force-app/main/default/objects/AdditionalChargeCredit__c/AdditionalChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Related object that functions as an auxiliary Product catalog. Good for charge lines, such Shipping &amp; Handling Fee</description>
    <label>Additional Charge and Credit</label>
    <nameField>
        <label>Additional Charge/Credit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Charges and Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AdditionalChargeCredit__c/fields/DefaultLineDescription__c.field-meta.xml
<CustomField>
    <fullName>DefaultLineDescription__c</fullName>
    <description>Sets the initial Line Description text in Quote and Order configurator page.</description>
    <inlineHelpText>Sets the initial Line Description text in Quote and Order configurator page</inlineHelpText>
    <label>Default Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeCredit__c/fields/DefaultQuantity__c.field-meta.xml
<CustomField>
    <fullName>DefaultQuantity__c</fullName>
    <description>Sets the initial Quantity value in Quote and Order configurator page. If blank, the Default Quantity is 1.</description>
    <inlineHelpText>Sets the initial Quantity value in Quote and Order configurator page. If blank, the Default Quantity is 1</inlineHelpText>
    <label>Default Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeCredit__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeCredit__c/fields/LockLineDescription__c.field-meta.xml
<CustomField>
    <fullName>LockLineDescription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Prevents Line Description to be editable in Quote and Order configurator page. Does not lock the Line Description at the record level.</description>
    <inlineHelpText>Prevents Line Description to be editable in Quote and Order configurator page. Does not lock the Line Description at the record level</inlineHelpText>
    <label>Lock Line Description</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeCredit__c/fields/LockQuantity__c.field-meta.xml
<CustomField>
    <fullName>LockQuantity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Prevents Quantity to be editable in Quote and Order configurator page. Does not lock the Quantity at the record level.</description>
    <inlineHelpText>Prevents Quantity to be editable in Quote and Order configurator page. Does not lock the Quantity at the record level</inlineHelpText>
    <label>Lock Quantity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeCredit__c/fields/LockUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>LockUnitPrice__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Prevents Unit Price to be editable in Quote and Order configurator page. Does not lock the Unit Price at the record level.</description>
    <inlineHelpText>Prevents Unit Price to be editable in Quote and Order configurator page. Does not lock the Unit Price at the record level</inlineHelpText>
    <label>Lock Unit Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeCredit__c/fields/MaximumQuantity__c.field-meta.xml
<CustomField>
    <fullName>MaximumQuantity__c</fullName>
    <description>Sets the maximum Quantity value limit in Quote and Order configurator page.</description>
    <inlineHelpText>Sets the maximum Quantity value limit in Quote and Order configurator page</inlineHelpText>
    <label>Maximum Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeCredit__c/fields/MinimumQuantity__c.field-meta.xml
<CustomField>
    <fullName>MinimumQuantity__c</fullName>
    <description>Sets the minimum Quantity value limit in Quote and Order configurator page.</description>
    <inlineHelpText>Sets the minimum Quantity value limit in Quote and Order configurator page</inlineHelpText>
    <label>Minimum Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeCredit__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/SalesOrderAdditionalChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Charges and Credits.</description>
    <label>Order Additional Charge and Credit</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Additional Charge/Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Additional Charges and Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/Additional_Charge_Credit__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charge_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional Charge/Credit</label>
    <referenceTo>AdditionalChargeCredit__c</referenceTo>
    <relationshipName>Order_Additional_Charges_Credits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/Line_Total__c.field-meta.xml
<CustomField>
    <fullName>Line_Total__c</fullName>
    <formula>Quantity__c *  SalesPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/LineDescription__c.field-meta.xml
<CustomField>
    <fullName>LineDescription__c</fullName>
    <label>Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Additional_Charges_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ManageChargesCreditsController.cls
public with sharing class ManageChargesCreditsController {
  @AuraEnabled
  public static String addNewOrderChargesCredits(List<Id> ccIds, Id soId) {
    List<AdditionalChargeCredit__c> selectedACCs = [
      SELECT
        Id,
        Name,
        DefaultQuantity__c,
        DefaultLineDescription__c,
        UnitPrice__c,
        MinimumQuantity__c
      FROM AdditionalChargeCredit__c
      WHERE Id IN :ccIds
    ];

    List<SalesOrderAdditionalChargeCredit__c> generatedSOACCs = new List<SalesOrderAdditionalChargeCredit__c>();

    for (AdditionalChargeCredit__c acc : selectedACCs) {
      SalesOrderAdditionalChargeCredit__c soacc = new SalesOrderAdditionalChargeCredit__c();
      soacc.Quantity__c = acc.DefaultQuantity__c != null
        ? acc.DefaultQuantity__c
        : (acc.MinimumQuantity__c != null ? acc.MinimumQuantity__c : 1);
      soacc.LineDescription__c = String.isEmpty(acc.DefaultLineDescription__c) ? '' : acc.DefaultLineDescription__c;
      soacc.SalesPrice__c = acc.UnitPrice__c != null ? (Decimal) acc.UnitPrice__c : 0;
      soacc.Date__c = Date.today();
      soacc.SalesOrder__c = soId;
      soacc.Additional_Charge_Credit__c = acc.Id;
      generatedSOACCs.add(soacc);
    }

    try {
      Database.insert(generatedSOACCs, false);

    List<SalesOrderAdditionalChargeCredit__c> results = [
      SELECT
        Id,
        Additional_Charge_Credit__r.Name,
        Quantity__c,
        SalesPrice__c,
        LineDescription__c,
        Date__c,
        Line_Total__c,
        Additional_Charge_Credit__r.LockLineDescription__c,
        Additional_Charge_Credit__r.LockQuantity__c,
        Additional_Charge_Credit__r.LockUnitPrice__c,
        Additional_Charge_Credit__r.MaximumQuantity__c,
        Additional_Charge_Credit__r.MinimumQuantity__c
      FROM SalesOrderAdditionalChargeCredit__c
      WHERE Id in :generatedSOACCs
    ];

    return JSON.serialize(results);
    } catch (DmlException err) {
      System.Debug(err.getMessage());
      Map<String, String> errMap = new Map<String, String>();
      errMap.put('Error', err.getMessage());
      return JSON.serialize(errMap);
    }
  }

    // @AuraEnabled(cacheable=true)
  // public static String generateChargesCredits() {
  //   List<AdditionalChargeCredit__c> chargesCredits = [
  //     SELECT Id, Name, Description__c, UnitPrice__c
  //     FROM AdditionalChargeCredit__c
  //     WHERE IsActive__c = TRUE
  //   ];

  //   for(AdditionalChargeCredit__c c : chargesCredits) {
  //     if(c.UnitPrice__c == null) {
  //       c.UnitPrice__c = 0;
  //     }
  //   }

  //   return JSON.serialize(chargesCredits);
  // }

  // @AuraEnabled(cacheable=true)
  // public static String generateOrderChargesCredits(Id recordId) {
  //   List<SalesOrderAdditionalChargeCredit__c> results = [
  //     SELECT
  //       Id,
  //       Additional_Charge_Credit__r.Name,
  //       Quantity__c,
  //       SalesPrice__c,
  //       LineDescription__c,
  //       Date__c,
  //       Line_Total__c,
  //       Additional_Charge_Credit__r.LockLineDescription__c,
  //       Additional_Charge_Credit__r.LockQuantity__c,
  //       Additional_Charge_Credit__r.LockUnitPrice__c,
  //       Additional_Charge_Credit__r.MaximumQuantity__c,
  //       Additional_Charge_Credit__r.MinimumQuantity__c,
  //       Additional_Charge_Credit__c
  //     FROM SalesOrderAdditionalChargeCredit__c
  //     WHERE SalesOrder__c = :recordId
  //   ];

  //   return JSON.serialize(results);
  // }

  // @AuraEnabled
  // public static String saveOrderAdditionalChargeCredit(List<SalesOrderAdditionalChargeCredit__c> records) {
  //   Map<String, List<Object>> returnMap = new Map<String, List<Object>>();
  //   try {
  //     Database.upsert(records);
  //     List<SalesOrderAdditionalChargeCredit__c> result = [
  //       SELECT
  //       Id,
  //       Additional_Charge_Credit__r.Name,
  //       Additional_Charge_Credit__c,
  //       Quantity__c,
  //       SalesPrice__c,
  //       LineDescription__c,
  //       Date__c,
  //       Line_Total__c,
  //       Additional_Charge_Credit__r.LockLineDescription__c,
  //       Additional_Charge_Credit__r.LockQuantity__c,
  //       Additional_Charge_Credit__r.LockUnitPrice__c,
  //       Additional_Charge_Credit__r.MaximumQuantity__c,
  //       Additional_Charge_Credit__r.MinimumQuantity__c
  //     FROM SalesOrderAdditionalChargeCredit__c
  //     WHERE Id IN :records
  //     ];
  //     returnMap.put('Data', result);
  //     return JSON.serialize(returnMap);
  //   } catch (DmlException err) {
  //     returnMap.put('Error', new List<Object>{err.getMessage()});
  //     return JSON.serialize(returnMap);
  //   }
  // }

  // @AuraEnabled
  // public static String deleteOrderChargesCredits(List<SalesOrderAdditionalChargeCredit__c> records) {
  //   Map<String, String> statusMap = new Map<String, String>();
  //   try {
  //     Database.delete(records);
  //     statusMap.put('Success', 'Delete success');
  //     return JSON.serialize(statusMap);
  //   } catch (DmlException err) {
  //     statusMap.put('Error', err.getMessage());
  //     return JSON.serialize(statusMap);
  //   }
  // } 

}