force-app/main/default/objects/AdditionalChargeCredit__c/AdditionalChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Related object that functions as an auxiliary Product catalog. Good for charge lines, such Shipping &amp; Handling Fee</description>
    <label>Additional Charge and Credit</label>
    <nameField>
        <label>Additional Charge/Credit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Charges and Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/Order_Line_Recipient__c.object-meta.xml
<CustomObject>
    <label>Order Line Recipient</label>
    <nameField>
        <displayFormat>OLR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SalesOrderProductLine__c.SalesOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Order_Line_Recipients1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <formula>Order__r.Release_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Release Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Release_Status__c.field-meta.xml
<CustomField>
    <fullName>Release_Status__c</fullName>
    <formula>Order__r.RecordStatus__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Release Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/DateApproved__c.field-meta.xml
<CustomField>
    <fullName>DateApproved__c</fullName>
    <description>Initial Order Date Approved from Draft or Sent Record Status. If Order is Released from Draft or Sent Record Status, then Date Approved equals Date Released.</description>
    <label>Date Approved</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/DateCancelled__c.field-meta.xml
<CustomField>
    <fullName>DateCancelled__c</fullName>
    <description>Date Order Cancelled</description>
    <label>Date Cancelled</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/DateReleased__c.field-meta.xml
<CustomField>
    <fullName>DateReleased__c</fullName>
    <description>Initial Order Date Released. Date Released will not be updated to BLANK when Order is Unreleased.</description>
    <label>Date Released</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/DateRequired__c.field-meta.xml
<CustomField>
    <fullName>DateRequired__c</fullName>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Required</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/DateSent__c.field-meta.xml
<CustomField>
    <fullName>DateSent__c</fullName>
    <description>Initial Order Date Sent via Email PDF / Email Link function</description>
    <label>Date Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Down_Payment__c</fullName>
    <label>Down Payment</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/FinanceOverride__c.field-meta.xml
<CustomField>
    <fullName>FinanceOverride__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check Before Unreleasing an Order, Prevents Release Automation from Firing.</inlineHelpText>
    <label>Finance Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/FulfillOrder__c.field-meta.xml
<CustomField>
    <fullName>FulfillOrder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fulfill Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Initial_Invoice_Sent__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initial Invoice Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/OrderDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <label>Release Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Release_Status__c.field-meta.xml
<CustomField>
    <fullName>Release_Status__c</fullName>
    <label>Release Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Released__c.field-meta.xml
<CustomField>
    <fullName>Released__c</fullName>
    <label>Released</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>Payment Update Needed</fullName>
            </value>
            <value>
                <fullName>Subscription Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/SalesOrderAdditionalChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Charges and Credits.</description>
    <label>Order Additional Charge and Credit</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Additional Charge/Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Additional Charges and Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/Additional_Charge_Credit__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charge_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional Charge/Credit</label>
    <referenceTo>AdditionalChargeCredit__c</referenceTo>
    <relationshipName>Order_Additional_Charges_Credits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Additional_Charges_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/Void_Date__c.field-meta.xml
<CustomField>
    <fullName>Void_Date__c</fullName>
    <label>Void Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/DateRequired__c.field-meta.xml
<CustomField>
    <fullName>DateRequired__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date Required</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/KitBundleLine__c.field-meta.xml
<CustomField>
    <fullName>KitBundleLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit/Bundle Line</label>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Recipient_Count__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Recipient Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Void_Date__c.field-meta.xml
<CustomField>
    <fullName>Void_Date__c</fullName>
    <label>Adjustment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BoomOrderCloneController.cls
public without sharing class BoomOrderCloneController {
  public static final String FINANCE_FEE_ACC = 'Multi payment Convenience Fee';
  public static final String DISC_PRODUCTNAME = 'Discount';

  @AuraEnabled
  public static Id cloneBoomOrder(Id recordId) {
    Savepoint sp = Database.setSavepoint();
    try {
      String editableFields = getEditableFields('SalesOrder__c');
      String soql =
        'SELECT ' +
        editableFields +
        ' FROM SalesOrder__c WHERE Id = \'' +
        recordId +
        '\' LIMIT 1';
      SalesOrder__c boomOrder = Database.query(soql);
      SalesOrder__c clonedOrder = boomOrder.clone(false, true, false, false);
      clonedOrder.Down_Payment__c= 0;
      clonedOrder.Approval_Status__c = 'Pending';
      clonedOrder.Status_Picklist__c = 'Draft';
      clonedOrder.Release_Status__c = null;
      clonedOrder.DateReleased__c = null;
      clonedOrder.DateApproved__c = null;
      clonedOrder.DateCancelled__c = null;
      clonedOrder.DateSent__c = null;
      clonedOrder.Release_Date__c = null;
      clonedOrder.OrderDate__c = System.today();
      clonedOrder.Released__c = null;
      clonedOrder.FulfillOrder__c = false;
      clonedOrder.FinanceOverride__c = false;
      clonedOrder.Legacy_Id__c = null;
      clonedOrder.Initial_Invoice_Sent__c = false;
      insert clonedOrder;
      cloneOrderProductLines(recordId, clonedOrder.Id);
      cloneAdditionalChargeCredit(recordId, clonedOrder.Id);
      return clonedOrder.Id;
    } catch (Exception e) {
      Database.rollback(sp);
      System.debug('Line '+ e.getLineNumber() + ':' + e.getMessage());
      throw new AuraHandledException(e.getMessage());
    }
  }

  public static void cloneAdditionalChargeCredit(
    Id oldBoomOrderId,
    Id newBoomOrderId
  ) {
    Savepoint sp = Database.setSavepoint();
    List<AdditionalChargeCredit__c> acc = [SELECT Id FROM AdditionalChargeCredit__c WHERE Name = :FINANCE_FEE_ACC AND IsActive__c = true LIMIT 1];
    try {
      String editableFields = getEditableFields(
        'SalesOrderAdditionalChargeCredit__c'
      );
      String soql =
        'SELECT ' +
        editableFields +
        ' FROM SalesOrderAdditionalChargeCredit__c WHERE SalesOrder__c = \'' +
        oldBoomOrderId +
        '\'';
      List<SalesOrderAdditionalChargeCredit__c> oldACCs = Database.query(soql);
      if (oldACCs.size() > 0) {
        List<SalesOrderAdditionalChargeCredit__c> newACCs = new List<SalesOrderAdditionalChargeCredit__c>();
        for (SalesOrderAdditionalChargeCredit__c oA : oldACCs) {
          if(acc.size() > 0 && oA.Additional_Charge_Credit__c == acc[0].Id){
            continue;
          }
            SalesOrderAdditionalChargeCredit__c nA = oA.clone(false, true, false, false);
            nA.SalesOrder__c = newBoomOrderId;
            nA.Adjustment_Date__c = null;
            nA.Intacct_Sync_Complete__c = false;
            nA.Legacy_Id__c = null;
            newACCs.add(nA);
        }
        insert newACCs;
      }
    } catch (Exception e) {
      Database.rollback(sp);
      throw new AuraHandledException(e.getMessage());
    }
  }

  public static void cloneOrderProductLines(
    Id oldBoomOrderId,
    Id newBoomOrderId
  ) {
    Savepoint sp = Database.setSavepoint();
    List<Product2> discProd = [SELECT Id FROM Product2 WHERE Name = :DISC_PRODUCTNAME AND IsActive = true LIMIT 1];

    try {
      String editableFields = getEditableFields('SalesOrderProductLine__c');
      String soql =
        'SELECT ' +
        editableFields +
        ', (SELECT Id, Recipient__c, Primary__c FROM Order_Line_Recipients__r)' +
        ' FROM SalesOrderProductLine__c WHERE SalesOrder__c = \'' +
        oldBoomOrderId +
        '\'';
      List<SalesOrderProductLine__c> oldOrderProductLines = Database.query(
        soql
      );
      if (oldOrderProductLines.size() > 0) {
        Map<Id, SalesOrderProductLine__c> clonedOrderProductLines = new Map<Id, SalesOrderProductLine__c>();
        Map<Id, List<Order_Line_Recipient__c>> oldOrderLineRecipients = new Map<Id, List<Order_Line_Recipient__c>>();
        for (
          SalesOrderProductLine__c oldOrderProductLine : oldOrderProductLines
        ) {
          if(discProd.size() > 0 && oldOrderProductLine.Product__c == discProd[0].Id) {
            continue;
          }
          if (oldOrderProductLine.KitBundleLine__c == null) {
            SalesOrderProductLine__c clonedOrderProductLine = oldOrderProductLine.clone(
              false,
              true,
              false,
              false
            );
            
            oldOrderLineRecipients.put(
              oldOrderProductLine.Id,
              oldOrderProductLine.Order_Line_Recipients__r
            );
            String clonedJson = JSON.serialize(clonedOrderProductLine);
            clonedJson =
              clonedJson.substringBefore(',"Order_Line_Recipients__r"') +
              clonedJson.substringAfter(']');
            
            clonedOrderProductLine = (SalesOrderProductLine__c) JSON.deserialize(
              clonedJson,
              SalesOrderProductLine__c.class
            );
            clonedOrderProductLine.SalesOrder__c = newBoomOrderId;
            clonedOrderProductLine.Recipient_Count__c = 0;
            clonedOrderProductLine.DateRequired__c = System.today();
            clonedOrderProductLine.Void_Date__c = null;
            clonedOrderProductLine.Legacy_Id__c = null;
            clonedOrderProductLine.Intacct_Sync_Complete__c = false;
            clonedOrderProductLines.put(
              oldOrderProductLine.Id,
              clonedOrderProductLine
            );
          }
        }

        try {
          insert clonedOrderProductLines.values();
        } catch (DmlException err) {
          System.debug('Error on cloning product lines: ' + err.getMessage());
          throw err;
        }


        List<Order_Line_Recipient__c> autoGeneratedRecipients = [
          SELECT Id
          FROM Order_Line_Recipient__c
          WHERE OrderProductLine__c = :clonedOrderProductLines.values()
        ];

        // delete automatically generated recipients generated by trigger
        
        try {
          delete autoGeneratedRecipients;
        } catch (DmlException err) {
          System.debug('From deleting recipients generated by trigger: ' + err.getMessage());
          throw err;
        }

        List<Order_Line_Recipient__c> newRecipients = new List<Order_Line_Recipient__c>();
        for (Id oldId : clonedOrderProductLines.keySet()) {
          SalesOrderProductLine__c clonedPL = clonedOrderProductLines.get(
            oldId
          );
          for(Order_Line_Recipient__c oldRecipient : oldOrderLineRecipients.get(oldId)) {
            Order_Line_Recipient__c newRecipient = new Order_Line_Recipient__c();
            newRecipient.Recipient__c = oldRecipient.Recipient__c;
            newRecipient.Order__c = newBoomOrderId;
            newRecipient.OrderProductLine__c = clonedPL.Id;
            newRecipient.Primary__c = oldRecipient.Primary__c;
            newRecipient.Legacy_Id__c = null;
            newRecipients.add(newRecipient);
          }
        }

        try {
          insert newRecipients;
        } catch (DmlException err) {
          System.debug('From inserting new recipients '+ err.getLineNumber() + ':' + err.getMessage());
          throw err;
        }
        
      }
    } catch (Exception e) {
      Database.rollback(sp);
      throw new AuraHandledException(e.getMessage());
    }
  }

  public static String getEditableFields(String sobjectName) {
    Map<String, Schema.SObjectField> fields = Schema.getGlobalDescribe()
      .get(sobjectName)
      .getDescribe()
      .fields.getMap();
    String editableFields = '';
    for (Schema.SObjectField fieldRef : fields.values()) {
      Schema.DescribeFieldResult fieldResult = fieldRef.getDescribe();
      if (fieldResult.isUpdateable()) {
        editableFields += fieldResult.getname() + ',';
      }
    }
    editableFields = editableFields.removeEnd(',');
    return editableFields;
  }
}