force-app/main/default/objects/Order_Line_Recipient__c/Order_Line_Recipient__c.object-meta.xml
<CustomObject>
    <label>Order Line Recipient</label>
    <nameField>
        <displayFormat>OLR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SalesOrderProductLine__c.SalesOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total transaction amount (including tax, shipping and fees)</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <inlineHelpText>Actual date of payment.</inlineHelpText>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <inlineHelpText>Details about the transaction.</inlineHelpText>
    <label>Memo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check or Money Order</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>ECheck</fullName>
            </value>
            <value>
                <fullName>Electronic Funds Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Scheduled_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment_Date__c</fullName>
    <inlineHelpText>Scheduled Payment Date is the date on which payment is expected to be paid, and may be used to trigger payment reminders using workflow rules.</inlineHelpText>
    <label>Scheduled Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Display_Name__c</fullName>
    <description>This field is used to &apos;override&apos; the product name when displaying inside the My Orders environment. If not data is in this field, the Product Name will be displayed. If data is in this field, the Product Display Name will be displayed.</description>
    <inlineHelpText>This field is used to &apos;override&apos; the product name when displaying inside the My Orders environment. If not data is in this field, the Product Name will be displayed. If data is in this field, the Product Display Name will be displayed.</inlineHelpText>
    <label>Product Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Account Name, which is required. 

To change the required Account name, please update the Additional Account Info field on this Order. If the field is not visible, please contact your Administrator. For Released or Paid Orders, please also update the Invoice and Payment records.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/AdditionalChargeCreditAmount__c.field-meta.xml
<CustomField>
    <fullName>AdditionalChargeCreditAmount__c</fullName>
    <label>Additional Charge/Credit Amount</label>
    <summarizedField>SalesOrderAdditionalChargeCredit__c.AdditionalChargeCreditAmount__c</summarizedField>
    <summaryForeignKey>SalesOrderAdditionalChargeCredit__c.SalesOrder__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactBilling__c.field-meta.xml
<CustomField>
    <fullName>ContactBilling__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactBuying__c.field-meta.xml
<CustomField>
    <fullName>ContactBuying__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Buying</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/DateAvailableToPromise__c.field-meta.xml
<CustomField>
    <fullName>DateAvailableToPromise__c</fullName>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Available to Promise</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <label>Memo on Invoice</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>round(ProductAmount__c - TotalDiscountAmount__c,2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/SalesOrderAdditionalChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Charges and Credits.</description>
    <label>Order Additional Charge and Credit</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Additional Charge/Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Additional Charges and Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/Additional_Charge_Credit__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charge_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional Charge/Credit</label>
    <referenceTo>AdditionalChargeCredit__c</referenceTo>
    <relationshipName>Order_Additional_Charges_Credits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/LineDescription__c.field-meta.xml
<CustomField>
    <fullName>LineDescription__c</fullName>
    <label>Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <formula>Additional_Charge_Credit__r.Name &amp; &quot;;&quot; &amp; SalesOrder__r.ContactBuying__r.FirstName &amp; SalesOrder__r.ContactBuying__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Memo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Additional_Charges_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Actual_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Price__c</fullName>
    <formula>( Quantity__c *  SalesPrice__c  )  -  LineDiscountAmount__c -  OrderDiscountAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/DateAvailableToPromise__c.field-meta.xml
<CustomField>
    <fullName>DateAvailableToPromise__c</fullName>
    <label>Date Available To Promise</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/DiscountSalesPrice__c.field-meta.xml
<CustomField>
    <fullName>DiscountSalesPrice__c</fullName>
    <description>Effective Price is the Sales Price with Discounts Applied.</description>
    <formula>If(
  Quantity__c = 0,
  round(SalesPrice__c * (1 - (OrderDiscountPercent__c + LineDiscountPercent__c)), 2),
  round(TotalAmount__c / Quantity__c, 2)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Effective Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Display_Name_for_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Display_Name_for_Invoice__c</fullName>
    <label>Display Name for Invoice</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/ListPrice__c.field-meta.xml
<CustomField>
    <fullName>ListPrice__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>round(ProductAmount__c   -  DiscountAmount__c,2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BoomEmailController.cls
public without sharing class BoomEmailController {
    public Id orderId { get; set; }

    public SalesOrder__c Order {get {
      if(orderId != null) {
        return querySalesOrder(orderId);
      } else {
        return null;
      }
    } private set;}

    public static SalesOrder__c querySalesOrder(Id recordId) {
      DescribeSObjectResult describeResult = recordId.getSObjectType()
        .getDescribe();
      List<String> fieldNames = new List<String>(
        describeResult.fields.getMap().keySet()
      );
      fieldNames.add('Owner.Name');
      fieldNames.add('ContactBilling__r.Name');
      fieldNames.add('ContactBilling__r.Email');
      fieldNames.add('ContactBilling__r.Phone');
      fieldNames.add('ContactBilling__r.Fax');
      fieldNames.add('ContactBuying__r.Name');
      fieldNames.add('ContactBuying__r.Email');
      fieldNames.add('ContactBuying__r.Phone');
      fieldNames.add('ContactBuying__r.Fax');
      fieldNames.add('Account__r.Name');
  
      String queryString =
        ' SELECT ' +
        String.join(fieldNames, ',') +
        ' FROM ' +
        describeResult.getName() +
        ' WHERE ' +
        ' id = :recordId ' +
        ' LIMIT 1 ';
      return database.query(queryString);
    }

    public list<SalesOrderProductLine__c> ProductLines {
        get {
          if (orderId != null) {
            ProductLines = [
              SELECT
                Id,
                Display_Name_for_Invoice__c,
                Product__r.Name,
                Product__r.Product_Display_Name__c,
                ListPrice__c,
                Name,
                LineDescription__c,
                Quantity__c,
                Actual_Price__c,
                TotalAmount__c,
                DateAvailableToPromise__c,
                DiscountSalesPrice__c
              FROM SalesOrderProductLine__c
              WHERE SalesOrder__c = :orderId
            ];
          } else {
            ProductLines = new List<SalesOrderProductLine__c>();
          }
          return ProductLines;
        }
        private set;
      }

      public Integer ProductLineCount {
        get {
            return ProductLines != null && ProductLines.size() > 0 ? ProductLines.size() : 0;
         } private set;
     }

    public SalesOrderPDFExtension.SettingResource settings {
        get {
          if (settings == null) {
            settings = new SalesOrderPDFExtension.SettingResource();
          }
          return settings;
        }
        private set;
      }

    public list<SalesOrderAdditionalChargeCredit__c> ACCLines {
        get {
          if (orderId != null) {
            ACCLines = [
              SELECT
                LineDescription__c,
                Date__c,
                Quantity__c,
                SalesPrice__c,
                AdditionalChargeCreditAmount__c,
                Additional_Charge_Credit__r.Name
              FROM SalesOrderAdditionalChargeCredit__c
              WHERE SalesOrder__c = :orderId
            ];
          } else {
            ACCLines = new List<SalesOrderAdditionalChargeCredit__c>();
          }
    
          return ACCLines;
        }
        private set;
      }

      public Integer ChargeCreditLineCount {
        get {
            return ACCLines != null ? ACCLines.size() : 0;
         } private set;
      }

      public list<Payment__c> PaymentSchedules {
        get {
          if (
            orderId != null ) {
            PaymentSchedules = [
              SELECT
                Scheduled_Payment_Date__c,
                Id,
                Date__c,
                Payment_Type__c,
                Memo__c,
                Amount__c,
                Contact__r.Name,
                CardType__c,
                Last_Four_Digits__c,
                Status__c,
                Billing_Name__c
              FROM Payment__c
              WHERE Sales_Order__c = :orderId AND Status__c = 'Scheduled'
              ORDER BY Date__c
            ];
          } else {
            PaymentSchedules = new List<Payment__c>();
          }
          return PaymentSchedules;
        }
        private set;
      }

      public list<Order_Line_Recipient__c> LineRecipients {
        get {
          if (orderId != null) {
            LineRecipients = queryLineRecipients(orderId);
          } else {
            LineRecipients = new List<Order_Line_Recipient__c>();
          }
          return LineRecipients;
        }
        private set;
      }
    
  public List<Payment__c> allPayments {
    get {
      if(orderId != null && (allPayments == null || allPayments.size() < 1) && PaymentSchedules != null && Payments != null) {
        List<Payment__c> newList = new List<Payment__c>();
        newList.addAll(Payments);
        newList.addAll(PaymentSchedules);
        return newList;
      } else {
        return new List<Payment__c>();
      }
    }
    private set;
  }

  public List<Payment__c> Payments {
    get {
      if (orderId != null) {
        Payments = [
          SELECT
            Id,
            Date__c,
            Payment_Type__c,
            Memo__c,
            Amount__c,
            Contact__r.Name,
            CardType__c,
            Last_Four_Digits__c,
            Status__c,
            Billing_Name__c
          FROM Payment__c
          WHERE Sales_Order__c = :orderId AND Status__c = 'Completed'
          ORDER BY Date__c
        ];
      } else {
        Payments = new List<Payment__c>();
      }

      return Payments;
    }
    private set;
  }

      public static list<Order_Line_Recipient__c> queryLineRecipients(Id orderId) {
        return orderId == null
          ? new List<Order_Line_Recipient__c>()
          : [
              SELECT
                Id,
                OrderLine__c,
                OrderProductLine__r.Product__r.Name,
                OrderProductLine__r.Product__r.Product_Display_Name__c,
                OrderProductLine__r.Display_Name_for_Invoice__c,
                Recipient__r.Name,
                Primary__c
              FROM Order_Line_Recipient__c
              WHERE Order__c = :orderId
              ORDER BY
                OrderProductLine__r.SortOrder__c NULLS LAST,
                Recipient__r.Name
            ];
      }
}