force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT (Status_Picklist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>Payment Update Needed</fullName>
            </value>
            <value>
                <fullName>Subscription Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Subscription</description>
    <inlineHelpText>Related Subscription</inlineHelpText>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Boom Orders</relationshipLabel>
    <relationshipName>Boom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/KitBundleLine__c.field-meta.xml
<CustomField>
    <fullName>KitBundleLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit/Bundle Line</label>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Related_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Related_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Sales Order Product Lines</relationshipLabel>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(SalesOrder__r.Status_Picklist__c)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <formula>Product__r.Subscription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Original_Subscription_Boom_Order__c.field-meta.xml
<CustomField>
    <fullName>Original_Subscription_Boom_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field displays the original order that was released with the new subscription</description>
    <inlineHelpText>This field displays the original order that was released with the new subscription</inlineHelpText>
    <label>Original Subscription Boom Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Parent_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Parent_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Renewal_Product__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the product that should be renewed at time of next renewal</description>
    <inlineHelpText>This is the product that should be renewed at time of next renewal</inlineHelpText>
    <label>Renewal Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/missedAddonsHelper.cls
public without sharing class missedAddonsHelper {
  public class MissedAddonResource {
    @AuraEnabled
    public List<SalesOrder__c> salesorders { get; set; }
    @AuraEnabled
    public Subscription__c subscription { get; set; }
  }

  @AuraEnabled
  public static List<MissedAddonResource> retrieveMissingAddons() {
    try {
      Map<Id, Subscription__c> subs = new Map<Id, Subscription__c>(
        [
          SELECT
            Id,
            Renewal_Product__c,
            (
              SELECT Id, Parent_Subscription__c, Renewal_Product__c, Name, Parent_Subscription__r.Name
              FROM Subscriptions__r
              WHERE Status__c = 'Active'
            )
          FROM Subscription__c
          WHERE status__c = 'Active'
        ]
      );

      List<MissedAddonResource> retVal = new List<MissedAddonResource>();
      List<SalesOrder__c> orders = [
        SELECT
          Id,
          Subscription__c,
          Name,
          Status_Picklist__c,
          (SELECT id, product__c FROM Sales_Order_Product_Lines__r)
        FROM salesorder__c
        WHERE subscription__c IN :subs.keySet()
      ];

      Map<Subscription__c, List<SalesOrder__c>> orderMap = new Map<Subscription__c, List<SalesOrder__c>>();

      for (SalesOrder__c o : orders) {
        Subscription__c s = subs.get(o.Subscription__c);
        List<SalesOrderProductLine__c> sopls = o.Sales_Order_Product_Lines__r;
        List<Id> prodIds = new List<Id>();
        List<Subscription__c> addons = s.Subscriptions__r;
        for (SalesOrderProductLine__c pl : sopls) {
          prodIds.add(pl.Product__c);
        }
        for (Subscription__c ao : addons) {
          List<SalesOrder__c> aos = orderMap.containsKey(ao) ? orderMap.get(ao) : new List<SalesOrder__c>();
          if (!prodIds.contains(ao.Renewal_Product__c)) {
            aos.add(o);
            orderMap.put(ao, aos);
          } else {
            prodIds.remove(prodIds.indexOf(ao.Renewal_Product__c));
          }
        }
      }
      for(Subscription__c s : orderMap.keySet()) {
        MissedAddonResource m = new MissedAddonResource();
        m.subscription = s;
        m.salesorders = orderMap.get(s);
        retVal.add(m);
      }
      return retVal;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}