force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/OrderDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT (Status_Picklist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>Payment Update Needed</fullName>
            </value>
            <value>
                <fullName>Subscription Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Subscription</description>
    <inlineHelpText>Related Subscription</inlineHelpText>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Boom Orders</relationshipLabel>
    <relationshipName>Boom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Create_Next_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Create_Next_Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Hidden field for automating creation of next period&apos;s subscription order.</description>
    <label>Create Next Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Parent_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Parent_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payment_Method__c.Inactive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <valueField>Payment_Method__c.Contact__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Renewal_Date_Day_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date_Day_of_Month__c</fullName>
    <label>Renewal Date (Day of Month)</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MissedSubscriptionsBatch.cls
global class MissedSubscriptionsBatch implements Database.Batchable<sObject>,Database.Stateful{
    private String queryString;

    global MissedSubscriptionsBatch() {
        if(String.isBlank(queryString)) {
            queryString = 'SELECT Id';
            queryString += ' FROM Subscription__c';
            queryString += ' WHERE  Status__c = \'Active\' AND Parent_Subscription__c = null AND Payment_Method__c != null';
            queryString += ' AND Id NOT IN (SELECT Subscription__c from SalesOrder__c where Subscription__c != null and OrderDate__c > TODAY and Status_Picklist__c = \'Pending Renewal\')';
            queryString += ' AND Id in (SELECT Subscription__c from SalesOrder__c where Subscription__c != null and OrderDate__c <= TODAY and Status_Picklist__c = \'Released\')';
        }
        
        if (Test.isRunningTest()) {
            queryString = 'SELECT Id';
            queryString += ' FROM Subscription__c';
            queryString += ' LIMIT 1';
        }
    }

    // select id, Create_Next_Subscription__c, Renewal_Date_Day_of_Month__c  from subscription__c where Status__c = 'Active' and Parent_Subscription__c = null and 
    // id not in (select subscription__c from salesorder__c where subscription__c != null and orderdate__c = NEXT_MONTH and status_picklist__c = 'Pending Renewal') and id in (select subscription__c from salesorder__c where subscription__c != null and orderdate__c = THIS_MONTH and status_picklist__c != 'Pending Renewal')

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(queryString);
    }

    global void execute(Database.BatchableContext info, List<Subscription__c> scope) {
        List<Subscription__c> updatedSubs = new List<Subscription__c>();

        for(Subscription__c sub : scope) {

            sub.Create_Next_Subscription__c = true;

            updatedSubs.add(sub);
        }

        List<Subscription__c> childrenSubs = [
            SELECT Id FROM Subscription__c WHERE Parent_Subscription__c IN :updatedSubs AND Status__c = 'Active'
        ];

        if(childrenSubs.size() > 0) {
            for(Subscription__c sub : childrenSubs) {
                sub.Create_Next_Subscription__c = true;
                updatedSubs.add(sub);
            }
        }

        if(updatedSubs.size() > 0) {
            Database.update(updatedSubs, false);
        }
    }

    global void finish(Database.BatchableContext info) {
        
    }
}