force-app/main/default/objects/Fulfillment__c/Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Fulfillment Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <referenceTo>kugo2p__SalesOrderProductLine__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>OrderProductLine__r.kugo2p__Quantity__c</description>
    <formula>Boom_Order_Product_Line__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Kit_Bundle_Member__c/Kit_Bundle_Member__c.object-meta.xml
<CustomObject>
    <label>Kit/Bundle Member</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Kit/Bundle Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kit/Bundle Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kit_Bundle_Member__c/fields/AllowQuantityChange__c.field-meta.xml
<CustomField>
    <fullName>AllowQuantityChange__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Kit/Bundle Member Lines only. Allows Quantity to be editable in Quote and Order configurator page. Does not lock the Quantity at the record level</description>
    <label>Edit Quantity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Kit_Bundle_Member__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Default Quantity value. Sets the initial Quantity value in Quote and Order configurator page. If blank, the Default Quantity is 1</description>
    <label>Default Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Kit_Bundle_Member__c/fields/ReferenceKitBundle__c.field-meta.xml
<CustomField>
    <fullName>ReferenceKitBundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit/Bundle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Kit/Bundle Members</relationshipLabel>
    <relationshipName>KitBundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kit_Bundle_Member__c/fields/ReferenceMemberProduct__c.field-meta.xml
<CustomField>
    <fullName>ReferenceMemberProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Member of Kit/Bundles</relationshipLabel>
    <relationshipName>KitsBundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kit_Bundle_Member__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Member is included in Kit/Bundle. Cannot be removed.</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/Order_Line_Recipient__c.object-meta.xml
<CustomObject>
    <label>Order Line Recipient</label>
    <nameField>
        <displayFormat>OLR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SalesOrderProductLine__c.SalesOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Order_Line_Recipients1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Tax__mdt/Sales_Tax__mdt.object-meta.xml
<CustomObject>
    <label>Sales Tax</label>
    <pluralLabel>Sales Taxes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sales_Tax__mdt/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/ContactShipping__c.field-meta.xml
<CustomField>
    <fullName>ContactShipping__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Shipping</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SalesOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/DateRequired__c.field-meta.xml
<CustomField>
    <fullName>DateRequired__c</fullName>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Required</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ShipToStateProvince__c.field-meta.xml
<CustomField>
    <fullName>ShipToStateProvince__c</fullName>
    <label>Ship To State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/AllowQuantityChange__c.field-meta.xml
<CustomField>
    <fullName>AllowQuantityChange__c</fullName>
    <defaultValue>true</defaultValue>
    <description>For Kit/Bundle Member Lines only. Allows Quantity to be editable in Quote and Order configurator page. Does not lock the Quantity at the record level. Checked by default</description>
    <label>Edit Quantity (Kit/Bundle Member)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/ContactShipping__c.field-meta.xml
<CustomField>
    <fullName>ContactShipping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Shipping</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/DateRequired__c.field-meta.xml
<CustomField>
    <fullName>DateRequired__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date Required</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/DiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAmount__c</fullName>
    <formula>round(LineDiscountAmount__c + OrderDiscountAmount__c, 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Kit_Bundle_Member__c.field-meta.xml
<CustomField>
    <fullName>Kit_Bundle_Member__c</fullName>
    <formula>IF( ISBLANK( KitBundleLine__c ) , false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Kit/Bundle Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Kit_Bundle_Product__c.field-meta.xml
<CustomField>
    <fullName>Kit_Bundle_Product__c</fullName>
    <description>Referenced to product</description>
    <formula>Product__r.IsKitBundle__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Kit/Bundle Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/KitBundle__c.field-meta.xml
<CustomField>
    <fullName>KitBundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kit/Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/KitBundleLine__c.field-meta.xml
<CustomField>
    <fullName>KitBundleLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit/Bundle Line</label>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/KitBundleMemberRequired__c.field-meta.xml
<CustomField>
    <fullName>KitBundleMemberRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kit/Bundle Member Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/ListPrice__c.field-meta.xml
<CustomField>
    <fullName>ListPrice__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Recipient_Count__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Recipient Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Sample_Parent_Order__c.field-meta.xml
<CustomField>
    <fullName>Sample_Parent_Order__c</fullName>
    <formula>SalesOrder__r.Sample_ELM_Copy__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sample Parent Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Sample_Product__c.field-meta.xml
<CustomField>
    <fullName>Sample_Product__c</fullName>
    <formula>Product__r.Sample_Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sample Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/ShipToStateProvince__c.field-meta.xml
<CustomField>
    <fullName>ShipToStateProvince__c</fullName>
    <formula>ContactShipping__r.MailingState</formula>
    <label>Ship To State/Province</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/State_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>State_Tax_Rate__c</fullName>
    <label>State Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Tax_Amount_Hidden__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Hidden__c</fullName>
    <description>Hidden field to calculate at rollup-- controlled by trigger</description>
    <label>Tax Amount Hidden</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/TaxAmount__c.field-meta.xml
<CustomField>
    <fullName>TaxAmount__c</fullName>
    <formula>ROUND(TotalAmount__c *  (TaxExciseRate__c + TaxSalesRate__c + TaxUsageRate__c + TaxVATRate__c), 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SalesOrderProductLineHelper.cls
public without sharing class SalesOrderProductLineHelper {

  /**
   * *************************************************************************
   * * uncomment everything below if I leave anything out *
   * *************************************************************************
   */

  public static void beforeInsert(List<SalesOrderProductLine__c> newObjs) {
    for (SalesOrderProductLine__c sopl : newObjs) {

      if (sopl.Kit_Bundle_Product__c == true) {
        sopl.KitBundle__c = true;
      }

      if (sopl.DateRequired__c == null) {
        sopl.DateRequired__c = System.today();
      }
      
    }

    System.debug('BEFORE INSERT');
  }

  public static void afterInsert(Map<Id, SalesOrderProductLine__c> newLines) {
    Map<Id, SalesOrderProductLine__c> parentLines = new Map<Id, SalesOrderProductLine__c>();
    List<SalesOrderProductLine__c> nonBundles = new List<SalesOrderProductLine__c>();
    Set<Id> orderIds = new Set<Id>();
    List<SalesOrderProductLine__c> taxableLines = new List<SalesOrderProductLine__c>();
    Set<Id> sampleOrders = new Set<Id>();
    Set<Id> desampleOrders = new Set<Id>();

    for (SalesOrderProductLine__c sopl : newLines.values()) {

      if (
        String.isNotEmpty(sopl.ShipToStateProvince__c) &&
        Sales_Tax__mdt.getInstance(sopl.ShipToStateProvince__c) != null
      ) {
        SalesOrderProductLine__c taxSopl = new SalesOrderProductLine__c();
        taxSopl.Id = sopl.Id;
        taxSopl.State_Tax_Rate__c = Sales_Tax__mdt.getInstance(
            sopl.ShipToStateProvince__c
          )
          .Rate__c;
        taxableLines.add(taxSopl);
      }

      if(sopl.Sample_Product__c == true) {
        sampleOrders.add(sopl.SalesOrder__c);
      }

      if(sopl.Sample_Parent_Order__c == true && sopl.Sample_Product__c != true && sopl.ListPrice__c != 0) {
        desampleOrders.add(sopl.SalesOrder__c);
      }

      if (sopl.Kit_Bundle_Product__c == true) {
        parentLines.put(sopl.Id, sopl);
      } else if (sopl.Kit_Bundle_Member__c != true) {
        nonBundles.add(sopl);
      }
      if (sopl.DiscountAmount__c != null && sopl.DiscountAmount__c > 0) {
        orderIds.add(sopl.SalesOrder__c);
      }
      
    }

    if (parentLines.size() > 0) {
      generateBundleMembers(parentLines);
    }

    if (nonBundles.size() > 0) {
      generateInitialRecipients(nonBundles);
    }

    if (taxableLines.size() > 0) {
      update taxableLines;
    }

    if(sampleOrders.size() > 0) {
      updateSampleOrders(sampleOrders);
    }

    if(desampleOrders.size() > 0) {
      unsetSampleOrders(desampleOrders);
    }
  }

  public static void beforeUpdate(
    List<SalesOrderProductLine__c> oldList,
    List<SalesOrderProductLine__c> newList
  ) {
    for (Integer i = 0; i < newList.size(); i++) {
      if (newList[i].TaxAmount__c != newList[i].Tax_Amount_Hidden__c) {
        newList[i].Tax_Amount_Hidden__c = newList[i].TaxAmount__c;
      }

      if(newList[i].Kit_Bundle_Product__c == true && newList[i].KitBundle__c != true) {
        newList[i].KitBundle__c = true;
      }
    }

    System.debug('BEFORE UPDATE');
  }

  public static void afterUpdate(
    List<SalesOrderProductLine__c> oldList,
    List<SalesOrderProductLine__c> newList
  ) {
    List<SalesOrderProductLine__c> taxUpdated = new List<SalesOrderProductLine__c>();
    Map<Id,SalesOrderProductLine__c> updChildren = new Map<Id,SalesOrderProductLine__c>();

    for (Integer i = 0; i < newList.size(); i++) {
      if (
        String.isNotEmpty(newList[i].ShipToStateProvince__c) &&
        Sales_Tax__mdt.getInstance(newList[i].ShipToStateProvince__c) != null &&
        (newList[i].ShipToStateProvince__c !=
        oldList[i].ShipToStateProvince__c ||
        newList[i].State_Tax_Rate__c !=
        Sales_Tax__mdt.getInstance(newList[i].ShipToStateProvince__c).Rate__c)
      ) {
        SalesOrderProductLine__c taxSopl = new SalesOrderProductLine__c();
        taxSopl.Id = newList[i].Id;
        taxSopl.State_Tax_Rate__c = Sales_Tax__mdt.getInstance(
            newList[i].ShipToStateProvince__c
          )
          .Rate__c;
        taxUpdated.add(taxSopl);
      }

      if((newList[i].Quantity__c != oldList[i].Quantity__c || newList[i].DateRequired__c != oldList[i].DateRequired__c) && newList[i].Kit_Bundle_Product__c == true) {
        updChildren.put(newList[i].Id, newList[i]);
      }

    }

    if (taxUpdated.size() > 0) {
      update taxUpdated;
    }

    if (updChildren.size() > 0) {
      updateChildren(updChildren);
    }
  }

  public static void beforeDelete(Map<Id, SalesOrderProductLine__c> oldMap) {
    Set<Id> kitBundles = new Set<Id>();
    Set<Id> withRecipients = new Set<Id>();

    Set<Id> forFulfillments = new Set<Id>();
    Map<Id, Id> sampleMap = new Map<Id, Id>();

    for (Id id : oldMap.keySet()) {

      forFulfillments.add(id);

      if (oldMap.get(id).Kit_Bundle_Product__c == true) {
        kitBundles.add(id);
      }

      if (oldMap.get(id).Recipient_Count__c > 0) {
        withRecipients.add(id);
      }

      if(oldMap.get(id).Sample_Product__c == true && oldMap.get(id).Sample_Parent_Order__c == true) {
        sampleMap.put(id, oldMap.get(id).SalesOrder__c);
      }
      
    }

    if (kitBundles.size() > 0) {
      deleteChildren(kitBundles);
    }
    if (withRecipients.size() > 0) {
      deleteRecipients(withRecipients);
    }

    if(sampleMap.size() > 0) {
      unsetDeletedSampleOrders(sampleMap);
    }

    if (forFulfillments.size() > 0) {
      deleteFulfillments(forFulfillments);
    }
  }

  public static void deleteChildren(Set<Id> kitBundles) {
    List<SalesOrderProductLine__c> rec = [
      SELECT Id, KitBundleLine__c
      FROM SalesOrderProductLine__c
      WHERE KitBundleLine__c IN :kitBundles
    ];

    try {
      System.debug(rec);

      delete rec;
    } catch (DmlException err) {
      System.debug('ON DELETE CHILDREN OF SALES ORDER PROD LINES ERROR ::: ');
      System.debug(err.getMessage());
    }
  }

  public static void updateChildren(Map<Id, SalesOrderProductLine__c> soplMap) {
    List<SalesOrderProductLine__c> recs = [
      SELECT Id, Quantity__c, KitBundleLine__c, DateRequired__c
      FROM SalesOrderProductLine__c 
      WHERE KitBundleLine__c IN :soplMap.keySet()
    ];

    for(SalesOrderProductLine__c r : recs) {
      r.Quantity__c = soplMap.get(r.KitBundleLine__c).Quantity__c;
      r.DateRequired__c = soplMap.get(r.KitBundleLine__c).DateRequired__c;
    }

    update recs;
    
  }

  public static void deleteRecipients(Set<Id> withRecipients) {
    List<Order_Line_Recipient__c> rec = [
      SELECT Id, OrderProductLine__c
      FROM Order_Line_Recipient__c
      WHERE OrderProductLine__c IN :withRecipients
    ];

    try {
      delete rec;
    } catch (DmlException err) {
      System.debug('ON DELETE RECIPIENTS OF SALES ORDER PROD LINES ERROR ::: ');
      System.debug(err.getMessage());
    }
  }

  public static void generateBundleMembers(
    Map<Id, SalesOrderProductLine__c> parentLines
  ) {
    List<Kit_Bundle_Member__c> kitMembers = [
      SELECT
        Id,
        Quantity__c,
        AllowQuantityChange__c,
        ReferenceKitBundle__c,
        ReferenceMemberProduct__c,
        Required__c
      FROM Kit_Bundle_Member__c
      WHERE
        ReferenceKitBundle__c IN (
          SELECT Product__c
          FROM SalesOrderProductLine__c
          WHERE Id IN :parentLines.keySet() AND Product__c != NULL
        )
    ];

    if (kitMembers.size() > 0) {
      Map<Id, List<Kit_Bundle_Member__c>> bundleMap = new Map<Id, List<Kit_Bundle_Member__c>>();

      for (Kit_Bundle_Member__c m : kitMembers) {
        List<Kit_Bundle_Member__c> mList = new List<Kit_Bundle_Member__c>();
        if (bundleMap.containsKey(m.ReferenceKitBundle__c)) {
          mList = bundleMap.get(m.ReferenceKitBundle__c);
        }
        mList.add(m);
        bundleMap.put(m.ReferenceKitBundle__c, mList);
      }

      List<SalesOrderProductLine__c> newOPLs = new List<SalesOrderProductLine__c>();
      for (Id key : parentLines.keySet()) {
        List<Kit_Bundle_Member__c> memberProds = bundleMap.get(
          parentLines.get(key).Product__c
        );

        for (Kit_Bundle_Member__c p : memberProds) {
         
          Decimal price = 0;
          newOPLs.add(
            new SalesOrderProductLine__c(
              AllowQuantityChange__c = p.AllowQuantityChange__c,
              KitBundle__c = false,
              KitBundleMemberRequired__c = p.Required__c,
              Product__c = p.ReferenceMemberProduct__c,
              SalesPrice__c = price,
              ListPrice__c = price,
              ContactShipping__c = parentLines.get(key).ContactShipping__c,
              SalesOrder__c = parentLines.get(key).SalesOrder__c,
              Quantity__c = parentLines.get(key).Quantity__c,
              DateRequired__c = parentLines.get(key).DateRequired__c,
              LineDiscountPercent__c = parentLines.get(key)
                .LineDiscountPercent__c,
              KitBundleLine__c = key
            )
          );
        }
      }

      try {
        insert newOPLs;
      } catch (DmlException err) {
        System.debug(
          'SALES ORDER PRODUCT LINES AFTER INSERT ERROR ON ADDING BUNDLE MEMBERS ::: '
        );
        System.debug(err.getMessage());
      }
      
    }
    generateInitialRecipients(
      (List<SalesOrderProductLine__c>) parentLines.values()
    );
  }

  public static void generateInitialRecipients(
    List<SalesOrderProductLine__c> prodLines
  ) {
    List<Order_Line_Recipient__c> newOLRs = new List<Order_Line_Recipient__c>();
    for (SalesOrderProductLine__c p : prodLines) {
      Order_Line_Recipient__c olr = new Order_Line_Recipient__c();
      olr.Order__c = p.SalesOrder__c;
      olr.OrderProductLine__c = p.Id;
      olr.Recipient__c = p.Order_Contact__c;
      olr.Primary__c = true;
      newOLRs.add(olr);
    }

    try {
      insert newOLRs;
    } catch (DmlException err) {
      System.debug('INITIAL RECIPIENT INSERT ERROR FROM SOPL TRIGGER ::: ');
      System.debug(err.getMessage());
    }
  }

  public static void updateSampleOrders(Set<Id> soIds) {
    List<SalesOrder__c> sampleOrders = [
      SELECT Id
      FROM SalesOrder__c
      WHERE Id IN :soIds
      AND Id NOT IN (
        SELECT SalesOrder__c
        FROM SalesOrderProductLine__c
        WHERE SalesOrder__c IN :soIds
        AND Sample_Product__c != true
      )
      AND Sample_ELM_Copy__c != true
    ];

    if (sampleOrders.size() > 0) {
      for (SalesOrder__c so : sampleOrders) {
        so.Sample_ELM_Copy__c = true;
      }

      try {
        update sampleOrders;
      } catch(DmlException err) {
        System.debug('UPDATE SAMPLE ORDERS ERROR ::: ');
        System.debug(err.getMessage());
      }
    }

  }

  public static void unsetSampleOrders(Set<Id> soIds) {
    List<SalesOrder__c> sampleOrders = [
      SELECT Id
      FROM SalesOrder__c
      WHERE Id IN :soIds
    ];
    
    if (sampleOrders.size() > 0) {
      for (SalesOrder__c so : sampleOrders) {
        so.Sample_ELM_Copy__c = false;
      }

      try {
        update sampleOrders;
      } catch(DmlException err) {
        System.debug('UPDATE SAMPLE ORDERS ERROR ::: ');
        System.debug(err.getMessage());
      }
    }
  }


  public static void unsetDeletedSampleOrders(Map<Id,Id> sampleMap) {
    List<SalesOrder__c> sampleOrders = [
      SELECT Id
      FROM SalesOrder__c
      WHERE Id IN :sampleMap.values()
      AND Id NOT IN (
        SELECT SalesOrder__c
        FROM SalesOrderProductLine__c
        WHERE SalesOrder__c IN :sampleMap.values()
        AND Sample_Product__c = true
        AND Id NOT IN :sampleMap.keySet()
      )
    ];

    if (sampleOrders.size() > 0) {
      for (SalesOrder__c so : sampleOrders) {
        so.Sample_ELM_Copy__c = false;
      }

      try {
        update sampleOrders;
      } catch(DmlException err) {
        System.debug('UPDATE SAMPLE ORDERS ERROR ::: ');
        System.debug(err.getMessage());
      }
    }
  }

  public static void deleteFulfillments(Set<Id> soplIds) {
    List<Fulfillment__c> fulfillments = [
      SELECT Id
      FROM Fulfillment__c
      WHERE Boom_Order_Product_Line__c IN :soplIds
    ];

    if (fulfillments.size() > 0) {
      delete fulfillments;
    }
  }
}