force-app/main/default/objects/Fulfillment__c/Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Fulfillment Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment__c/fields/OrderLine__c.field-meta.xml
<CustomField>
    <fullName>OrderLine__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Boom_Order_Product_Line__c, Boom_Order_Product_Line__r.Product__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <referenceTo>kugo2p__SalesOrderProductLine__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/OrderServiceLine__c.field-meta.xml
<CustomField>
    <fullName>OrderServiceLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Service Line</label>
    <referenceTo>kugo2p__SalesOrderServiceLine__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineRecipient__c/LineRecipient__c.object-meta.xml
<CustomObject>
    <label>Line Recipient</label>
    <nameField>
        <displayFormat>LR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LineRecipient__c/fields/Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fulfillment</label>
    <referenceTo>Fulfillment__c</referenceTo>
    <relationshipLabel>Line Recipients</relationshipLabel>
    <relationshipName>Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineRecipient__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>kugo2p__SalesOrder__c</referenceTo>
    <relationshipLabel>Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LineRecipient__c/fields/OrderLine__c.field-meta.xml
<CustomField>
    <fullName>OrderLine__c</fullName>
    <formula>IF( ISBLANK(OrderProductLine__c), 
HYPERLINK(&apos;/&apos;+OrderServiceLine__c, OrderServiceLine__r.kugo2p__Service__r.Name), 
HYPERLINK(&apos;/&apos;+OrderProductLine__c, OrderProductLine__r.kugo2p__Product__r.Name))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LineRecipient__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>kugo2p__SalesOrderProductLine__c.kugo2p__SalesOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>kugo2p__SalesOrderProductLine__c</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineRecipient__c/fields/OrderServiceLine__c.field-meta.xml
<CustomField>
    <fullName>OrderServiceLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Service Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>kugo2p__SalesOrderServiceLine__c.kugo2p__SalesOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>kugo2p__SalesOrderServiceLine__c</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineRecipient__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceLineViewExt.cls
public with sharing class InvoiceLineViewExt {

	private final kugo2p__KugamonInvoiceLine__c invLine;
	public list<LineRecipient__c> lineRecipients {get; set;}

	public InvoiceLineViewExt(ApexPages.StandardController stdCon) {
		invLine = (kugo2p__KugamonInvoiceLine__c) stdCon.getRecord();

		//if (invLine.kugo2p__SalesOrderProductLine__c != null || invLine.kugo2p__SalesOrderServiceLine__c != null) {
		lineRecipients = [select 	Id, Name, Order__r.Name, OrderLine__c, Primary__c, Recipient__r.Name, Fulfillment__r.Name
						from 	LineRecipient__c 
						where 	(OrderProductLine__c != null AND OrderProductLine__c = :invLine.kugo2p__SalesOrderProductLine__c) OR 
								(OrderServiceLine__c != null AND OrderServiceLine__c = :invLine.kugo2p__SalesOrderServiceLine__c)];
		//}
	}
}