force-app/main/default/objects/Fulfillment__c/Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Fulfillment Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment__c/fields/Boom_Order__c.field-meta.xml
<CustomField>
    <fullName>Boom_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Boom Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Boom_Order_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Boom_Order_Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Boom Order Product Line</label>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fulfillments (Contact)</relationshipLabel>
    <relationshipName>Fulfillments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <description>OrderProductLine__r.kugo2p__Product__r.kugo2p__ReferenceProduct__r.Subscription__c</description>
    <formula>Boom_Order_Product_Line__r.Product__r.Subscription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/Order_Line_Recipient__c.object-meta.xml
<CustomObject>
    <label>Order Line Recipient</label>
    <nameField>
        <displayFormat>OLR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/fields/AccountManager__c.field-meta.xml
<CustomField>
    <fullName>AccountManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Line_Recipients1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fulfillment</label>
    <referenceTo>Fulfillment__c</referenceTo>
    <relationshipLabel>Order Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SalesOrderProductLine__c.SalesOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Order_Line_Recipients1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Renewal_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Frequency__c</fullName>
    <label>Renewal Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Renewal_Product__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field shows the renewal product that should be used in the recurring subscription orders</description>
    <inlineHelpText>This field shows the renewal product that should be used in the recurring subscription orders</inlineHelpText>
    <label>Renewal Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this product a subscription product?</description>
    <inlineHelpText>Is this product a subscription product?</inlineHelpText>
    <label>Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/ContactBilling__c.field-meta.xml
<CustomField>
    <fullName>ContactBilling__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Subscription</description>
    <inlineHelpText>Related Subscription</inlineHelpText>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Boom Orders</relationshipLabel>
    <relationshipName>Boom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <formula>Product__r.Subscription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the assigned Account Manager to the Subscription</description>
    <inlineHelpText>This is the assigned Account Manager to the Subscription</inlineHelpText>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Original_Subscription_Boom_Order__c.field-meta.xml
<CustomField>
    <fullName>Original_Subscription_Boom_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field displays the original order that was released with the new subscription</description>
    <inlineHelpText>This field displays the original order that was released with the new subscription</inlineHelpText>
    <label>Original Subscription Boom Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payment_Method__c.Inactive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <valueField>Payment_Method__c.Contact__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Renewal_Date_Day_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date_Day_of_Month__c</fullName>
    <label>Renewal Date (Day of Month)</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Renewal_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Frequency__c</fullName>
    <label>Renewal Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Renewal_Price__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Price__c</fullName>
    <inlineHelpText>Renewal Price Per Qty</inlineHelpText>
    <label>Renewal Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Renewal_Product__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the product that should be renewed at time of next renewal</description>
    <inlineHelpText>This is the product that should be renewed at time of next renewal</inlineHelpText>
    <label>Renewal Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BoomFulfillmentHelper.cls
public without sharing class BoomFulfillmentHelper {
    public static void afterInsert(Map<Id, Fulfillment__c> newMap) {
        Map<Id, Fulfillment__c> subscriptionFulfillments = new Map<Id, Fulfillment__c>();
        Set<Id> fulfillmentProductLines = new Set<Id>();
        for(Fulfillment__c f : newMap.values()) {
            if(f.Subscription__c == true) {
                subscriptionFulfillments.put(f.Id, f);
                fulfillmentProductLines.add(f.Boom_Order_Product_Line__c);
            }
        }

        if(subscriptionFulfillments.size() > 0) {
            createSubscriptions(subscriptionFulfillments, fulfillmentProductLines);
        }
    }

    public static void createSubscriptions(Map<Id, Fulfillment__c> ffMap, Set<Id> prodLineIds) {
        Map<Id, SalesOrderProductLine__c> prodLineMap = new Map<Id, SalesOrderProductLine__c>([
            SELECT Id,Product__c,Product__r.Renewal_Product__c,Product__r.Renewal_Frequency__c,
            SalesOrder__r.ContactBilling__c,
            (SELECT Id, AccountManager__c,Recipient__c FROM Order_Line_Recipients__r WHERE Primary__c = true LIMIT 1)
            FROM SalesOrderProductLine__c
            WHERE Id IN :prodLineIds
        ]);



        Map<Id, Id> paymentMethodMap = generatePaymentMethodMap(ffMap);

        List<Subscription__c> newSubscriptions = new List<Subscription__c>();
        Integer dayOfMonth = (System.today()).day();
        
        for(Fulfillment__c ff : ffMap.values()) {
            SalesOrderProductLine__c prodLine = prodLineMap.get(ff.Boom_Order_Product_Line__c);

            if(prodLine != null && prodLine.Order_Line_Recipients__r.size() > 0) {
                Subscription__c sub = new Subscription__c();
                sub.Account_Manager__c = prodLine.Order_Line_Recipients__r[0].AccountManager__c;
                sub.Contact__c = prodLine.Order_Line_Recipients__r[0].Recipient__c;
                sub.Original_Subscription_Boom_Order__c = ff.Boom_Order__c;
                sub.Payment_Method__c = paymentMethodMap.get(ff.Boom_Order__c);
                sub.Renewal_Date_Day_of_Month__c = '' + dayOfMonth;
                sub.Renewal_Frequency__c = prodLine.Product__r.Renewal_Frequency__c;
                sub.Renewal_Price__c = ff.Gross_Price__c;
                sub.Renewal_Product__c = prodLine.Product__r.Renewal_Product__c;
                sub.Renewal_Quantity__c = ff.Quantity__c;
                sub.Start_Date__c = System.today();
                sub.Status__c = 'Active';
                sub.Subscription_Fulfillment__c = ff.Id;
                newSubscriptions.add(sub);
            }
        }

        if(newSubscriptions.size() > 0) {
            insert newSubscriptions;
        }        
    }
    
    public static Map<Id,Id> generatePaymentMethodMap(Map<Id, Fulfillment__c> ffMap) {
        Map<Id,Id> finalMap = new Map<Id,Id>();

        for(Payment__c p : [
            SELECT Sales_Order__c, Payment_Method__c
            FROM Payment__c
            WHERE Payment_Method__c != null
            AND Status__c = 'Completed'
            AND Sales_Order__c IN (
                SELECT Boom_Order__c FROM Fulfillment__c
                WHERE Id IN :ffMap.keySet()
            )
        ]) {
            finalMap.put(p.Sales_Order__c, p.Payment_Method__c);
        }

        return  finalMap;
    }

}