force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Markets</relationshipLabel>
    <relationshipName>Markets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MarketNewTriggerTest.cls
@isTest
public with sharing class MarketNewTriggerTest {
    @isTest
    private static void testInsert() {
        Product2 testProd = BoomTestHelpers.generateProduct();
        PricebookEntry testPbe = BoomTestHelpers.generatePriceBookEntry(testProd.Id);
        Market__c testMarket = BoomTestHelpers.generateMarket(testPbe.Pricebook2Id, false);
        Market__c queriedMkt = [SELECT Id,Price_Book__c FROM Market__c WHERE Id = :testMarket.Id LIMIT 1];
        System.assertEquals(true, queriedMkt.Price_Book__c == testPbe.Pricebook2Id, 'Pricebook Ids do not match on insert');
    }

    @isTest
    private static void testUpdate() {
        Product2 testProd = BoomTestHelpers.generateProduct();
        PricebookEntry testPbe = BoomTestHelpers.generatePriceBookEntry(testProd.Id);
        Market__c testMarket = BoomTestHelpers.generateMarket(testPbe.Pricebook2Id, false);
        testMarket.Price_Book__c = null;
        update testMarket;
        Market__c queriedMkt = [SELECT Id,Price_Book__c FROM Market__c WHERE Id = :testMarket.Id LIMIT 1];
        System.assertEquals(true, queriedMkt.Price_Book__c == testPbe.Pricebook2Id, 'Pricebook Ids do not match on update');
    }
}