force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Markets</relationshipLabel>
    <relationshipName>Markets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Price_Book_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_Book_Name__c</fullName>
    <description>Price Book Name Text Field</description>
    <formula>Price_Book__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Book Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MarketNewTriggerHelper.cls
public with sharing class MarketNewTriggerHelper {
  // Trigger to add pricebook to each market record when they're updated or inserted for simpler record access
  public static void afterInsert(Map<Id, Market__c> newMap) {
    Map<Id, String> pbNameMap = new Map<Id, String>();
    for (Id key : newMap.keySet()) {
      Market__c market = newMap.get(key);
      if (market.Price_Book__c == null) {
        pbNameMap.put(key, market.Name);
      }
    }
    findPriceBook(pbNameMap);
  }

  public static void afterUpdate(
    Map<Id, Market__c> oldMap,
    Map<Id, Market__c> newMap
  ) {
    Map<Id, String> pbNameMap = new Map<Id, String>();
    for (Id key : newMap.keySet()) {
      Market__c oldMarket = oldMap.get(key);
      Market__c newMarket = newMap.get(key);
      if (
        newMarket.Price_Book__c == null ||
        (oldMarket.Name != newMarket.Name &&
        newMarket.Price_Book_Name__c != newMarket.Name)
      ) {
        pbNameMap.put(key, newMarket.Name);
      }
    }
    findPriceBook(pbNameMap);
  }

  public static void findPriceBook(Map<Id, String> pbNameMap) {
    Map<String, Id> pbMap = new Map<String, Id>();
    for (PriceBook2 pb : [
      SELECT Id, Name
      FROM Pricebook2
      WHERE Name IN :pbNameMap.values()
    ]) {
        pbMap.put(pb.Name, pb.Id);
    }

    List<Market__c> updatedMarkets = new List<Market__c>();
    for(Id key : pbNameMap.keySet()){
        Id pbId = pbMap.get(pbNameMap.get(key));
        updatedMarkets.add(new Market__c(Id=key, Price_Book__c=pbId));
    }

    try{
        Database.update(updatedMarkets);
    } catch(DmlException err) {
        System.debug('Market pricebook update error :');
        System.debug(err.getMessage());
    }
  }
}