force-app/main/default/objects/Product2/fields/TaxableExcise__c.field-meta.xml
<CustomField>
    <fullName>TaxableExcise__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxable Excise</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/TaxableSale__c.field-meta.xml
<CustomField>
    <fullName>TaxableSale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxable Sale</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/TaxableUsage__c.field-meta.xml
<CustomField>
    <fullName>TaxableUsage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxable Usage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/TaxableVAT__c.field-meta.xml
<CustomField>
    <fullName>TaxableVAT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Taxable VAT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Tax_Amount_Hidden__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Hidden__c</fullName>
    <description>Hidden field to calculate at rollup-- controlled by trigger</description>
    <label>Tax Amount Hidden</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/TaxableExcise__c.field-meta.xml
<CustomField>
    <fullName>TaxableExcise__c</fullName>
    <formula>Product__r.TaxableExcise__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taxable Excise</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/TaxableSale__c.field-meta.xml
<CustomField>
    <fullName>TaxableSale__c</fullName>
    <formula>Product__r.TaxableSale__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taxable Sale</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/TaxableUsage__c.field-meta.xml
<CustomField>
    <fullName>TaxableUsage__c</fullName>
    <formula>Product__r.TaxableUsage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taxable Usage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/TaxableVAT__c.field-meta.xml
<CustomField>
    <fullName>TaxableVAT__c</fullName>
    <formula>Product__r.TaxableVAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taxable VAT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/TaxAmount__c.field-meta.xml
<CustomField>
    <fullName>TaxAmount__c</fullName>
    <formula>ROUND(TotalAmount__c *  (TaxExciseRate__c + TaxSalesRate__c + TaxUsageRate__c + TaxVATRate__c), 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProductTaxesHelper.cls
public without sharing class ProductTaxesHelper {
    public static void afterUpdate(Map<Id, Product2> oldMap, Map<Id, Product2> newMap) {
        List<Id> updatedProductTaxes = new List<Id>();
        for(Product2 np : newMap.values()) {
            Product2 op = oldMap.get(np.Id);

            if(np.TaxableSale__c != op.TaxableSale__c || np.TaxableExcise__c != op.TaxableExcise__c || np.TaxableUsage__c != op.TaxableUsage__c || np.TaxableVAT__c != op.TaxableVAT__c) {
                updatedProductTaxes.add(np.Id);
            }
        }

        if(updatedProductTaxes.size() > 0) { 
            updateProductLineTaxes(updatedProductTaxes);
        }
    }

    public static void updateProductLineTaxes(List<Id> prodIds) {
        List<SalesOrderProductLine__c> sopls = [SELECT Id, TaxAmount__c,Tax_Amount_Hidden__c FROM SalesOrderProductLine__c WHERE Product__c IN :prodIds];
        List<SalesOrderProductLine__c> soplsToUpdate = new List<SalesOrderProductLine__c>();

        for(SalesOrderProductLine__c sopl : sopls) {
            if(sopl.TaxAmount__c != sopl.Tax_Amount_Hidden__c) {
                sopl.Tax_Amount_Hidden__c = sopl.TaxAmount__c;
                soplsToUpdate.add(sopl);
            }
        }

        if(soplsToUpdate.size() > 0) {
            update soplsToUpdate;
        }
    }
    
}