force-app/main/default/objects/Account/fields/Client_Type__c.field-meta.xml
<CustomField>
    <fullName>Client_Type__c</fullName>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A++</fullName>
            </value>
            <value>
                <fullName>A+</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>A-</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Client_Type__c.field-meta.xml
<CustomField>
    <fullName>Client_Type__c</fullName>
    <label>Client Type</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Professionals</relationshipLabel>
    <relationshipName>Professionals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Market_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Market_Close_Date__c</fullName>
    <description>Pub date in numeric form (first of the month for monthly pub, date of publication for daily pub)</description>
    <inlineHelpText>Pub date in numeric form (first of the month for monthly pub, date of publication for daily pub)</inlineHelpText>
    <label>Market Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Sales_Close__c.field-meta.xml
<CustomField>
    <fullName>Sales_Close__c</fullName>
    <label>Sales Close</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_Type__c.field-meta.xml
<CustomField>
    <fullName>Client_Type__c</fullName>
    <formula>(Contact__r.Client_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Market_Close_Date__c</fullName>
    <formula>Market_Project__r.Market_Close_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Next_call_date__c.field-meta.xml
<CustomField>
    <fullName>Next_call_date__c</fullName>
    <label>Next call date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Next_Call_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Next_Call_Date_Time__c</fullName>
    <label>Next Call Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pardot_Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Pardot_Campaign_Type__c</fullName>
    <label>Pardot Campaign Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>WSJ Showcase I</fullName>
            </value>
            <value>
                <fullName>WSJ Showcase II</fullName>
            </value>
            <value>
                <fullName>WiW WSJ Showcase I</fullName>
            </value>
            <value>
                <fullName>WiW WSJ Showcase II</fullName>
            </value>
            <value>
                <fullName>WiW MAG Showcase I</fullName>
            </value>
            <value>
                <fullName>Forbes Investment Guide I</fullName>
            </value>
            <value>
                <fullName>Forbes Investment Guide II</fullName>
            </value>
            <value>
                <fullName>BFF Showcase</fullName>
            </value>
            <value>
                <fullName>Digital Showcase I</fullName>
            </value>
            <value>
                <fullName>Digital Showcase II</fullName>
            </value>
            <value>
                <fullName>Alumni Showcase I</fullName>
            </value>
            <value>
                <fullName>Alumni Showcase II</fullName>
            </value>
            <value>
                <fullName>Relocation Guide I</fullName>
            </value>
            <value>
                <fullName>Relocation Guide II</fullName>
            </value>
            <value>
                <fullName>Airline Mag Showcase I</fullName>
            </value>
            <value>
                <fullName>Other Alt Media I</fullName>
            </value>
            <value>
                <fullName>Other Alt Media II</fullName>
            </value>
            <value>
                <fullName>Post-market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestOpportunityEmailAfterOneHr.cls
@isTest
private class TestOpportunityEmailAfterOneHr
{

    static testmethod void schedulerTest() 
    {
        String CRON_EXP = '0 0 0 15 3 ? *';
        
        Account acc = new Account();
       acc.Name ='Test';
       insert acc;
       
       Contact c = new Contact();
       c.AccountId = acc.Id;
       c.LastName = 'Test';
       c.Client_Type__c = 'BD';
       c.Email = 'test123@gmail.com';
       insert c;
        
       Market__c market = new Market__c();
       market.Name = 'Test';
       market.Sales_Close__c = Date.today().AddDays(1);
       market.Market_Close_Date__c = system.today().addDays(1);
       insert market; 
       string RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Core - New Business').getRecordTypeId();

        
       Opportunity opp = new Opportunity();
       opp.RecordTypeId = RecordTypeId;
       opp.AccountId = acc.Id;
       opp.Contact__c= c.Id;
       opp.Name = 'Test1';
       opp.StageName = 'Gold';
       opp.CloseDate = Date.Today();
       opp.Market_Project__c = market.Id;
       opp.Next_call_date__c = Date.Today();
       opp.Next_Call_Date_Time__c= Date.Today();
    //    opp.Pardot_Campaign_Type__c = 'Core';
       
     //  opp.RecordTypeId = 
       insert opp; 
        
        Test.startTest();

        String jobId = System.schedule('ScheduleApexClassTest',  CRON_EXP, new OpportunityEmailAfterOneHr(new List<Id>{opp.Id}));
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
            System.assertEquals(CRON_EXP, ct.CronExpression);
            System.assertEquals(0, ct.TimesTriggered);

        Test.stopTest();        
    }
}