force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 Year Winner</fullName>
            </value>
            <value>
                <fullName>2 Year Winner</fullName>
            </value>
            <value>
                <fullName>3 Year Winner</fullName>
            </value>
            <value>
                <fullName>4 Year Winner</fullName>
            </value>
            <value>
                <fullName>5 Year Winner</fullName>
            </value>
            <value>
                <fullName>6 Year Winner</fullName>
            </value>
            <value>
                <fullName>7 Year Winner</fullName>
            </value>
            <value>
                <fullName>8 Year Winner</fullName>
            </value>
            <value>
                <fullName>9 Year Winner</fullName>
            </value>
            <value>
                <fullName>10 Year Winner</fullName>
            </value>
            <value>
                <fullName>11 Year Winner</fullName>
            </value>
            <value>
                <fullName>12 Year Winner</fullName>
            </value>
            <value>
                <fullName>13 Year Winner</fullName>
            </value>
            <value>
                <fullName>14 Year Winner</fullName>
            </value>
            <value>
                <fullName>15 Year Winner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Account.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Fulfillment Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <description>OrderProductLine__r.kugo2p__Product__r.kugo2p__ReferenceProduct__r.Subscription__c</description>
    <formula>Boom_Order_Product_Line__r.Product__r.Subscription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this product a subscription product?</description>
    <inlineHelpText>Is this product a subscription product?</inlineHelpText>
    <label>Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Account Name, which is required. 

To change the required Account name, please update the Additional Account Info field on this Order. If the field is not visible, please contact your Administrator. For Released or Paid Orders, please also update the Invoice and Payment records.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactBilling__c.field-meta.xml
<CustomField>
    <fullName>ContactBilling__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>Payment Update Needed</fullName>
            </value>
            <value>
                <fullName>Subscription Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Subscription</description>
    <inlineHelpText>Related Subscription</inlineHelpText>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Boom Orders</relationshipLabel>
    <relationshipName>Boom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>SalesOrder__r.ContactBilling__r.Market_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <formula>Product__r.Subscription__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payment_Method__c.Inactive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <valueField>Payment_Method__c.Contact__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is related to the primary subscription fulfillment used by Production</description>
    <inlineHelpText>This field is related to the primary subscription fulfillment used by Production</inlineHelpText>
    <label>Subscription Fulfillment</label>
    <referenceTo>Fulfillment__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SubscriptionTests.cls
@isTest
public with sharing class SubscriptionTests {
    @TestSetup
    static void makeData(){
        Product2 renewalProduct = BoomTestHelpers.generateProduct();
        Product2 subscriptionProd = BoomTestHelpers.createSubscriptionProduct(renewalProduct);
        Product2 addonProd = BoomTestHelpers.createAddonProduct();
        PricebookEntry pbE1 = BoomTestHelpers.generatePriceBookEntry(renewalProduct.Id);
        PricebookEntry pbE2 = BoomTestHelpers.generatePriceBookEntry(subscriptionProd.Id);
        PricebookEntry pbE3 = BoomTestHelpers.generatePriceBookEntry(addonProd.Id);
        Market__c mkt = BoomTestHelpers.generateMarket(pbe1.Pricebook2Id, true);
        Account a = BoomTestHelpers.generateAccount();
        Contact c = BoomTestHelpers.generateContact(a.Id);
        Opportunity o = BoomTestHelpers.generateOpportunity(a.Id, mkt.Id, c.Id);
        SalesOrder__c so = BoomTestHelpers.generateTestBoomOrder(o.Id);
        SalesOrderProductLine__c sopl = BoomTestHelpers.generateBoomProductLine(so.Id, pbE2);
        SalesOrderProductLine__c sopl2 = BoomTestHelpers.generateBoomProductLine(so.Id, pbE3);

        so.Status_Picklist__c = 'Approved';

        update so;

        Payment_Method__c pm = BoomTestHelpers.generateTestPmtMethod(c.Id, true);
    }
    @isTest
    public static void testSubscriptionMethod() {
      Test.setMock(HttpCalloutMock.class, new ZealynxHttpMockGenerator());
        SalesOrder__c so = [SELECT Id, Account__c, ContactBilling__c FROM SalesOrder__c LIMIT 1];
        Payment_Method__c pm = [SELECT Id FROM Payment_Method__c LIMIT 1];
        Test.startTest();
        Payment__c testPmt = BoomTestHelpers.generateTestPayment(so.Id, so.Account__c, so.ContactBilling__c, pm.Id, 100, 'Completed');
        Test.stopTest();

        List<Subscription__c> subs = [SELECT Id,Subscription_Fulfillment__c FROM Subscription__c];
        System.assertEquals(true, subs.size() > 0, 'Subscription__c records were not created');

        subs[0].Status__c = 'Cancelled';
        update subs[0];

        Fulfillment__c f = [SELECT Id, Status__c FROM Fulfillment__c WHERE Id = :subs[0].Subscription_Fulfillment__c LIMIT 1];

        System.assertEquals('Subscription Cancelled', f.Status__c, 'Fulfillment status was not set to Subscription Cancelled');
    }

    @isTest
    public static void testSubscriptionSchedule() {
        Test.setMock(HttpCalloutMock.class, new ZealynxHttpMockGenerator());

        String cronExpr = '0 0 0 15 3 ? 2060';
        List<AsyncApexJob> jobsBefore = [
          SELECT Id, ApexClassID, ApexClass.Name, Status, JobType
          FROM AsyncApexJob
        ];
        System.assertEquals(0, jobsBefore.size(), 'not expecting any asyncjobs');
        Test.startTest();
        String jobId = System.schedule(
          'myJobTestJobName',
          cronExpr,
          new SubscriptionBatchSchedule()
        );
        Test.stopTest();
    
        List<AsyncApexJob> jobsScheduled = [
          SELECT Id, ApexClassID, ApexClass.Name, Status, JobType
          FROM AsyncApexJob
          WHERE JobType = 'ScheduledApex'
        ];
        System.assertEquals(1, jobsScheduled.size(), 'expecting one scheduled job');
        System.assertEquals(
          'SubscriptionBatchSchedule',
          jobsScheduled[0].ApexClass.Name,
          'expecting specific scheduled job'
        );
    
        // check apex batch is in the job list
        List<AsyncApexJob> jobsApexBatch = [
          SELECT Id, ApexClassID, ApexClass.Name, Status, JobType
          FROM AsyncApexJob
          WHERE JobType = 'BatchApex'
        ];
        System.assertEquals(
          2,
          jobsApexBatch.size(),
          'expecting two apex batch jobs'
        );

    }

    @isTest
    public static void testSubscriptionBatch() {
        Test.setMock(HttpCalloutMock.class, new ZealynxHttpMockGenerator());
        
        SalesOrder__c so = [SELECT Id, Account__c, ContactBilling__c FROM SalesOrder__c LIMIT 1];
        Payment_Method__c pm = [SELECT Id FROM Payment_Method__c LIMIT 1];

        Test.startTest();
        Payment__c testPmt = BoomTestHelpers.generateTestPayment(so.Id, so.Account__c, so.ContactBilling__c, pm.Id, 100, 'Completed');
        Test.stopTest();
        SalesOrder__c renewalOrder = [SELECT Id FROM SalesOrder__c WHERE Status_Picklist__c = 'Pending Renewal' LIMIT 1];
        renewalOrder.OrderDate__c = System.today();
        update renewalOrder;
        Database.executeBatch(new SubscriptionOrdersBatch(), 1);
    }

    @isTest
    public static void testSubscriptionBatchDeclined() {
      Test.setMock(HttpCalloutMock.class, new ZealynxHttpMockGeneratorDeclined());
      SalesOrder__c so = [SELECT Id, Account__c, ContactBilling__c FROM SalesOrder__c LIMIT 1];
      Payment_Method__c pm = [SELECT Id FROM Payment_Method__c LIMIT 1];

      Test.startTest();
      Payment__c testPmt = BoomTestHelpers.generateTestPayment(so.Id, so.Account__c, so.ContactBilling__c, pm.Id, 100, 'Completed');
      Test.stopTest();
      SalesOrder__c renewalOrder = [SELECT Id FROM SalesOrder__c WHERE Status_Picklist__c = 'Pending Renewal' LIMIT 1];
      renewalOrder.OrderDate__c = System.today();
      update renewalOrder;
      Database.executeBatch(new SubscriptionOrdersBatch(), 1);

    }

    @isTest
    public static void testSubscriptionStatusBatch() {
        
        SalesOrder__c so = [SELECT Id, Account__c, ContactBilling__c FROM SalesOrder__c LIMIT 1];
        Payment_Method__c pm = [SELECT Id FROM Payment_Method__c LIMIT 1];

        Test.startTest();
        Payment__c testPmt = BoomTestHelpers.generateTestPayment(so.Id, so.Account__c, so.ContactBilling__c, pm.Id, 100, 'Completed');
        Test.stopTest();
        Subscription__c generatedSub = [SELECT Id FROM Subscription__c LIMIT 1];
        generatedSub.End_Date__c = System.today();
        update generatedSub;
        Database.executeBatch(new SubscriptionStatusBatch(), 1);
    }

    @isTest
    public static void testChainedQueue() { 
      List<SalesOrder__c> so = [SELECT Id, Account__c, ContactBilling__c FROM SalesOrder__c];
      List<Payment_Method__c> pm = [SELECT Id FROM Payment_Method__c];
      Test.startTest();
      System.enqueueJob(new BoomSubscriptionPaymentsQueuable(so, pm));
      Test.stopTest();
      
    }
}