force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <inlineHelpText>Details about the transaction.</inlineHelpText>
    <label>Memo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <label>Memo on Invoice</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PaymentConversionHelperTest.cls
@isTest(SeeAllData=True)
public without sharing class PaymentConversionHelperTest {
    @isTest
    public static void PaymentConversionHelperTest() {
        kugo2p__SalesOrder__c so = [SELECT Id FROM kugo2p__SalesOrder__c LIMIT 1];

        Product2 testProd = BoomTestHelpers.generateProduct();
        PricebookEntry testPbe = BoomTestHelpers.generatePricebookEntry(
          testProd.Id
        );
        Market__c testMarket = BoomTestHelpers.generateMarket(
          testPbe.Pricebook2Id,
          true
        );
        Account testAcct = BoomTestHelpers.generateAccount();
        Contact testCont = BoomTestHelpers.generateContact(testAcct.Id);
        Opportunity testOpp = BoomTestHelpers.generateOpportunity(
          testAcct.Id,
          testMarket.Id,
          testCont.Id
        );

        List<SalesOrder__c> soList = [SELECT Id FROM SalesOrder__c WHERE Legacy_Id__c = :so.Id  LIMIT 1];
            
        SalesOrder__c testSo;
        
        if(soList.size() > 0) {
            testSo = soList[0];
        } else {
            testSo = BoomTestHelpers.generateTestBoomOrder(
                testOpp.Id
              );

            testSo.Legacy_Id__c = so.Id;

            update testSo;
        }

        
    
        kugo2p__paymentX__c newPayment = new kugo2p__paymentX__c();
        newPayment.kugo2p__SalesOrder__c = so.Id;
        insert newPayment;

        List<Payment__c> testPayment = [
            SELECT Id, Legacy_Id__c
            FROM Payment__c
            WHERE Legacy_Id__c = :newPayment.Id
        ];
        
        System.assertEquals(true, testPayment.size() > 0, 'Payment not created');


        newPayment.kugo2p__Memo__c = 'TEST MEMO';

        update newPayment;

        List<Payment__c> testPayment2 = [
            SELECT Id, Legacy_Id__c
            FROM Payment__c
            WHERE Legacy_Id__c = :newPayment.Id
            AND Memo__c LIKE '%TEST MEMO%'
        ];

        System.assertEquals(true, testPayment2.size() > 0, 'Payment not updated');
        
    }
}