force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kit_Bundle_Member__c/Kit_Bundle_Member__c.object-meta.xml
<CustomObject>
    <label>Kit/Bundle Member</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Kit/Bundle Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kit/Bundle Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/Order_Line_Recipient__c.object-meta.xml
<CustomObject>
    <label>Order Line Recipient</label>
    <nameField>
        <displayFormat>OLR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/fields/AccountManager__c.field-meta.xml
<CustomField>
    <fullName>AccountManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Line_Recipients1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Order Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SalesOrderProductLine__c.SalesOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Kit_Bundle_Member__c.field-meta.xml
<CustomField>
    <fullName>Kit_Bundle_Member__c</fullName>
    <formula>IF( ISBLANK( KitBundleLine__c ) , false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Kit/Bundle Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>SalesOrder__r.ContactBilling__r.Market_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Recipient_Count__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Recipient Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderLineRecipientHelperTest.cls
@isTest
public with sharing class OrderLineRecipientHelperTest {
    @isTest
    private static void testBeforeInsert() {
        Account testAcc = BoomTestHelpers.generateAccount();
        Contact testCtc = BoomTestHelpers.generateContact(testAcc.Id);
        Product2 testPrd = BoomTestHelpers.generateProduct();
        PricebookEntry testPbe = BoomTestHelpers.generatePricebookEntry(testPrd.Id);
        Market__c testMkt = BoomTestHelpers.generateMarket(testPbe.Pricebook2Id, true);
        Opportunity testOpp = BoomTestHelpers.generateOpportunity(testAcc.Id, testMkt.Id, testCtc.Id);
        SalesOrder__c testSo = BoomTestHelpers.generateTestBoomOrder(testOpp.Id);
        Test.startTest();
        SalesOrderProductLine__c testSoPrdLn = BoomTestHelpers.generateBoomProductLine(testSo.Id, testPbe);
        Order_Line_Recipient__c testRecipient = BoomTestHelpers.generateTestLineRecipient(testSo.Id, testSoPrdLn.Id, testCtc.Id, true);
        Order_Line_Recipient__c queriedRecipient = [SELECT Id, Market__c, AccountManager__c FROM Order_Line_Recipient__c WHERE Id = :testRecipient.Id LIMIT 1];
        Id accOwner = [SELECT OwnerId FROM Account WHERE Id = :testAcc.Id LIMIT 1].OwnerId;
        System.assertEquals(accOwner, queriedRecipient.AccountManager__c, 'Account owner should be set to the account manager');
        System.assertEquals(queriedRecipient.Market__c, testMkt.Id, 'Market should be set to the market of the sales order');
        Test.stopTest();
    }

    @isTest
    private static void testAfterInsertAndDelete() {
        Account testAcc = BoomTestHelpers.generateAccount();
        Account testAcc2 = BoomTestHelpers.generateAccount();

        Contact testCtc = BoomTestHelpers.generateContact(testAcc.Id);
        Contact testCtc2 = BoomTestHelpers.generateContact(testAcc.Id);

        Product2 testPrd = BoomTestHelpers.generateProduct();
        Product2 testPrd2 = BoomTestHelpers.generateProduct();
        PricebookEntry testPbe = BoomTestHelpers.generatePricebookEntry(testPrd.Id);
        PricebookEntry testPbe2 = BoomTestHelpers.generatePricebookEntry(testPrd2.Id);
        Market__c testMkt = BoomTestHelpers.generateMarket(testPbe.Pricebook2Id, true);
        Opportunity testOpp = BoomTestHelpers.generateOpportunity(testAcc.Id, testMkt.Id, testCtc.Id);
        SalesOrder__c testSo = BoomTestHelpers.generateTestBoomOrder(testOpp.Id);
        Kit_Bundle_Member__c testKbm = BoomTestHelpers.generateTestKitBundle(testPrd.Id, testPrd2.Id);
        SalesOrderProductLine__c testSoPrdLn = BoomTestHelpers.generateBoomProductLine(testSo.Id, testPbe);
        Order_Line_Recipient__c testRecipient = BoomTestHelpers.generateTestLineRecipient(testSo.Id, testSoPrdLn.Id, testCtc.Id, true);
        Order_Line_Recipient__c testRecipient2 = BoomTestHelpers.generateTestLineRecipient(testSo.Id, testSoPrdLn.Id, testCtc2.Id, false);

        List<Order_Line_Recipient__c> queriedRecipients = [SELECT Id FROM Order_Line_Recipient__c WHERE Order__c = :testSo.Id];
        List<Order_Line_Recipient__c> queriedRecipientsForSopl = [SELECT Id FROM Order_Line_Recipient__c WHERE OrderProductLine__c = :testSoPrdLn.Id];
        SalesOrderProductLine__c queriedSoPrdLn = [SELECT Id, Recipient_Count__c FROM SalesOrderProductLine__c WHERE Id = :testSoPrdLn.Id];
        System.assertEquals(queriedRecipients.size() > 0, true, 'There should be more than one recipient for the sales order');
        System.assertEquals(queriedSoPrdLn.Recipient_Count__c, queriedRecipientsForSopl.size(), 'The recipient count for the sales order product line should be equal to the number of recipients');
        Test.startTest();
        delete queriedRecipientsForSopl;
        Test.stopTest();
        SalesOrderProductLine__c queriedSoPrdLn2 = [SELECT Id, Recipient_Count__c FROM SalesOrderProductLine__c WHERE Id = :testSoPrdLn.Id];
        System.assertEquals(queriedSoPrdLn2.Recipient_Count__c, 0, 'The recipient count for the sales order product line should be zero after the recipient is deleted');
    }

    @isTest
    private static void testAfterUpdate() {
        Account testAcc = BoomTestHelpers.generateAccount();
        Contact testCtc = BoomTestHelpers.generateContact(testAcc.Id);
        Product2 testPrd = BoomTestHelpers.generateProduct();
        PricebookEntry testPbe = BoomTestHelpers.generatePricebookEntry(testPrd.Id);
        Market__c testMkt = BoomTestHelpers.generateMarket(testPbe.Pricebook2Id, true);
        Opportunity testOpp = BoomTestHelpers.generateOpportunity(testAcc.Id, testMkt.Id, testCtc.Id);
        SalesOrder__c testSo = BoomTestHelpers.generateTestBoomOrder(testOpp.Id);
        Test.startTest();
        SalesOrderProductLine__c testSoPrdLn = BoomTestHelpers.generateBoomProductLine(testSo.Id, testPbe);
        Order_Line_Recipient__c testRecipient = BoomTestHelpers.generateTestLineRecipient(testSo.Id, testSoPrdLn.Id, testCtc.Id, true);
        SalesOrderProductLine__c testSoPrdLn2 = BoomTestHelpers.generateBoomProductLine(testSo.Id, testPbe);
        testRecipient.OrderProductLine__c = testSoPrdLn2.Id;
        update testRecipient;
        List<Order_Line_Recipient__c> queriedRecipients = [SELECT Id FROM Order_Line_Recipient__c WHERE OrderProductLine__c = :testSoPrdLn.Id AND Id = :testRecipient.Id];
        System.assertEquals(queriedRecipients.size() == 0, true, 'The recipient should not be in the list of recipients for the old sales order product line');
        Test.stopTest();
    }
}