force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineRecipient__c/LineRecipient__c.object-meta.xml
<CustomObject>
    <label>Line Recipient</label>
    <nameField>
        <displayFormat>LR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LineRecipient__c/fields/AccountManager__c.field-meta.xml
<CustomField>
    <fullName>AccountManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Line_Recipients1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineRecipient__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Line Recipients</relationshipLabel>
    <relationshipName>Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineRecipient__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>kugo2p__SalesOrder__c</referenceTo>
    <relationshipLabel>Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LineRecipient__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>kugo2p__SalesOrderProductLine__c.kugo2p__SalesOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>kugo2p__SalesOrderProductLine__c</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineRecipient__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/Order_Line_Recipient__c.object-meta.xml
<CustomObject>
    <label>Order Line Recipient</label>
    <nameField>
        <displayFormat>OLR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/fields/AccountManager__c.field-meta.xml
<CustomField>
    <fullName>AccountManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Line_Recipients1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Is_Kit_Bundle__c.field-meta.xml
<CustomField>
    <fullName>Is_Kit_Bundle__c</fullName>
    <formula>OrderProductLine__r.KitBundle__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Kit Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Order Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SalesOrderProductLine__c.SalesOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Order_Line_Recipients1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Account Name, which is required. 

To change the required Account name, please update the Additional Account Info field on this Order. If the field is not visible, please contact your Administrator. For Released or Paid Orders, please also update the Invoice and Payment records.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.Contact__r.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Boom Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/KitBundleLine__c.field-meta.xml
<CustomField>
    <fullName>KitBundleLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit/Bundle Line</label>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>SalesOrder__r.ContactBilling__r.Market_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Recipient_Count__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Recipient Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderLineRecipientsHelper.cls
public without sharing class OrderLineRecipientsHelper {
  public static void beforeInsert(List<Order_Line_Recipient__c> newRecipients) {
    Set<Id> salesOrderIds = new Set<Id>();
    for (Order_Line_Recipient__c r : newRecipients) {
      if (String.isEmpty(r.Legacy_Id__c)) {
        salesOrderIds.add(r.Order__c);
      }
    }

    Map<Id, SalesOrder__c> parentSalesOrders = generateSalesOrders(
      salesOrderIds
    );

    for (Order_Line_Recipient__c r : newRecipients) {
      if (String.isEmpty(r.Legacy_Id__c)) {
        if (r.Market__c == null) {
          r.Market__c = parentSalesOrders.get(r.Order__c).Market__c;
        }

        if (r.AccountManager__c == null) {
          r.AccountManager__c = parentSalesOrders.get(r.Order__c)
            .Opportunity__r.OwnerId;
        }
      }
    }
  }

  public static void afterInsert(List<Order_Line_Recipient__c> newRecipients) {
    Set<Id> orderLineIds = new Set<Id>();
    Map<Id, List<Order_Line_Recipient__c>> addToChildren = new Map<Id, List<Order_Line_Recipient__c>>();
    List<Id> referenceIds = new List<Id>();
    for (Order_Line_Recipient__c r : newRecipients) {
      if(String.isEmpty(r.Legacy_Id__c)) {
        orderLineIds.add(r.OrderProductLine__c);
        if (r.Is_Kit_Bundle__c == true) {
          referenceIds.add(r.Id);
          if (addToChildren.containsKey(r.OrderProductLine__c)) {
            List<Order_Line_Recipient__c> recips = addToChildren.get(
              r.OrderProductLine__c
            );
            recips.add(r);
            addToChildren.put(r.OrderProductLine__c, recips);
          } else {
            addToChildren.put(
              r.OrderProductLine__c,
              new List<Order_Line_Recipient__c>{ r }
            );
          }
        }
      }
      
    }

    if(orderLineIds.size() > 0){ 
      updateParentOrderLine(orderLineIds);
    }


    if (addToChildren.size() > 0) {
      updateChildrenRecipients(addToChildren, referenceIds, false);
    }
  }

  public static void afterUpdate(
    Map<Id, Order_Line_Recipient__c> oldRecipients,
    Map<Id, Order_Line_Recipient__c> newRecipients
  ) {
    Set<Id> orderLineIds = new Set<Id>();

    for (Id key : newRecipients.keySet()) {
      if (
        oldRecipients.get(key).OrderProductLine__c !=
        newRecipients.get(key).OrderProductLine__c &&
        String.isEmpty(newRecipients.get(key).Legacy_Id__c)
      ) {
        orderLineIds.add(oldRecipients.get(key).OrderProductLine__c);
        orderLineIds.add(newRecipients.get(key).OrderProductLine__c);
      }
    }

    if(orderLineIds.size() > 0){ 
      updateParentOrderLine(orderLineIds);
    }
  }

  public static void afterDelete(List<Order_Line_Recipient__c> oldList) {
    Set<Id> orderLineIds = new Set<Id>();
    Map<Id, List<Order_Line_Recipient__c>> deleteChildren = new Map<Id, List<Order_Line_Recipient__c>>();
    List<Id> referenceIds = new List<Id>();

    for (Order_Line_Recipient__c ol : oldList) {

      if(String.isEmpty(ol.Legacy_Id__c)) {
        orderLineIds.add(ol.OrderProductLine__c);
        if (ol.Is_Kit_Bundle__c == true) {
          referenceIds.add(ol.Recipient__c);
          if (deleteChildren.containsKey(ol.OrderProductLine__c)) {
            List<Order_Line_Recipient__c> recips = deleteChildren.get(
              ol.OrderProductLine__c
            );
            recips.add(ol);
            deleteChildren.put(ol.OrderProductLine__c, recips);
          } else {
            deleteChildren.put(
              ol.OrderProductLine__c,
              new List<Order_Line_Recipient__c>{ ol }
            );
          }
        }
      }
      
    }

    if(orderLineIds.size() > 0) {
      updateParentOrderLine(orderLineIds);
    }

    if (deleteChildren.size() > 0) {
      updateChildrenRecipients(deleteChildren, referenceIds, true);
    }
  }

  public static Map<Id, SalesOrder__c> generateSalesOrders(
    Set<Id> salesOrderIds
  ) {
    Map<Id, SalesOrder__c> salesOrders = new Map<Id, SalesOrder__c>(
      [
        SELECT Id, Account__r.OwnerId, Market__c, Opportunity__r.OwnerId
        FROM SalesOrder__c
        WHERE Id IN :salesOrderIds
      ]
    );

    return salesOrders;
  }

  public static Map<Id, Contact> generateOppToContactMap() {
    Map<Id, Contact> returnedMap = new Map<Id, Contact>();

    return returnedMap;
  }

  public static void updateParentOrderLine(Set<Id> orderLineIds) {
   
  List<SalesOrderProductLine__c> SOPLs = [
      SELECT Id, Recipient_Count__c, (SELECT Id FROM Order_Line_Recipients__r WHERE OrderProductLine__c != null)
      FROM SalesOrderProductLine__c
      WHERE Id IN :orderLineIds
      AND Legacy_Id__c = null
    ];

    for (SalesOrderProductLine__c sopl : SOPLs) {
      if(sopl.Order_Line_Recipients__r != null && sopl.Order_Line_Recipients__r.size() > 0) {
        sopl.Recipient_Count__c = sopl.Order_Line_Recipients__r.size();
      } else {
        sopl.Recipient_Count__c = 0;
      }
    }

    try {
      Database.update(SOPLs, false);
    } catch (DmlException err) {
      System.debug('RECIPIENT COUNT UPDATE ERROR :::' + err.getMessage());
    }
  }

  public static void updateChildrenRecipients(
    Map<Id, List<Order_Line_Recipient__c>> parentMap,
    List<Id> referenceIds,
    Boolean isDelete
  ) {
    if (isDelete) {
      List<Order_Line_Recipient__c> olrForDeletion = [
        SELECT Id, OrderProductLine__r.KitBundleLine__c
        FROM Order_Line_Recipient__c
        WHERE
          OrderProductLine__r.KitBundleLine__c IN :parentMap.keySet()
          AND Recipient__c IN :referenceIds
      ];

      if (olrForDeletion.size() > 0) {
        delete olrForDeletion;
      }

      return;
    }

    List<SalesOrderProductLine__c> childrenRecords = [
      SELECT Id, KitBundleLine__c
      FROM SalesOrderProductLine__c
      WHERE KitBundleLine__c IN :parentMap.keySet()
    ];

    List<Order_Line_Recipient__c> newRecipients = new List<Order_Line_Recipient__c>();

    for (SalesOrderProductLine__c c : childrenRecords) {
      List<Order_Line_Recipient__c> olr = parentMap.get(c.KitBundleLine__c);

      for (Order_Line_Recipient__c o : olr) {
        Order_Line_Recipient__c newRecipient = o.clone(
          false,
          true,
          false,
          false
        );
        newRecipient.OrderProductLine__c = c.Id;
        newRecipients.add(newRecipient);
      }
    }

    insert newRecipients;
  }
}