force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AdditionalChargeCredit__c/AdditionalChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Related object that functions as an auxiliary Product catalog. Good for charge lines, such Shipping &amp; Handling Fee</description>
    <label>Additional Charge and Credit</label>
    <nameField>
        <label>Additional Charge/Credit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Charges and Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/Order_Line_Recipient__c.object-meta.xml
<CustomObject>
    <label>Order Line Recipient</label>
    <nameField>
        <displayFormat>OLR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Order Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/SalesOrderAdditionalChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Charges and Credits.</description>
    <label>Order Additional Charge and Credit</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Additional Charge/Credit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Additional Charges and Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/Additional_Charge_Credit__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charge_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional Charge/Credit</label>
    <referenceTo>AdditionalChargeCredit__c</referenceTo>
    <relationshipName>Order_Additional_Charges_Credits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderAdditionalChargeCredit__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Additional_Charges_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>SalesOrder__r.ContactBilling__r.Market_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BoomOrderCloneTest.cls
@isTest
public with sharing class BoomOrderCloneTest {
  @isTest
  public static void testMethod1() {
    Product2 testProd = BoomTestHelpers.generateProduct();
    PricebookEntry testPbe = BoomTestHelpers.generatePricebookEntry(
      testProd.Id
    );
    Market__c testMarket = BoomTestHelpers.generateMarket(testPbe.Pricebook2Id, true);
    Account testAcct = BoomTestHelpers.generateAccount();
    Contact testCont = BoomTestHelpers.generateContact(testAcct.Id);
    Opportunity testOpp = BoomTestHelpers.generateOpportunity(
      testAcct.Id,
      testMarket.Id,
      testCont.Id
    );
    System.debug(testCont);

    SalesOrder__c testSO = BoomTestHelpers.generateTestBoomOrder(testOpp.Id);
    AdditionalChargeCredit__c testACC = BoomTestHelpers.generateAdditionalChargeCredit(testProd.Id);
    SalesOrderAdditionalChargeCredit__c testSAOCC = new SalesOrderAdditionalChargeCredit__c(
      SalesOrder__c = testSO.Id,
      Additional_Charge_Credit__c = testACC.Id
    );
    insert testSAOCC;

    SalesOrderProductLine__c testOPL = BoomTestHelpers.generateBoomProductLine(testSO.Id, testPbe);
    Order_Line_Recipient__c testOLR = BoomTestHelpers.generateTestLineRecipient(testSO.Id, testOPL.Id, testCont.Id, true);

    Test.startTest();
        Id clonedOrder = BoomOrderCloneController.cloneBoomOrder(testSO.Id);
    System.assertEquals(
      true,
      String.isNotEmpty(clonedOrder),
      'A new order was created'
    );
    Test.stopTest();
  }
}