force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Fulfillment</label>
    <nameField>
        <displayFormat>F-{000000}</displayFormat>
        <label>Fulfillment Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment__c/fields/Boom_Order_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Boom_Order_Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Boom Order Product Line</label>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <referenceTo>kugo2p__SalesOrderProductLine__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>OrderProductLine__r.kugo2p__Quantity__c</description>
    <formula>Boom_Order_Product_Line__r.Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Kit_Bundle_Member__c/Kit_Bundle_Member__c.object-meta.xml
<CustomObject>
    <label>Kit/Bundle Member</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Kit/Bundle Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kit/Bundle Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kit_Bundle_Member__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Default Quantity value. Sets the initial Quantity value in Quote and Order configurator page. If blank, the Default Quantity is 1</description>
    <label>Default Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/Order_Line_Recipient__c.object-meta.xml
<CustomObject>
    <label>Order Line Recipient</label>
    <nameField>
        <displayFormat>OLR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fulfillment</label>
    <referenceTo>Fulfillment__c</referenceTo>
    <relationshipLabel>Order Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Order Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/OrderProductLine__c.field-meta.xml
<CustomField>
    <fullName>OrderProductLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SalesOrderProductLine__c.SalesOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Order__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <formula>Amount__c - Transaction_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Sample_Product__c.field-meta.xml
<CustomField>
    <fullName>Sample_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sample Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Account Name, which is required. 

To change the required Account name, please update the Additional Account Info field on this Order. If the field is not visible, please contact your Administrator. For Released or Paid Orders, please also update the Invoice and Payment records.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactBilling__c.field-meta.xml
<CustomField>
    <fullName>ContactBilling__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <formula>round(ProductAmount__c + AdditionalChargeCreditAmount__c - TotalDiscountAmount__c + TotalTaxAmount__c + TotalVATAmount__c,2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Sample_ELM_Copy__c.field-meta.xml
<CustomField>
    <fullName>Sample_ELM_Copy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sample ELM Copy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>Payment Update Needed</fullName>
            </value>
            <value>
                <fullName>Subscription Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Kit_Bundle_Member__c.field-meta.xml
<CustomField>
    <fullName>Kit_Bundle_Member__c</fullName>
    <formula>IF( ISBLANK( KitBundleLine__c ) , false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Kit/Bundle Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/KitBundle__c.field-meta.xml
<CustomField>
    <fullName>KitBundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Kit/Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/KitBundleLine__c.field-meta.xml
<CustomField>
    <fullName>KitBundleLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit/Bundle Line</label>
    <referenceTo>SalesOrderProductLine__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>SalesOrder__r.ContactBilling__r.Market_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <formula>round(TotalAmount__c  +  TaxAmount__c,2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Sample_Product__c.field-meta.xml
<CustomField>
    <fullName>Sample_Product__c</fullName>
    <formula>Product__r.Sample_Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sample Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SalesOrderProductLineHelperTest.cls
/**
   * *************************************************************************
   * * uncomment everything that's commented below if I leave anything out *
   * *************************************************************************
   */

@isTest
public with sharing class SalesOrderProductLineHelperTest {
  @TestSetup
  static void setup() {
    Account testAcc = BoomTestHelpers.generateAccount();
    Contact testCtc = BoomTestHelpers.generateContact(testAcc.Id);
    Product2 testPdc1 = BoomTestHelpers.generateProduct();
    Product2 testPdc2 = BoomTestHelpers.generateProduct();
    Kit_Bundle_Member__c sampleMember = BoomTestHelpers.generateTestKitBundle(
      testPdc1.Id,
      testPdc2.Id
    );
    PricebookEntry testPbe1 = BoomTestHelpers.generatePriceBookEntry(
      testPdc1.Id
    );
    PricebookEntry testPbe2 = BoomTestHelpers.generatePriceBookEntry(
      testPdc2.Id
    );
    Market__c testMkt = BoomTestHelpers.generateMarket(
      testPbe1.Pricebook2Id,
      true
    );
    Opportunity testOpp = BoomTestHelpers.generateOpportunity(
      testAcc.Id,
      testMkt.Id,
      testCtc.Id
    );
    SalesOrder__c testSo = BoomTestHelpers.generateTestBoomOrder(testOpp.Id);

    SalesOrderProductLine__c testProdLine = BoomTestHelpers.generateBoomProductLine(
      testSo.Id,
      testPbe1
    );

    Order_Line_Recipient__c testRecipient = BoomTestHelpers.generateTestLineRecipient(
      testSo.Id,
      testProdLine.Id,
      testCtc.Id,
      true
    );
  }

  @isTest
  private static void testInsert() {
    SalesOrderProductLine__c insertedProdLine = [
      SELECT KitBundle__c, Id, SalesOrder__c
      FROM SalesOrderProductLine__c
      WHERE SalesPrice__c = 10 AND Quantity__c = 5 AND KitBundle__c = TRUE
      ORDER BY CreatedDate DESC
      LIMIT 1
    ];
    System.assertEquals(
      false,
      insertedProdLine == null,
      'Product line was not modified at insert'
    );

    List<SalesOrderProductLine__c> bundleProdLine = [
      SELECT Id, KitBundleLine__c
      FROM SalesOrderProductLine__c
      WHERE KitBundleLine__c = :insertedProdLine.Id
    ];

    System.assertEquals(
      true,
      bundleProdLine.size() > 0,
      'Bundle product line was not created'
    );


    Product2 sampleProd = BoomTestHelpers.generateProduct();
    sampleProd.Sample_Product__c = true;
    update sampleProd;

    PricebookEntry samplePbe = BoomTestHelpers.generatePriceBookEntry(
      sampleProd.Id
    );
    samplePbe.UnitPrice = 0;
    update samplePbe;

    SalesOrderProductLine__c testSampleProdLine = BoomTestHelpers.generateBoomProductLine(
      insertedProdLine.SalesOrder__c,
      samplePbe
    );

    List<SalesOrder__c> sampleOrders = [
      SELECT Id
      FROM SalesOrder__c
      WHERE Sample_ELM_Copy__c = true
    ];

    System.assertEquals(
      true,
      sampleOrders.size() == 0,
      'Order should not be a sample order'
    );


  }

  @isTest
  private static void testSampleProdInsert() {
    Product2 sampleProd = BoomTestHelpers.generateProduct();
    sampleProd.Sample_Product__c = true;
    update sampleProd;

    PricebookEntry samplePbe = BoomTestHelpers.generatePriceBookEntry(
      sampleProd.Id
    );
    samplePbe.UnitPrice = 0;
    update samplePbe;

    SalesOrder__c testSo = [
      SELECT Id
      FROM SalesOrder__c
      WHERE CreatedDate = TODAY
      ORDER BY CreatedDate DESC
      LIMIT 1
    ];

    delete [SELECT Id FROM SalesOrderProductLine__c WHERE SalesOrder__c = :testSo.Id];

    SalesOrderProductLine__c testProdLine = BoomTestHelpers.generateBoomProductLine(
      testSo.Id,
      samplePbe
    );
    

    List<SalesOrder__c> sampleOrders = [
      SELECT Id
      FROM SalesOrder__c
      WHERE Sample_ELM_Copy__c = true
      AND Id = :testSo.Id
    ];

    System.assertEquals(
      true,
      sampleOrders.size() > 0,
      'Order was not updated'
    );

    delete testProdLine;

    List<SalesOrder__c> sampleOrders2 = [
      SELECT Id
      FROM SalesOrder__c
      WHERE Sample_ELM_Copy__c = true
      AND Id = :testSo.Id
    ];

    System.assertEquals(
      true,
      sampleOrders2.size() == 0,
      'Order was not unset'
    );
    
    SalesOrderProductLine__c testProdLine2 = BoomTestHelpers.generateBoomProductLine(
      testSo.Id,
      samplePbe
    );

    List<SalesOrder__c> resetOrders = [
      SELECT Id
      FROM SalesOrder__c
      WHERE Sample_ELM_Copy__c = true
      AND Id = :testSo.Id
    ];

    Boolean beforeUpdate = sampleOrders.size() > 0;

    Product2 regProd = BoomTestHelpers.generateProduct();
    PricebookEntry regPbe = BoomTestHelpers.generatePriceBookEntry(
      regProd.Id
    );
    SalesOrderProductLine__c regProdLine = BoomTestHelpers.generateBoomProductLine(
      testSo.Id,
      regPbe
    );

    List<SalesOrder__c> removedSampleOrders  = [
      SELECT Id
      FROM SalesOrder__c
      WHERE Sample_ELM_Copy__c = true
      AND Id = :testSo.Id
    ];

    Boolean afterUpdate = removedSampleOrders.size() > 0;

    System.assertEquals(
      beforeUpdate,
      !afterUpdate,
      'Order was not updated'
    );


  }

  @isTest
  private static void testUpdate() {
    SalesOrderProductLine__c prodLineToUpdate = [
      SELECT KitBundle__c, Id
      FROM SalesOrderProductLine__c
      WHERE SalesPrice__c = 10 AND Quantity__c = 5 AND KitBundle__c = TRUE
      ORDER BY CreatedDate DESC
      LIMIT 1
    ];

    prodLineToUpdate.Quantity__c = 10;
    update prodLineToUpdate;
  }

  @isTest
  private static void testDelete() {
    SalesOrderProductLine__c prodLineToDelete = [
      SELECT KitBundle__c, Id,SalesOrder__c
      FROM SalesOrderProductLine__c
      WHERE SalesPrice__c = 10 AND KitBundle__c = TRUE
      ORDER BY CreatedDate DESC
      LIMIT 1
    ];

    SalesOrder__c testSo = [
      SELECT Id, NetAmount__c,ContactBilling__c,Account__c
      FROM SalesOrder__c
      WHERE Id = :prodLineToDelete.SalesOrder__c
      LIMIT 1
    ];

    testSo.Status_Picklist__c = 'Approved';
    update testSo;

    Payment_Method__c testPmtMethod = BoomTestHelpers.generateTestPmtMethod(
      testSo.ContactBilling__c,
      false
    );

    Payment__c testPmt = BoomTestHelpers.generateTestPayment(
      testSo.Id,
      testSo.Account__c,
      testSo.ContactBilling__c,
      testPmtMethod.Id,
      testSo.NetAmount__c,
      'Completed'
    );

    // List<Fulfillment__c> beforeDeleteFulfillments = [
    //   SELECT Id
    //   FROM Fulfillment__c
    //   WHERE Boom_Order_Product_Line__c = :prodLineToDelete.Id
    // ];

    // System.assertEquals(
    //   true,
    //   beforeDeleteFulfillments.size() > 0,
    //   'Fulfillments were not created'
    // );
    
    testSo.Status_Picklist__c = 'Draft';
    update testSo;

    delete prodLineToDelete;

    List<SalesOrderProductLine__c> bundleProdLine = [
      SELECT Id, KitBundleLine__c
      FROM SalesOrderProductLine__c
      WHERE KitBundleLine__c = :prodLineToDelete.Id
    ];

    // List<Fulfillment__c> afterDeleteFulfillments = [
    //   SELECT Id
    //   FROM Fulfillment__c
    //   WHERE Boom_Order_Product_Line__c = :prodLineToDelete.Id
    // ];

    List<Order_Line_Recipient__c> afterDeleteRecipients = [
      SELECT Id
      FROM Order_Line_Recipient__c
      WHERE OrderProductLine__c = :prodLineToDelete.Id
    ];

    System.assertEquals(
      false,
      bundleProdLine.size() > 0,
      'Bundle product line was not deleted'
    );

    // System.assertEquals(
    //   false,
    //   afterDeleteFulfillments.size() > 0,
    //   'Fulfillments were not deleted'
    // );

    System.assertEquals(
      false,
      afterDeleteRecipients.size() > 0,
      'Recipients were not deleted'
    );
  }


}