force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Professionals</relationshipLabel>
    <relationshipName>Professionals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Market_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Market_Close_Date__c</fullName>
    <description>Pub date in numeric form (first of the month for monthly pub, date of publication for daily pub)</description>
    <inlineHelpText>Pub date in numeric form (first of the month for monthly pub, date of publication for daily pub)</inlineHelpText>
    <label>Market Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Market_Close_Date__c</fullName>
    <formula>Market_Project__r.Market_Close_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ScheduleAppointmentControllerTest.cls
@isTest
public class ScheduleAppointmentControllerTest {
  static testMethod void schedule() {
    test.startTest();

    Account acc = new Account();
    acc.Name = 'testContact';
    insert acc;

    Contact con = new Contact();
    con.AccountId = acc.Id;
    con.FirstName = 'Test Name';
    con.LastName = 'Test Last';
    insert con;

    Market__c mark = new Market__c();
    mark.Name = 'Test';
    mark.Market_Close_Date__c = System.today().addDays(30);
    insert mark;

    Opportunity testOppty = new Opportunity();
    testOppty.name = 'testOppty';
    testOppty.AccountId = acc.id;
    testOppty.Contact__c = con.id;
    testOppty.StageName = 'Open';
    testOppty.CloseDate = System.today();
    testOppty.Market_Project__c = mark.Id;
    insert testOppty;

    PageReference pageRef = Page.ScheduleAppointment;
    Test.setCurrentPage(pageRef);
    pageRef.getParameters().put('id', testOppty.id);
    ApexPages.StandardController sc = new ApexPages.standardController(
      testOppty
    );

    ScheduleAppointmentController controller = new ScheduleAppointmentController(
      sc
    );
    controller.btnRedirection();
  }
}