force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>Payment Update Needed</fullName>
            </value>
            <value>
                <fullName>Subscription Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>SalesOrder__r.ContactBilling__r.Market_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BoomPaymentTerminal_Tests.cls
@isTest
public with sharing class BoomPaymentTerminal_Tests {
    @TestSetup
    static void makeData(){
        Product2 testProd = BoomTestHelpers.generateProduct();
        PricebookEntry pbE1 = BoomTestHelpers.generatePriceBookEntry(testProd.Id);
        Market__c mkt = BoomTestHelpers.generateMarket(pbe1.Pricebook2Id, true);
        Account a = BoomTestHelpers.generateAccount();
        Contact c = BoomTestHelpers.generateContact(a.Id);
        Opportunity o = BoomTestHelpers.generateOpportunity(a.Id, mkt.Id, c.Id);
        SalesOrder__c so = BoomTestHelpers.generateTestBoomOrder(o.Id);
        SalesOrderProductLine__c sopl = BoomTestHelpers.generateBoomProductLine(so.Id, pbe1);

        so.Status_Picklist__c = 'Approved';

        update so;

        Payment_Method__c pm = BoomTestHelpers.generateTestPmtMethod(c.Id, true);

    }
    @isTest
    public static void testSaveCustomer() {
        Test.setMock(HttpCalloutMock.class, new ZealynxHttpMockGenerator());
        SalesOrder__c so = [SELECT Id FROM SalesOrder__c LIMIT 1];
        Contact c = [SELECT Id FROM Contact LIMIT 1];

        Test.startTest();
        BoomPaymentTerminal_LightningController.TerminalWrapper tw = BoomPaymentTerminal_LightningController.getRecordData(so.Id);
        Map<Id, Payment_Method__c> pmMap = BoomPaymentTerminal_LightningController.returnPaymentMethods(c.Id);
        Contact ctc = BoomPaymentTerminal_LightningController.returnRelatedContact(c.Id);
        Contact updatedCtc = BoomPaymentTerminal_LightningController.saveCustomer(ctc);
        Test.stopTest();

    }
    
    @isTest
    public static void testSavePaymentMethod() { 
        Test.setMock(HttpCalloutMock.class, new ZealynxHttpMockGenerator());
        Contact c = [SELECT Id FROM Contact LIMIT 1];
        Map<Id, Payment_Method__c> pmMap = BoomPaymentTerminal_LightningController.returnPaymentMethods(c.Id);

        Test.startTest();
        BoomPaymentTerminal_LightningController.CustomPaymentMethod cpm = new BoomPaymentTerminal_LightningController.CustomPaymentMethod();
        cpm.cardNumber = '4242424242424242';
        cpm.expirationMonth = '12';
        cpm.expirationYear = '2029';
        cpm.customerMerchantId = '1234';
        BoomPaymentTerminal_LightningController.savePaymentMethod(pmMap.values()[0], cpm);
        Test.stopTest();

    }

    @isTest
    public static void testPayment(){
        Test.setMock(HttpCalloutMock.class, new ZealynxHttpMockGenerator());

        Contact ctc = [SELECT Id FROM Contact LIMIT 1];
        Map<Id, Payment_Method__c> pmMap = BoomPaymentTerminal_LightningController.returnPaymentMethods(ctc.Id);
        SalesOrder__c so = [SELECT Id FROM SalesOrder__c LIMIT 1];

        Test.startTest();
        BoomPaymentTerminal_LightningController.MultiplePayment mp = new BoomPaymentTerminal_LightningController.MultiplePayment();
        mp.waveFinanceFee = false;
        mp.contactId = ctc.Id;
        mp.financeFee = 10;
        mp.paymentAmount = 10;
        mp.firstPayment = 10;
        mp.paymentMethodId = pmMap.values()[0].Id;
        mp.salesOrderId = so.Id;
        mp.newFirstPaymentDate = System.today().addMonths(1);
        mp.numberOfPayments = 2;
        BoomPaymentTerminal_LightningController.handleMultiplePayments(mp);
        Test.stopTest();

    }
}