force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/Order_Line_Recipient__c.object-meta.xml
<CustomObject>
    <label>Order Line Recipient</label>
    <nameField>
        <displayFormat>OLR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Order Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>Payment Update Needed</fullName>
            </value>
            <value>
                <fullName>Subscription Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>SalesOrder__r.ContactBilling__r.Market_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SalesOrderPDFExtensionTest.cls
@isTest
public with sharing class SalesOrderPDFExtensionTest {
  @isTest
  private static void salesOrderPdfTest() {
    Account testAcc = BoomTestHelpers.generateAccount();
    Contact testCtc = BoomTestHelpers.generateContact(testAcc.Id);
    Product2 testPdc = BoomTestHelpers.generateProduct();
    PricebookEntry testPbe = BoomTestHelpers.generatePriceBookEntry(testPdc.Id);
    Market__c testMkt = BoomTestHelpers.generateMarket(
      testPbe.Pricebook2Id,
      true
    );
    Opportunity testOpp = BoomTestHelpers.generateOpportunity(
      testAcc.Id,
      testMkt.Id,
      testCtc.Id
    );
    SalesOrder__c testSo = BoomTestHelpers.generateTestBoomOrder(testOpp.Id);
    SalesOrderProductLine__c testProdLine = BoomTestHelpers.generateBoomProductLine(
      testSo.Id,
      testPbe
    );
    Order_Line_Recipient__c testRecipient = BoomTestHelpers.generateTestLineRecipient(
      testSo.Id,
      testProdLine.Id,
      testCtc.Id,
      true
    );

    testSo.Status_Picklist__c = 'Approved';

    update testSo;
    Payment_Method__c testPmtMethod = BoomTestHelpers.generateTestPmtMethod(
      testCtc.Id,
      false
    );
    Payment__c testPmt = BoomTestHelpers.generateTestPayment(
      testSo.Id,
      testAcc.Id,
      testCtc.Id,
      testPmtMethod.Id,
      50,
      'Completed'
    );

    Pagereference testPageRef = Page.OnlineOrderVf;
    Test.setCurrentPage(testPageRef);
    ApexPages.currentPage().getParameters().put('id', testSo.Id);
    ApexPages.currentPage().getParameters().put('acceptedByName', 'Test Name');
    ApexPages.currentPage().getParameters().put('signature', 'Test Signature');
    SalesOrderPDFExtension custController = new SalesOrderPDFExtension();
    SalesOrderPDFExtension controller = new SalesOrderPDFExtension(new ApexPages.StandardController(testSo));
    
    System.assertEquals(controller.orderId, testSo.Id, 'Ids should match');
    controller.captureAcceptedByInput();
    System.assertEquals(
      controller.acceptedBy,
      'Test Name',
      'Names should match'
    );
    Boolean oldAcceptTerms = controller.acceptTerms;
    controller.toggleAcceptTerms();
    Boolean newAcceptTerms = controller.acceptTerms;
    System.assertNotEquals(
      oldAcceptTerms,
      newAcceptTerms,
      'Accept terms should have changed'
    );
    System.assertEquals(
      controller.showAcceptedByNameErrorBlock,
      false,
      'Error block should be hidden'
    );
    

    Pagereference testPdfRef = controller.attachPDF();
    System.assertEquals(
      testPdfRef.getParameters().get('id'),
      testSo.Id,
      'Ids should match with pdf ref'
    );

    System.assertEquals(
      'test.pdf.url.com',
      controller.downloadPDFURL,
      'String values should match'
    );

    Pagereference testOnlineTerminalRef = new PageReference(
      '/apex/publicPaymentVfPage?id=' + testSo.Id + '&isEssential=false'
    );
    Pagereference returnedOnlineTerminalRef = controller.acceptAndPayOnline();

    System.assertEquals(testOnlineTerminalRef.getParameters().get('id'), returnedOnlineTerminalRef.getParameters().get('id'), 'Refs should match');

    System.assertEquals('Test Signature', controller.encodedSignature, 'Signatures should match');

    DateTime dt = Datetime.now();

    // System.assertEquals('Jane Doe', controller.InitialedBy, 'Names should match');
    System.assertEquals('Test Name', controller.getTermsAcceptedBy(), 'Names should match');
    System.assertEquals(dt.format(), controller.getTermsAcceptedDate(), 'Dates should match');
    System.assertEquals(controller.getIPAddress(), controller.getTermsAcceptedFromIPAddress(), 'IP Addresses should match');
    System.assertEquals('USD', controller.getISOCurrencyCode(), 'Currency Codes should match');
    System.assertEquals(false, controller.getIsMultiCurrencyEnabled(), 'Multi Currency should match');
    System.assertEquals(false, controller.showInitialByErrorBlock, 'Error block should be hidden');
    System.assertEquals(true, controller.checkout() == null && controller.getProductsHaveDescriptions() && controller.getAccsHaveDescriptions() && controller.getDisplayShipToInfo() && controller.getRenderPaymentButton() && !controller.gethasProductTextandTerms() && controller.getProducts() == null, 'booleans should match');
    System.assertEquals(true, controller.getProductLineCount() == controller.ProductLines.size(), 'Product Line Count should match');
    System.assertEquals(true, controller.getChargeCreditLineCount() == controller.ACCLines.size(), 'Additional Charge Ids should match');
    System.assertEquals('test.com', controller.getLogoUrl(), 'Logo Url should match');
    System.assertEquals(testSo.Id, controller.Order.Id, 'Order ids should match');
    System.assertEquals(true, controller.Payments.size() > 0, 'Payment count should be greater than 0');
    System.assertEquals(true, controller.settings.SignatureLinestoPDF && controller.settings.PrintCompanyTextandTerms && String.isNotEmpty(controller.settings.CompanyTextandTerms) && String.isNotEmpty(controller.settings.OnlinePaymentButton), 'Settings should all have values');
  
    controller.getPaymentURL();
    controller.LineRecipients.size();
    controller.UniqueLineRecipients.size();
    controller.PaymentSchedules.size();
  }
}