force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Professionals</relationshipLabel>
    <relationshipName>Professionals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Markets</relationshipLabel>
    <relationshipName>Markets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApexControllersTest.cls
@isTest
public with sharing class ApexControllersTest {
  @isTest
  public static void ApexControllersTest() {
    Product2 testProd = BoomTestHelpers.generateProduct();
    PricebookEntry testPbe = BoomTestHelpers.generatePricebookEntry(
      testProd.Id
    );
    Market__c testMarket = BoomTestHelpers.generateMarket(
      testPbe.Pricebook2Id,
      true
    );
    Account testAcct = BoomTestHelpers.generateAccount();
    Contact testCont = BoomTestHelpers.generateContact(testAcct.Id);
    Opportunity testOpp = BoomTestHelpers.generateOpportunity(
      testAcct.Id,
      testMarket.Id,
      testCont.Id
    );
    Test.startTest();
    Id oppId = testOpp.Id;
    DescribeSObjectResult describeResult = oppId.getSObjectType().getDescribe();
    Map<String, Schema.SObjectField> fieldMap = describeResult.fields.getMap();

    // Get all of the fields on the object
    List<String> fieldNames = new List<String>(fieldMap.keySet());
    Id ctcId = testCont.Id;
    DescribeSObjectResult describeCtcResult = ctcId.getSObjectType().getDescribe();
    Map<String, Schema.SObjectField> ctcFieldMap = describeResult.fields.getMap();

    // Get all of the fields on the object
    List<String> ctcFieldNames = new List<String>(ctcFieldMap.keySet());

    // Build a Dynamic Query String.
    String soqlQuery =
      ' SELECT ' +
      string.join(fieldNames, ',') + ', Market_Project__r.Price_Book__c, Market_Project__r.Name, ' +
      'Contact__r.MailingCity,Contact__r.MailingCountry,Contact__r.MailingState,Contact__r.MailingStreet,Contact__r.MailingPostalCode,Contact__r.OtherCity,Contact__r.OtherCountry,Account.Name,Contact__r.OtherState,Contact__r.OtherStreet,Contact__r.OtherPostalCode' +
      ' FROM ' +
      describeResult.getName() +
      ' Where Id =: oppId';
    
    soqlQuery = soqlQuery.replace(', Contact__r.isprivate', '');
    List<Opportunity> record = Database.query(soqlQuery);
    ApexPages.StandardController sc = new ApexPages.StandardController(record[0]);
    ApexControllers testController = new ApexControllers(sc);
    Pagereference testPage = testController.generateOrder();
    System.assertEquals(
      testPage.getUrl().contains(String.valueOf(testOpp.Id)),
      true
    );
    Test.stopTest();
  }
}