force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 Year Winner</fullName>
            </value>
            <value>
                <fullName>2 Year Winner</fullName>
            </value>
            <value>
                <fullName>3 Year Winner</fullName>
            </value>
            <value>
                <fullName>4 Year Winner</fullName>
            </value>
            <value>
                <fullName>5 Year Winner</fullName>
            </value>
            <value>
                <fullName>6 Year Winner</fullName>
            </value>
            <value>
                <fullName>7 Year Winner</fullName>
            </value>
            <value>
                <fullName>8 Year Winner</fullName>
            </value>
            <value>
                <fullName>9 Year Winner</fullName>
            </value>
            <value>
                <fullName>10 Year Winner</fullName>
            </value>
            <value>
                <fullName>11 Year Winner</fullName>
            </value>
            <value>
                <fullName>12 Year Winner</fullName>
            </value>
            <value>
                <fullName>13 Year Winner</fullName>
            </value>
            <value>
                <fullName>14 Year Winner</fullName>
            </value>
            <value>
                <fullName>15 Year Winner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Account.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Account.Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Fulfillment__c/Order_Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Order Fulfillment</label>
    <nameField>
        <displayFormat>OF-{000000}</displayFormat>
        <label>Order Fulfillment Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Fulfillments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Fulfillment__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Order Fulfillments</relationshipLabel>
    <relationshipName>Order_Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Fulfillment__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Fulfillments</relationshipLabel>
    <relationshipName>Fulfillments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Fulfillment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Content Received</fullName>
            </value>
            <value>
                <fullName>In Revision</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>To Print</fullName>
            </value>
            <value>
                <fullName>Product Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed No Response</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Ready for FTP</fullName>
            </value>
            <value>
                <fullName>Write copy</fullName>
            </value>
            <value>
                <fullName>In Revision - Urgent</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Scheduled</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Incomplete - 1st Request</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Incomplete - 2nd Request</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Incomplete - 3rd Request</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Incomplete – 4th Request</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Incomplete – Content Needed</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Incomplete – Approval Needed</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Complete - Content Needed</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Complete - Approval Needed</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Complete - Open Fulfillment</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Complete - Urgent Response Needed</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Complete - Follow Up Needed</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Complete – Follow Up Scheduled</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Complete - LONG TERM Follow Up</fullName>
            </value>
            <value>
                <fullName>CSR Appointment Complete</fullName>
            </value>
            <value>
                <fullName>CSR Appointment NOT Complete - Closed</fullName>
            </value>
            <value>
                <fullName>CST Follow Up 1 Complete</fullName>
            </value>
            <value>
                <fullName>CST Follow Up 1 Complete - Open Fulfillment</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/Order_Line_Recipient__c.object-meta.xml
<CustomObject>
    <label>Order Line Recipient</label>
    <nameField>
        <displayFormat>OLR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Order Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Order_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Order_Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Fulfillment</label>
    <referenceTo>Order_Fulfillment__c</referenceTo>
    <relationshipLabel>Order Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>For recording manual payments like a check or cash, please choose &quot;Completed&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/FulfillOrder__c.field-meta.xml
<CustomField>
    <fullName>FulfillOrder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fulfill Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT (Status_Picklist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>Payment Update Needed</fullName>
            </value>
            <value>
                <fullName>Subscription Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>SalesOrder__r.ContactBilling__r.Market_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SalesOrderHelperTest.cls
@isTest
public with sharing class SalesOrderHelperTest {
  @isTest
  private static void testOrderRelease() {
    Account testAcc = BoomTestHelpers.generateAccount();
    Contact testCtc = BoomTestHelpers.generateContact(testAcc.Id);
    Product2 testPdc = BoomTestHelpers.generateProduct();
    PricebookEntry testPbe = BoomTestHelpers.generatePriceBookEntry(testPdc.Id);
    Market__c testMkt = BoomTestHelpers.generateMarket(
      testPbe.Pricebook2Id,
      true
    );
    Opportunity testOpp = BoomTestHelpers.generateOpportunity(
      testAcc.Id,
      testMkt.Id,
      testCtc.Id
    );
    SalesOrder__c testSo = BoomTestHelpers.generateTestBoomOrder(testOpp.Id);
    SalesOrderProductLine__c testProdLine = BoomTestHelpers.generateBoomProductLine(
      testSo.Id,
      testPbe
    );
    Order_Line_Recipient__c testRecipient = BoomTestHelpers.generateTestLineRecipient(
      testSo.Id,
      testProdLine.Id,
      testCtc.Id,
      true
    );

    testSo.Status_Picklist__c = 'Approved';

    update testSo;
    Payment_Method__c testPmtMethod = BoomTestHelpers.generateTestPmtMethod(
      testCtc.Id,
      false
    );
    Payment__c testPmt = BoomTestHelpers.generateTestPayment(
      testSo.Id,
      testAcc.Id,
      testCtc.Id,
      testPmtMethod.Id,
      50,
      'Scheduled'
    );

    Payment__c testPmt2 = BoomTestHelpers.generateTestPayment(
      testSo.Id,
      testAcc.Id,
      testCtc.Id,
      testPmtMethod.Id,
      50,
      'Completed'
    );

    List<Order_Fulfillment__c> fulfillments = [
      SELECT Id
      FROM Order_Fulfillment__c
      WHERE OrderNumber__c = :testSo.Id
    ];

    SalesOrder__c updSo = [
      SELECT Id, Status_Picklist__c, FulfillOrder__c
      FROM SalesOrder__c
      WHERE Id = :testSo.Id
      LIMIT 1
    ];

    List<Payment__c> cxlPmts = [
      SELECT Id
      FROM Payment__c
      WHERE Status__c='Cancelled'
      AND Id=:testPmt.Id
    ];

    System.assertEquals(true, cxlPmts.size() > 0, 'Cancelled Payment not found');

    System.assertEquals(
      'Released',
      updSo.Status_Picklist__c,
      'Sales Order Status is not Released'
    );
    System.assertEquals(
      true,
      fulfillments.size() > 0,
      'Sales Order has no Order Fulfillments. FulfillOrder__c is :' +
      updSo.FulfillOrder__c
    );
    PriceBook2 customPriceBook = new PriceBook2();
    customPriceBook.Name = 'Custom Pricebook';
    customPriceBook.IsActive = true;
    insert customPriceBook;

    updSo.Price_Book__c = customPriceBook.Id;

    update updSo;
  }
}