force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Professionals</relationshipLabel>
    <relationshipName>Professionals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Markets</relationshipLabel>
    <relationshipName>Markets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Account Name, which is required. 

To change the required Account name, please update the Additional Account Info field on this Order. If the field is not visible, please contact your Administrator. For Released or Paid Orders, please also update the Invoice and Payment records.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/BillToCity__c.field-meta.xml
<CustomField>
    <fullName>BillToCity__c</fullName>
    <label>Bill To City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/BillToCountry__c.field-meta.xml
<CustomField>
    <fullName>BillToCountry__c</fullName>
    <label>Bill To Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/BillToName__c.field-meta.xml
<CustomField>
    <fullName>BillToName__c</fullName>
    <label>Bill To Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/BillToStateProvince__c.field-meta.xml
<CustomField>
    <fullName>BillToStateProvince__c</fullName>
    <label>Bill To State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/BillToStreetLong__c.field-meta.xml
<CustomField>
    <fullName>BillToStreetLong__c</fullName>
    <description>A longer version of the original BillToStreet__c field</description>
    <label>Bill To Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/BillToZipPostalCode__c.field-meta.xml
<CustomField>
    <fullName>BillToZipPostalCode__c</fullName>
    <label>Bill To Zip/Postal Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactBilling__c.field-meta.xml
<CustomField>
    <fullName>ContactBilling__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactBuying__c.field-meta.xml
<CustomField>
    <fullName>ContactBuying__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Buying</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactShipping__c.field-meta.xml
<CustomField>
    <fullName>ContactShipping__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Shipping</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SalesOrders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.Contact__r.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Boom Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/OrderDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/OrderName__c.field-meta.xml
<CustomField>
    <fullName>OrderName__c</fullName>
    <label>Order Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Changing the price book will delete all product order lines associated with this sales order.</description>
    <inlineHelpText>Changing the price book will delete all product order lines associated with this sales order.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ShipToCity__c.field-meta.xml
<CustomField>
    <fullName>ShipToCity__c</fullName>
    <label>Ship To City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ShipToCountry__c.field-meta.xml
<CustomField>
    <fullName>ShipToCountry__c</fullName>
    <label>Ship To Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ShipToName__c.field-meta.xml
<CustomField>
    <fullName>ShipToName__c</fullName>
    <label>Ship To Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ShipToStateProvince__c.field-meta.xml
<CustomField>
    <fullName>ShipToStateProvince__c</fullName>
    <label>Ship To State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ShipToStreetLong__c.field-meta.xml
<CustomField>
    <fullName>ShipToStreetLong__c</fullName>
    <description>A longer version of the origingal ShipToStreet__c field</description>
    <label>Ship To Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ShipToZipPostalCode__c.field-meta.xml
<CustomField>
    <fullName>ShipToZipPostalCode__c</fullName>
    <label>Ship To Zip/Postal Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApexControllers.cls
public class ApexControllers {
  public Id owner { get; set; }
  public Id Id { get; set; }
  public Opportunity opp { get; set; }

  public ApexControllers(ApexPages.StandardController controller) {
    opp = (Opportunity) controller.getRecord();
    Id = opp.Id;
    if(!Test.isRunningTest()) {
      owner = opp.OwnerId;
    } else {
      owner = UserInfo.getUserId();
    }
  }

  public Pagereference generateOrder() {
   
    SalesOrder__c generatedSO = new SalesOrder__c();
    generatedSO.OrderDate__c = System.today();
    generatedSO.OrderName__c = opp.Name;
    generatedSO.Market__c = opp.Market_Project__c;
    generatedSO.Opportunity__c = Id;
    generatedSO.Account__c = opp.AccountId;
    if (opp.Market_Project__r.Price_Book__c == null) {
      Pricebook2 pb = [
        SELECT Id
        FROM Pricebook2
        WHERE Name = :opp.Market_Project__r.Name
        LIMIT 1
      ];
      generatedSO.Price_Book__c = pb.Id;
    } else {
      generatedSO.Price_Book__c = opp.Market_Project__r.Price_Book__c;
    }

    generatedSO.ContactBilling__c = opp.Contact__r.Id;
    generatedSO.ContactBuying__c = opp.Contact__r.Id;
    generatedSO.ContactShipping__c = opp.Contact__r.Id;
    generatedSO.BillToName__c = opp.Account.Name;
    generatedSO.BillToCity__c = opp.Contact__r.MailingCity;
    generatedSO.BillToCountry__c = opp.Contact__r.MailingCountry;
    generatedSO.BillToStateProvince__c = opp.Contact__r.MailingState;
    generatedSO.BillToStreetLong__c = opp.Contact__r.MailingStreet;
    generatedSO.BillToZipPostalCode__c = opp.Contact__r.MailingPostalCode;
    generatedSO.ShipToCity__c = opp.Contact__r.OtherCity;
    generatedSO.ShipToCountry__c = opp.Contact__r.OtherCountry;
    generatedSO.ShipToName__c = opp.Account.Name;
    generatedSO.ShipToStateProvince__c = opp.Contact__r.OtherState;
    generatedSO.ShipToStreetLong__c = opp.Contact__r.OtherStreet;
    generatedSO.ShipToZipPostalCode__c = opp.Contact__r.OtherPostalCode;
    try {
      Database.SaveResult sr = Database.insert(generatedSO, false);
      PageReference pageRef = new PageReference('/' + sr.getId());
      if(Test.isRunningTest()) {
        return new Pagereference('/'+ opp.Id);
      }

      pageRef.setRedirect(true);
      
      return pageRef;
    } catch (DmlException err) {
      opp.addError(err.getMessage());
      return null;
    }
  }
}