force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>This date is set when a desired end date is needed for the subscription</description>
    <inlineHelpText>This date is set when a desired end date is needed for the subscription</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Re_start_Date__c.field-meta.xml
<CustomField>
    <fullName>Re_start_Date__c</fullName>
    <description>When a subscription is status = paused, it will automatically go back to Active on the Re-start Date.</description>
    <inlineHelpText>When a subscription is status = paused, it will automatically go back to Active on the Re-start Date.</inlineHelpText>
    <label>Re-start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubscriptionStatusBatch.cls
global class SubscriptionStatusBatch implements Database.Batchable<sObject>,Database.Stateful{
    private String queryString;

    global SubscriptionStatusBatch() {
        if(String.isBlank(queryString)) {
            queryString = 'SELECT Id, End_Date__c, Re_Start_Date__c ';
            queryString += 'FROM Subscription__c ';
            queryString += 'WHERE (End_Date__c  <= TODAY AND Status__c != \'Cancelled\') ';
            queryString += 'OR (Re_Start_Date__c <= TODAY AND Status__c != \'Active\')';
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(queryString);
    }

    global void execute(Database.BatchableContext info, List<Subscription__c> scope) {
        List<Subscription__c> updatedSubs = new List<Subscription__c>();

        for(Subscription__c sub : scope) {
            Date today = System.today();

            if(sub.End_Date__c <= today) {
                sub.Status__c = 'Cancelled';
            } else if(sub.Re_Start_Date__c <= today) {
                sub.Status__c = 'Active';
            }

            updatedSubs.add(sub);
        }

        if(updatedSubs.size() > 0) {
            Database.update(updatedSubs, false);
        }
    }

    global void finish(Database.BatchableContext info) {
        
    }
}