force-app/main/default/objects/OppIdsToUpdate__mdt/OppIdsToUpdate__mdt.object-meta.xml
<CustomObject>
    <label>OppIdsToUpdate</label>
    <pluralLabel>OppIdsToUpdates</pluralLabel>
</CustomObject>

force-app/main/default/objects/OppIdsToUpdate__mdt/fields/OppIds__c.field-meta.xml
<CustomField>
    <fullName>OppIds__c</fullName>
    <label>OppIds</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pardot_Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Pardot_Campaign_Type__c</fullName>
    <label>Pardot Campaign Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>WSJ Showcase I</fullName>
            </value>
            <value>
                <fullName>WSJ Showcase II</fullName>
            </value>
            <value>
                <fullName>WiW WSJ Showcase I</fullName>
            </value>
            <value>
                <fullName>WiW WSJ Showcase II</fullName>
            </value>
            <value>
                <fullName>WiW MAG Showcase I</fullName>
            </value>
            <value>
                <fullName>Forbes Investment Guide I</fullName>
            </value>
            <value>
                <fullName>Forbes Investment Guide II</fullName>
            </value>
            <value>
                <fullName>BFF Showcase</fullName>
            </value>
            <value>
                <fullName>Digital Showcase I</fullName>
            </value>
            <value>
                <fullName>Digital Showcase II</fullName>
            </value>
            <value>
                <fullName>Alumni Showcase I</fullName>
            </value>
            <value>
                <fullName>Alumni Showcase II</fullName>
            </value>
            <value>
                <fullName>Relocation Guide I</fullName>
            </value>
            <value>
                <fullName>Relocation Guide II</fullName>
            </value>
            <value>
                <fullName>Airline Mag Showcase I</fullName>
            </value>
            <value>
                <fullName>Other Alt Media I</fullName>
            </value>
            <value>
                <fullName>Other Alt Media II</fullName>
            </value>
            <value>
                <fullName>Post-market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestUpdateOpportunityFieldBatchClass.cls
public class TestUpdateOpportunityFieldBatchClass {
    public static void  testUpdateOpportunityFieldBatch(integer batchsize)
    {
        Set<String> setOppIds = new Set<String>();
        List<OppIdsToUpdate__mdt> lstOppMdt= [SELECT Label,OppIds__c  FROM OppIdsToUpdate__mdt];
        for(OppIdsToUpdate__mdt oppmdt:lstOppMdt)
        {
            if(!String.isBlank(oppmdt.OppIds__c))
            {
                List<String> lstOppIds= oppmdt.OppIds__c.Split(',');
                for(String oppid:lstOppIds)
                {
                    setOppIds.add(oppid);
                }
            }
        }        
        if(Test.isRunningTest())
        {
            setOppIds.Clear();
            Opportunity opp = [select id , Market_Project__c from Opportunity  where Market_Project__c!= null limit 1];
            setOppIds.add(opp.id);
        }       
        
        UpdateOpportunityField updateOpp = new UpdateOpportunityField();
        updateOpp.setOppIds = setOppIds;
        updateOpp.query = 'select id,Pardot_Campaign_Type__c, Market_Project__c from Opportunity where id in :setOppIds AND Market_Project__c!= null';
        Database.executeBatch(updateOpp,batchsize);

    }
}