force-app/main/default/objects/Opportunity/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pardot_Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Pardot_Campaign_Type__c</fullName>
    <label>Pardot Campaign Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>WSJ Showcase I</fullName>
            </value>
            <value>
                <fullName>WSJ Showcase II</fullName>
            </value>
            <value>
                <fullName>WiW WSJ Showcase I</fullName>
            </value>
            <value>
                <fullName>WiW WSJ Showcase II</fullName>
            </value>
            <value>
                <fullName>WiW MAG Showcase I</fullName>
            </value>
            <value>
                <fullName>Forbes Investment Guide I</fullName>
            </value>
            <value>
                <fullName>Forbes Investment Guide II</fullName>
            </value>
            <value>
                <fullName>BFF Showcase</fullName>
            </value>
            <value>
                <fullName>Digital Showcase I</fullName>
            </value>
            <value>
                <fullName>Digital Showcase II</fullName>
            </value>
            <value>
                <fullName>Alumni Showcase I</fullName>
            </value>
            <value>
                <fullName>Alumni Showcase II</fullName>
            </value>
            <value>
                <fullName>Relocation Guide I</fullName>
            </value>
            <value>
                <fullName>Relocation Guide II</fullName>
            </value>
            <value>
                <fullName>Airline Mag Showcase I</fullName>
            </value>
            <value>
                <fullName>Other Alt Media I</fullName>
            </value>
            <value>
                <fullName>Other Alt Media II</fullName>
            </value>
            <value>
                <fullName>Post-market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateOpportunityField.cls
global class UpdateOpportunityField implements Database.Batchable<sObject> {
  public String query;
  global set<string> setOppIds;

  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(query);
  }

  global void execute(Database.BatchableContext BC, List<sObject> scope) {
    List<Opportunity> lstOpp = new List<Opportunity>();
    for (SObject s : scope) {
      Opportunity opp = (Opportunity) s;
      if (!String.isBlank(opp.Market_Project__c)) {
        // opp.Pardot_Campaign_Type__c = 'Core';
        lstOpp.add(opp);
      }
      //s.put('Market_Project__c', s.get('Market_Project__c'));
      //s.put('Pardot_Campaign_Type__c','Core');
    }
    if (!Test.isRunningTest() && lstOpp.size() > 0) {
      update lstOpp;
    }
  }

  global void finish(Database.BatchableContext BC) {
  }
}