force-app/main/default/objects/Contact/fields/ACDF_Branch_Office__c.field-meta.xml
<CustomField>
    <fullName>ACDF_Branch_Office__c</fullName>
    <description>This is normalized company field to be used for the client.</description>
    <inlineHelpText>This is the official company field to be used in the index.</inlineHelpText>
    <label>Company</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Office City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Office State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Account.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager_Name__c</fullName>
    <formula>FSP_Sales_Rep__r.FirstName + &quot; &quot; + FSP_Sales_Rep__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Manager Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ACDF_Branch_Office__c.field-meta.xml
<CustomField>
    <fullName>ACDF_Branch_Office__c</fullName>
    <formula>Contact__r.ACDF_Branch_Office__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ACDF Branch Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Account.Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total transaction amount (including tax, shipping and fees)</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Authorization_Id__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Id__c</fullName>
    <inlineHelpText>Authorization ID returned from payment processor.</inlineHelpText>
    <label>Authorization Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Billing_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Name__c</fullName>
    <label>Billing Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/CardType__c.field-meta.xml
<CustomField>
    <fullName>CardType__c</fullName>
    <formula>TEXT(Payment_Method__r.Card_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Card Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <inlineHelpText>Actual date of payment.</inlineHelpText>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Last_Four_Digits__c.field-meta.xml
<CustomField>
    <fullName>Last_Four_Digits__c</fullName>
    <formula>Payment_Method__r.Last_4_Digits_of_Card__c</formula>
    <label>Last 4 Digits</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>For recording manual payments like a check or cash, please choose &quot;Completed&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Transaction Id returned from payment processor.</inlineHelpText>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Authorization</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Billing_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_First_Name__c</fullName>
    <label>Billing First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Billing_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Last_Name__c</fullName>
    <label>Billing Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Billing_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Postal_Code__c</fullName>
    <label>Billing Postal Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Billing State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Billing Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/BillToCity__c.field-meta.xml
<CustomField>
    <fullName>BillToCity__c</fullName>
    <label>Bill To City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/BillToStateProvince__c.field-meta.xml
<CustomField>
    <fullName>BillToStateProvince__c</fullName>
    <label>Bill To State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/BillToStreetLong__c.field-meta.xml
<CustomField>
    <fullName>BillToStreetLong__c</fullName>
    <description>A longer version of the original BillToStreet__c field</description>
    <label>Bill To Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/BillToZipPostalCode__c.field-meta.xml
<CustomField>
    <fullName>BillToZipPostalCode__c</fullName>
    <label>Bill To Zip/Postal Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactBilling__c.field-meta.xml
<CustomField>
    <fullName>ContactBilling__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactBuying__c.field-meta.xml
<CustomField>
    <fullName>ContactBuying__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Buying</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.Contact__r.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Boom Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT (Status_Picklist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Payment2ReceiptController.cls
public class Payment2ReceiptController {
  public SalesOrder__c SalesOrder {
    get {
      List<SalesOrder__c> resultsList = [
        SELECT
          Id,
          Name,
          Opportunity__r.Account_Manager_Name__c,
          ContactBilling__r.Name,
          BillToStreetLong__c,
          BillToCity__c,
          BillToStateProvince__c,
          BillToZipPostalCode__c,
          ContactBuying__r.ACDF_Branch_Office__c
        FROM SalesOrder__c
        WHERE id = :ApexPages.currentPage().getParameters().get('orderId')
      ];

      SalesOrder = resultsList.isEmpty() == false
        ? resultsList.get(0)
        : new SalesOrder__c();

      return SalesOrder;
    }
    private set;
  }

  public list<Payment__c> OrderPayments {
    get {
      String paymentId = ApexPages.currentPage()
        .getParameters()
        .get('paymentId');

      OrderPayments = [
        SELECT
          Id,
          Name,
          Date__c,
          Transaction_Type__c,
          CardType__c,
          Last_Four_Digits__c,
          Amount__c,
          Transaction_Id__c,
          Billing_Name__c,
          Status__c,
          Authorization_Id__c,
          Payment_Method__c
        FROM Payment__c
        WHERE Id = :paymentId
      ];
      OrderPayments.sort();
      return OrderPayments;
    }
    private set;
  }

  public Payment_Method__c paymentMethod {
    get {
      if (
        OrderPayments.size() > 0 &&
        OrderPayments[0].Payment_Method__c != null
      ) {
        paymentMethod = [
          SELECT
            Id,
            Billing_First_Name__c,
            Billing_Last_Name__c,
            Billing_Street__c,
            Billing_City__c,
            Billing_State__c,
            Billing_Postal_Code__c,
            Billing_Country__c
          FROM Payment_Method__c
          WHERE Id = :OrderPayments[0].Payment_Method__c
          LIMIT 1
        ];
      } else {
        paymentMethod = new Payment_Method__c();
      }
      return paymentMethod;
    }
    set;
  }

  public PageReference attachPDF() {
    PageReference p = Page.Payment2VF;
    p.getParameters()
      .put('orderId', ApexPages.currentPage().getParameters().get('orderId'));
    p.getParameters()
      .put(
        'paymentId',
        ApexPages.currentPage().getParameters().get('paymentId')
      );

    Blob body;

    if (Test.isRunningTest()) {
      body = Blob.valueOf('teststring');
    } else {
      body = p.getContent();
    }

    List<Payment__c> currPayments = OrderPayments;

    Attachment a = new Attachment();
    a.ParentId = ApexPages.currentPage().getParameters().get('paymentId');
    a.Body = body;
    a.Name = currPayments[0].Name + '.pdf';
    insert a;

    if (!Test.isRunningTest()) {
      p.setRedirect(true);
    }
    return p;
  }
}