force-app/main/default/objects/Contact/fields/Client_Type__c.field-meta.xml
<CustomField>
    <fullName>Client_Type__c</fullName>
    <label>Client Type</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_AG_link__c.field-meta.xml
<CustomField>
    <fullName>Core_AG_link__c</fullName>
    <label>Core: AG link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_AG_link_NP__c.field-meta.xml
<CustomField>
    <fullName>Core_AG_link_NP__c</fullName>
    <label>Core: AG link – NP</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_AG_link_NP_MS__c.field-meta.xml
<CustomField>
    <fullName>Core_AG_link_NP_MS__c</fullName>
    <label>Core: AG link – NP (MS)</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_AG_link_NP_WF__c.field-meta.xml
<CustomField>
    <fullName>Core_AG_link_NP_WF__c</fullName>
    <label>Core: AG link – NP (WF)</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Alternative_segment__c.field-meta.xml
<CustomField>
    <fullName>Core_Alternative_segment__c</fullName>
    <label>Core: Alternative segment</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Client_type__c.field-meta.xml
<CustomField>
    <fullName>Core_Client_type__c</fullName>
    <label>Core: Client type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Close_date__c.field-meta.xml
<CustomField>
    <fullName>Core_Close_date__c</fullName>
    <label>Core: Close date</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Issue_s__c.field-meta.xml
<CustomField>
    <fullName>Core_Issue_s__c</fullName>
    <label>Core: Issue(s)</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Last_year_link__c.field-meta.xml
<CustomField>
    <fullName>Core_Last_year_link__c</fullName>
    <label>Core: Last year link</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Magazine_name__c.field-meta.xml
<CustomField>
    <fullName>Core_Magazine_name__c</fullName>
    <label>Core: Magazine name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Magazine_readership__c.field-meta.xml
<CustomField>
    <fullName>Core_Magazine_readership__c</fullName>
    <label>Core: Magazine readership</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Magazine_website__c.field-meta.xml
<CustomField>
    <fullName>Core_Magazine_website__c</fullName>
    <label>Core: Magazine website</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Market_city__c.field-meta.xml
<CustomField>
    <fullName>Core_Market_city__c</fullName>
    <label>Core: Market city</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Market_project__c.field-meta.xml
<CustomField>
    <fullName>Core_Market_project__c</fullName>
    <label>Core: Market project</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Market_Sales_Stop_Date__c.field-meta.xml
<CustomField>
    <fullName>Core_Market_Sales_Stop_Date__c</fullName>
    <label>Core: Market Sales Close Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Opp_stage_comments__c.field-meta.xml
<CustomField>
    <fullName>Core_Opp_stage_comments__c</fullName>
    <label>Core: Opp stage comments</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Opportunity_owner_email__c.field-meta.xml
<CustomField>
    <fullName>Core_Opportunity_owner_email__c</fullName>
    <label>Core: Opportunity owner email</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Opportunity_owner_full_name__c.field-meta.xml
<CustomField>
    <fullName>Core_Opportunity_owner_full_name__c</fullName>
    <label>Core: Opportunity owner full name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Opportunity_owner_phone__c.field-meta.xml
<CustomField>
    <fullName>Core_Opportunity_owner_phone__c</fullName>
    <label>Core: Opportunity owner phone</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Core_Opportunity_stage__c.field-meta.xml
<CustomField>
    <fullName>Core_Opportunity_stage__c</fullName>
    <label>Core: Opportunity stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market_Name__c.field-meta.xml
<CustomField>
    <fullName>Market_Name__c</fullName>
    <formula>Market_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AG_link_no_price__c.field-meta.xml
<CustomField>
    <fullName>AG_link_no_price__c</fullName>
    <formula>Market_Project__r.AG_link_no_price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AG link no price</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AG_link_no_price_MS__c.field-meta.xml
<CustomField>
    <fullName>AG_link_no_price_MS__c</fullName>
    <formula>Market_Project__r.AG_link_no_price_MS__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AG link no price (MS)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AG_link_no_price_WF__c.field-meta.xml
<CustomField>
    <fullName>AG_link_no_price_WF__c</fullName>
    <formula>Market_Project__r.AG_link_no_price_WF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AG link no price (WF)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Alternative_Segment__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Segment__c</fullName>
    <label>Alternative Segment</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_Type__c.field-meta.xml
<CustomField>
    <fullName>Client_Type__c</fullName>
    <formula>(Contact__r.Client_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company_Specific_AG__c.field-meta.xml
<CustomField>
    <fullName>Company_Specific_AG__c</fullName>
    <formula>IF(CONTAINS(ACDF_Branch_Office__c, &quot;Wells Fargo&quot;),  Pardot_Friendly_WF_AG_Link__c , IF(CONTAINS(ACDF_Branch_Office__c, &quot;Morgan Stanley&quot;),  Pardot_Friendly_MS_AG_Link__c ,  Pardot_Friendly_AG_Link__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Specific AG</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_Templates_Issue_s__c.field-meta.xml
<CustomField>
    <fullName>Email_Templates_Issue_s__c</fullName>
    <formula>Market_Project__r.Issue_Issues__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Templates: Issue(s)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_Templates_Magazine__c.field-meta.xml
<CustomField>
    <fullName>Email_Templates_Magazine__c</fullName>
    <formula>Market_Project__r.Magazine_Text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Templates: Magazine</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_Templates_Magazine_Section__c.field-meta.xml
<CustomField>
    <fullName>Email_Templates_Magazine_Section__c</fullName>
    <formula>Market_Project__r.LY_Magazine_Section__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Templates: Magazine Section</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_Templates_Market_City__c.field-meta.xml
<CustomField>
    <fullName>Email_Templates_Market_City__c</fullName>
    <formula>Market_Project__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Templates: Market City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Magazine_Readership__c.field-meta.xml
<CustomField>
    <fullName>Magazine_Readership__c</fullName>
    <formula>Market_Project__r.Magazine_Readership__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Magazine Readership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Magazine_Website__c.field-meta.xml
<CustomField>
    <fullName>Magazine_Website__c</fullName>
    <formula>Market_Project__r.Magazine_Website__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Magazine Website</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Market_Close_Date__c</fullName>
    <formula>Market_Project__r.Market_Close_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Name__c.field-meta.xml
<CustomField>
    <fullName>Market_Name__c</fullName>
    <formula>Market_Project__r.Name</formula>
    <label>Market Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Sales_Stop_Date__c.field-meta.xml
<CustomField>
    <fullName>Market_Sales_Stop_Date__c</fullName>
    <description>Shows the sales close date of an opportunitie&apos;s market project on the opportunity, used mostly for analytics</description>
    <formula>Market_Project__r.Sales_Close__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Sales Stop Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Email__c</fullName>
    <formula>Owner.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Owner Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Full_Name__c</fullName>
    <formula>Owner.FirstName &amp; &quot; &quot; &amp; Owner.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Owner Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Owner_Phone__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Phone__c</fullName>
    <formula>Owner.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Owner Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pardot_Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Pardot_Campaign_Type__c</fullName>
    <label>Pardot Campaign Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>WSJ Showcase I</fullName>
            </value>
            <value>
                <fullName>WSJ Showcase II</fullName>
            </value>
            <value>
                <fullName>WiW WSJ Showcase I</fullName>
            </value>
            <value>
                <fullName>WiW WSJ Showcase II</fullName>
            </value>
            <value>
                <fullName>WiW MAG Showcase I</fullName>
            </value>
            <value>
                <fullName>Forbes Investment Guide I</fullName>
            </value>
            <value>
                <fullName>Forbes Investment Guide II</fullName>
            </value>
            <value>
                <fullName>BFF Showcase</fullName>
            </value>
            <value>
                <fullName>Digital Showcase I</fullName>
            </value>
            <value>
                <fullName>Digital Showcase II</fullName>
            </value>
            <value>
                <fullName>Alumni Showcase I</fullName>
            </value>
            <value>
                <fullName>Alumni Showcase II</fullName>
            </value>
            <value>
                <fullName>Relocation Guide I</fullName>
            </value>
            <value>
                <fullName>Relocation Guide II</fullName>
            </value>
            <value>
                <fullName>Airline Mag Showcase I</fullName>
            </value>
            <value>
                <fullName>Other Alt Media I</fullName>
            </value>
            <value>
                <fullName>Other Alt Media II</fullName>
            </value>
            <value>
                <fullName>Post-market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Comment__c.field-meta.xml
<CustomField>
    <fullName>Stage_Comment__c</fullName>
    <label>Stage Comment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Continue to receive emails</fullName>
            </value>
            <value>
                <fullName>Remove from email campaigns</fullName>
            </value>
            <value>
                <fullName>Do not contact me regarding other promotions this year</fullName>
            </value>
            <value>
                <fullName>Contact me about future promotions</fullName>
            </value>
            <value>
                <fullName>Remove contact permanently</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Out of Area</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppContactDataTriggerHelper.cls
public class OppContactDataTriggerHelper {
  public static void updateContactFromOpp(List<Opportunity> lstOpportunity) {
    List<Contact> lstContactToUpdate = new List<Contact>();
    // for (Opportunity opp : lstOpportunity) {
    //   if (opp.Pardot_Campaign_Type__c == 'Post-market')
    //     lstContactToUpdate.add(PopulatePostDetails(opp));
    //   if (opp.Pardot_Campaign_Type__c == 'Core')
    //     lstContactToUpdate.add(PopulateCoreDetails(opp));
    // }
    // if (lstContactToUpdate.size() > 0)
    //   update lstContactToUpdate;
  }
  private static Contact PopulateCoreDetails(Opportunity opp) {
    Contact con = new Contact();
    con.Id = opp.Contact__c;
    con.Core_AG_link_NP_MS__c = opp.AG_link_no_price_MS__c;
    con.Core_AG_link_NP_WF__c = opp.AG_link_no_price_WF__c;
    con.Core_AG_link_NP__c = opp.AG_link_no_price__c;
    con.Core_AG_link__c = opp.Company_Specific_AG__c;
    con.Core_Alternative_segment__c = opp.Alternative_Segment__c;
    con.Core_Client_type__c = opp.Client_Type__c;
    con.Core_Close_date__c = getFormattedDate(opp.Market_Close_Date__c);
    con.Core_Issue_s__c = opp.Email_Templates_Issue_s__c;
    con.Core_Last_year_link__c = opp.Email_Templates_Magazine_Section__c;
    con.Core_Magazine_name__c = opp.Email_Templates_Magazine__c;
    con.Core_Magazine_readership__c = string.ValueOf(
      opp.Magazine_Readership__c
    );
    con.Core_Magazine_website__c = opp.Magazine_Website__c;
    con.Core_Market_Sales_Stop_Date__c = getFormattedDate(
      opp.Market_Sales_Stop_Date__c
    ); //string.ValueOf(opp.Market_Sales_Stop_Date__c);
    con.Core_Market_city__c = opp.Email_Templates_Market_City__c;
    con.Core_Market_project__c = opp.Market_Name__c;
    con.Core_Opp_stage_comments__c = opp.Stage_Comment__c;
    con.Core_Opportunity_owner_full_name__c = opp.Opportunity_Owner_Full_Name__c;
    con.Core_Opportunity_owner_email__c = opp.Opportunity_Owner_Email__c;
    con.Core_Opportunity_owner_phone__c = opp.Opportunity_Owner_Phone__c;
    con.Core_Opportunity_stage__c = opp.StageName;
    con.Core_Profession__c = opp.Email_Templates_Profession__c;
    con.Core_Publication_month__c = opp.Publication_Month__c;
    con.Core_Publication_year__c = opp.Email_Templates_Publication_Year__c;

    return con;
  }
  private static Contact PopulatePostDetails(Opportunity opp) {
    Contact con = new Contact();
    con.Id = opp.Contact__c;
    con.Post_market_AG_link_NP_MS__c = opp.AG_link_no_price_MS__c;
    con.Post_market_AG_link_NP_WF__c = opp.AG_link_no_price_WF__c;
    con.Post_market_AG_link_NP__c = opp.AG_link_no_price__c;
    con.Post_market_AG_link__c = opp.Company_Specific_AG__c;
    con.Post_market_Alternative_segment__c = opp.Alternative_Segment__c;
    con.Post_market_Client_type__c = opp.Client_Type__c;
    con.Post_market_Close_date__c = string.ValueOf(opp.Market_Close_Date__c);
    con.Post_market_Issue_s__c = opp.Email_Templates_Issue_s__c;
    con.Post_market_Last_year_link__c = opp.Email_Templates_Magazine_Section__c;
    con.Post_market_Magazine_name__c = opp.Email_Templates_Magazine__c;
    con.Post_market_Magazine_readership__c = string.ValueOf(
      opp.Magazine_Readership__c
    );
    con.Post_market_Magazine_website__c = opp.Magazine_Website__c;
    //con.Core_Market_Sales_Stop_Date__c= string.ValueOf(opp.Market_Sales_Stop_Date__c);
    con.Post_market_Market_city__c = opp.Email_Templates_Market_City__c;
    con.Post_market_Market_project__c = opp.Market_Name__c;
    con.Post_market_Opp_stage_comments__c = opp.Stage_Comment__c;
    con.Post_market_Opportunity_owner_name__c = opp.Opportunity_Owner_Full_Name__c;
    con.Post_market_Opportunity_owner_email__c = opp.Opportunity_Owner_Email__c;
    con.Post_market_Opportunity_owner_name__c = opp.Opportunity_Owner_Full_Name__c;
    con.Post_market_Opportunity_owner_phone__c = opp.Opportunity_Owner_Phone__c;
    con.Post_market_Opportunity_stage__c = opp.StageName;
    con.Post_market_Profession__c = opp.Email_Templates_Profession__c;
    con.Post_market_Publication_month__c = opp.Publication_Month__c;
    con.Post_market_Publication_year__c = opp.Email_Templates_Publication_Year__c;
    con.amreg_code__c = opp.amreg_code__c;
    return con;
  }

  private static String getFormattedDate(Date datefield) {
    if (datefield == null)
      return '';
    Map<Integer, String> monthNameMap = new Map<Integer, String>{
      1 => 'January',
      2 => 'February',
      3 => 'March',
      4 => 'April',
      5 => 'May',
      6 => 'June',
      7 => 'July',
      8 => 'August',
      9 => 'September',
      10 => 'October',
      11 => 'November',
      12 => 'December'
    };
    Datetime dt = DateTime.newInstance(datefield, Time.newInstance(0, 0, 0, 0));
    String dayOfWeek = dt.format('EEEE');
    String monthName = dt.format('MMMMM');
    integer Day = datefield.day();
    integer year = datefield.Year();

    return dayOfWeek + ', ' + monthName + ' ' + Day + ', ' + year;
  }
  /*  public static void sendEmail(List < Opportunity > lstOppsToSendEmail) {

      List < EmailTemplate > et = new List < EmailTemplate > ();
      if (Schema.sObjectType.EmailTemplate.isAccessible()) {
       et = [
        SELECT Id, HTMLValue
        FROM EmailTemplate
        WHERE DeveloperName = 'Buyer_No_Interest_Survey'
       ];
      }
    
      //loop through and build emails for the orders
      List < Messaging.SingleEmailMessage > emailList = new List < Messaging.SingleEmailMessage > ();
    
      for (Opportunity opp: lstOppsToSendEmail) {
    
       //otherwise send 1 email per order
       Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
    
       List < String > recipients = new List < String > ();
       recipients.add('sakethasfmc@gmail.com');
       recipients.add('greg.thatcher@fivestarprofessional.com');
       recipients.add('mdazer@salesforce.com');
       
       email.setToAddresses(recipients);
       system.debug('To addresses are ' + recipients);
       if(!Test.isRunningTest())
            email.setTemplateId(et[0].Id);
       else
       {
           email.setHtmlBody('Test');
       }
       email.setWhatId(opp.Id);
       //email.RelatedToId= anOrder.Id;
       email.setTreatTargetObjectAsRecipient(false);
       if (opp.Contact__c != null) {
    
        email.setTargetObjectId(opp.Contact__c);
    
       }
    
       emailList.add(email);
      }
      system.debug('Emails==='+emailList);
      Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList);
    
    system.debug('results ==='+results );
    
    
     } */
}