force-app/main/default/objects/Contact/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Professionals</relationshipLabel>
    <relationshipName>Professionals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MX_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Customer_Id__c</fullName>
    <label>MX Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Account.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>All the Markets Five Star Works in by Geography, Profession, and Year.</description>
    <label>Market</label>
    <nameField>
        <label>Market Project</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Geographic Area</description>
    <inlineHelpText>Geographic Area</inlineHelpText>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Core_Market__c.field-meta.xml
<CustomField>
    <fullName>Core_Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Core Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Opportunities (Core Market)</relationshipLabel>
    <relationshipName>Alt_Media_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market Project</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Account.Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/Order_Line_Recipient__c.object-meta.xml
<CustomObject>
    <label>Order Line Recipient</label>
    <nameField>
        <displayFormat>OLR-{000000}</displayFormat>
        <label>Line Recipient Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>Order Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Market_Project__c.field-meta.xml
<CustomField>
    <fullName>Market_Project__c</fullName>
    <formula>Order__r.Market__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Line Recipients</relationshipLabel>
    <relationshipName>Order_Line_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Recipient__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Order_Line_Recipients1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check or Money Order</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>ECheck</fullName>
            </value>
            <value>
                <fullName>Electronic Funds Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Ship_To_City__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_City__c</fullName>
    <label>Ship To City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>For recording manual payments like a check or cash, please choose &quot;Completed&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Last_4_Digits_of_Card__c.field-meta.xml
<CustomField>
    <fullName>Last_4_Digits_of_Card__c</fullName>
    <label>Last 4 Digits of Card</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/MX_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Customer_Id__c</fullName>
    <formula>Contact__r.MX_Customer_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MX Customer Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/ContactBilling__c.field-meta.xml
<CustomField>
    <fullName>ContactBilling__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT (Status_Picklist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Actual_Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Actual_Selling_Price__c</fullName>
    <label>Actual Selling Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>SalesOrder__r.ContactBilling__r.Market_Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesOrder__c.field-meta.xml
<CustomField>
    <fullName>SalesOrder__c</fullName>
    <label>Order Number</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/SalesPrice__c.field-meta.xml
<CustomField>
    <fullName>SalesPrice__c</fullName>
    <label>Sales Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(SalesOrder__r.Status_Picklist__c)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ECommerceAPI.cls
@RestResource(urlMapping='/ecommerce/*')
global with sharing class ECommerceAPI {
/**
 You can test this class as follows in execute anonymous:

  ECommerceAPI.eCommerceRequestResource ecr = new ECommerceAPI.eCommerceRequestResource().mock();
  ecr = ECommerceAPI.processBody(JSON.serialize(ecr),'test');

**/
    
  // static final Id ECOMMERCE_PRICEBOOKID = Test.isRunningTest() ? Test.getStandardPricebookId() : '01s6T0000015dLrQAI';
  static final Id ECOMMERCE_PRICEBOOKID = Test.isRunningTest() ? Test.getStandardPricebookId() : '01s6T000001Ywcp';

  @HttpPost
  global static void postMethod() {
    RestRequest req = RestContext.request;
    String uri = req.requestURI;
    String body = req.requestBody.toString();
    RestResponse res = RestContext.response;
  	eCommerceRequestResource ecrr = processBody(body, uri);
    res.statusCode = 200;
    res.responseBody = blob.valueOf(JSON.serialize(ecrr));
  }

  public static eCommerceRequestResource processBody(String body, String uri){
    eCommerceRequestResource ecrr;
//    try {
      ecrr = (eCommerceRequestResource)JSON.deserialize(body, eCommerceRequestResource.class);
//      try {
        ecrr = saveOrders(ecrr);
//      } catch ( Exception saveException ){
//    	system.debug(saveException);      
//        for ( OpportunityProductResource opr : ecrr.OpportunitiesProducts ){
//          opr.Success = false;
//          opr.ErrorMessage = saveException.getLineNumber()+' '+saveException.getMessage();
//        }   
//        log('POST', uri, body);
//      }
//    } catch ( Exception jsonDeserializeException ){
//      ecrr = new eCommerceRequestResource();
//      ecrr.OpportunitiesProducts = new List<OpportunityProductResource>{new OpportunityProductResource()};
//      ecrr.OpportunitiesProducts[0].Success = false;
//      ecrr.OpportunitiesProducts[0].ErrorMessage = jsonDeserializeException.getLineNumber()+' '+jsonDeserializeException.getMessage();
//      log('POST', uri, jsonDeserializeException.getMessage());
//    }
    log('POST', uri, JSON.serialize(ecrr));
    return ecrr;
  }

  static Map<Id,Opportunity> queryOpportunityMap(Set<Id> opportunityIds){
    return new Map<Id,Opportunity>([
      SELECT Id, AccountId, Core_Market__c, Market_Project__c, (
        SELECT Id, Product2Id, PricebookEntryId
        FROM OpportunityLineItems
      )
      FROM Opportunity
      WHERE Id IN :opportunityIds
    ]);
  }

  static Map<Id,Contact> queryContactMap(Set<Id> contactIds){
    return new Map<Id,Contact>([
      SELECT Id, FirstName, LastName, MX_Customer_Id__c, MailingStreet, MailingCity, MailingState,
      MailingPostalCode, MailingCountry, (
        SELECT Id, Card_Type__c, Last_4_Digits_of_Card__c, ExternalId__c
        FROM Payment_Methods__r
        WHERE Inactive__c = FALSE 
      )
      FROM Contact
      WHERE Id IN :contactIds
    ]);
  }

  static eCommerceRequestResource saveOrders(eCommerceRequestResource e){
    Map<Id,Contact> contactMap = new Map<Id,Contact>();
    contactMap.put(e.BillingAddress.ContactId,null);
    contactMap = queryContactMap(contactMap.keySet());

    Map<Id,Opportunity> opportunityMap = new Map<Id,Opportunity>();
    for ( OpportunityProductResource opr : e.OpportunitiesProducts ){
      opportunityMap.put(opr.OpportunityId, null);
    }
    opportunityMap = queryOpportunityMap(opportunityMap.keySet());

    List<SalesOrder__c> salesOrders = new List<SalesOrder__c>();
    List<SalesOrderProductLine__c> sopls = new List<SalesOrderProductLine__c>();
    List<Payment_Method__c> paymentMethods = new List<Payment_Method__c>();
    List<Payment__c> payments = new List<Payment__c>();
    for ( OpportunityProductResource opr : e.OpportunitiesProducts ){
      if ( !contactMap.containsKey(e.BillingAddress.ContactId) ){
        opr.Success = false;
        opr.ErrorMessage = 'Contact '+e.BillingAddress.ContactId+' not found';
      }
      else if ( !opportunityMap.containsKey(opr.OpportunityId)  ){
        opr.Success = false;
        opr.ErrorMessage = 'Opportunity '+opr.OpportunityId+' not found';
      } else {
          Contact existingContact = contactMap.get(e.BillingAddress.ContactId);
          Opportunity existingOpportunity = opportunityMap.get(opr.OpportunityId);
          SalesOrder__c so = saveSalesOrder(existingOpportunity, e);
		      salesOrders.add(so);
            
          Order_Line_Recipient__c olr = new Order_Line_Recipient__c();
          olr.Order__c = so.Id;
          olr.Recipient__c = existingContact.Id;

          Decimal totalAmount = 0;
          for ( ProductLineResource plr : opr.ProductLines ){
            totalAmount += plr.TotalAmount;
            SalesOrderProductLine__c sopl = new SalesOrderProductLine__c();
            sopl.SalesOrder__r = so;
            sopl.Quantity__c = plr.Quantity;
            sopl.SalesPrice__c = plr.TotalAmount / plr.Quantity;
            sopl.Actual_Selling_Price__c = sopl.SalesPrice__c;
            sopl.Product__c = plr.ProductId;
            sopls.add(sopl);     
          }
          Zealynx.CustomerResource zealynxCustomer = saveZealynxCustomer(existingContact, e.BillingAddress);
          Payment_Method__c paymentMethod;
          for ( Payment_Method__c existingPaymentMethod : existingContact.Payment_Methods__r ){
            if ( 
              existingPaymentMethod.Card_Type__c == e.CreditCard.CardType &&
              existingPaymentMethod.Last_4_Digits_of_Card__c == e.CreditCard.CardNumber.right(4)
            ){
              paymentMethod = existingPaymentMethod;
              break;
            }
          }
          paymentMethod = saveZealynxPaymentMethod(existingContact, paymentMethod, e.CreditCard);
          paymentMethods.add(paymentMethod);

          Payment__c payment = saveZealynxPayment(existingContact, paymentMethod, totalAmount);
          payment.Sales_Order__r = so;
          payment.Ship_To_City__c = e.ShippingAddress.City;
          payment.Status__c = 'Completed';
          payment.Payment_Type__c = 'Credit Card';
          payments.add(payment);
          
          opr.Success = true;
      }
    }
    insert salesOrders;
    
    // insert olr;
    for ( SalesOrderProductLine__c sopl : sopls ){
      sopl.SalesOrder__c = sopl.SalesOrder__r.Id;
      sopl.SalesOrder__r = null;
    }
    insert sopls;

    for(SalesOrder__c so : salesOrders) {
      so.Status_Picklist__c = 'Approved';
    }
    update salesOrders;

    if ( contactMap.size() > 0 ){
      update contactMap.values();
    }
    upsert paymentMethods;
    for ( Payment__c p : payments ){
      p.Payment_Method__c = p.Payment_Method__r.Id;
      p.Payment_Method__r = null;
      p.Sales_Order__c = p.Sales_Order__r.Id;
      p.Sales_Order__r = null;
    }
    insert payments;

    for(Integer i = 0; i < e.OpportunitiesProducts.size(); i++){
      e.OpportunitiesProducts[i].OrderId = salesOrders[i].Id;
    }
    return e;
  }

  static SalesOrder__c saveSalesOrder(Opportunity existingOpportunity, eCommerceRequestResource e){
    SalesOrder__c so = new SalesOrder__c();
    so.Account__c = existingOpportunity.AccountId;
    so.Opportunity__c = existingOpportunity.Id;
    so.ContactBilling__c = e.BillingAddress.ContactId;
    so.ContactBuying__c = e.BillingAddress.ContactId;
    so.ContactShipping__c = e.ShippingAddress.ContactId;
    so.Market__c = existingOpportunity.Market_Project__c;
    so.OrderDate__c = System.Today();
    so.Price_Book__c = ECOMMERCE_PRICEBOOKID;
    return so;
  }

  static Zealynx.CustomerResource saveZealynxCustomer(Contact existingContact, AddressResource billingAddress){
    Zealynx.CustomerResource zealynxCustomer = new Zealynx.CustomerResource();
    if ( String.isNotBlank(existingContact.MX_Customer_Id__c) ){
      zealynxCustomer.id = Long.valueOf(existingContact.MX_Customer_Id__c);
    } else {
      zealynxCustomer.name = billingAddress.FirstName+' '+billingAddress.LastName;
      zealynxCustomer.FirstName = billingAddress.FirstName;
      zealynxCustomer.LastName = billingAddress.LastName;
      zealynxCustomer.REPLACE_number = existingContact.Id;
      zealynxCustomer.address1 = existingContact.MailingStreet;
      //zealynxCustomer.address2 {get; set;} 
      zealynxCustomer.city = existingContact.MailingCity;
      zealynxCustomer.state = existingContact.MailingState;
      zealynxCustomer.zip = existingContact.MailingPostalCode;
      zealynxCustomer.customerType = 'Person';
      zealynxCustomer = zealynxCustomer.save();
      if ( zealynxCustomer.id != null ){
        existingContact.MX_Customer_Id__c = String.valueOf(zealynxCustomer.id);
      }
    }
    return zealynxCustomer;
  }

  static Payment_Method__c saveZealynxPaymentMethod(Contact existingContact, Payment_Method__c paymentMethod, CreditCardResource creditCard){
    if ( paymentMethod == null ){
      paymentMethod = new Payment_Method__c();
      paymentMethod.Contact__c = existingContact.Id;
      paymentMethod.Card_Type__c = creditCard.CardType;
      paymentMethod.Payment_Processor__c = 'MX Merchant';

      Zealynx.CreditCardResource zealynxCreditCardResource = new Zealynx.CreditCardResource();
      zealynxCreditCardResource.customerId = Long.valueOf(existingContact.MX_Customer_Id__c);
      zealynxCreditCardResource.expiryMonth = ''+creditCard.ExpirationMonth;
      zealynxCreditCardResource.expiryYear = ''+creditCard.ExpirationYear;
      zealynxCreditCardResource.cvv = creditCard.CVC;
      zealynxCreditCardResource.REPLACE_number = creditCard.CardNumber;
      zealynxCreditCardResource.name = existingContact.FirstName+' '+existingContact.LastName;
      zealynxCreditCardResource.alias = zealynxCreditCardResource.name + ' '+ creditCard.CardType;
      zealynxCreditCardResource = zealynxCreditCardResource.save();
      if ( zealynxCreditCardResource.id != null ){ 
        paymentMethod.ExternalId__c = String.valueOf(zealynxCreditCardResource.id);
      }
    }
    return paymentMethod;
  }

  static Payment__c saveZealynxPayment(Contact existingContact, Payment_Method__c paymentMethod, Decimal totalAmount){
    Zealynx.PaymentResource zealynxPayment = new Zealynx.PaymentResource();
    zealynxPayment.amount = totalAmount;
    zealynxPayment.paymentType = 'Sale';
    zealynxPayment.tenderType = 'Card';
    zealynxPayment.tenderType = 'WEB';
    zealynxPayment.cardPresent = false;
    zealynxPayment.authOnly = false;
    zealynxPayment.isSettleFunds = true;
    zealynxPayment.customerId = Long.valueOf(existingContact.MX_Customer_Id__c);
    zealynxPayment.cardAccountToken = paymentMethod.ExternalId__c;
    zealynxPayment = zealynxPayment.save();

    Payment__c payment = new Payment__c();
    // payment.Account__c = 
    payment.Contact__c = paymentMethod.Contact__c;
    payment.Amount__c = totalAmount;
    payment.MX_Payment_Id__c = String.valueOf(zealynxPayment.id);
    payment.Date__c = system.today();
    payment.Payment_Method__r = paymentMethod;
    payment.Payment_Processor__c = 'MX Merchant';
    return payment;
  }

  static void log(String method, String requestURI, String requestBody){
    try {
      Task t = new Task();
      t.ActivityDate = system.today();
      t.Subject = method+':'+requestURI;
      t.Description = requestBody;
      insert t;
    } catch ( Exception e){
      system.debug(e);
    }
  }

  public class eCommerceRequestResource {
    List<OpportunityProductResource> OpportunitiesProducts;
  	AddressResource ShippingAddress;
	  AddressResource BillingAddress;
    CreditCardResource CreditCard;

    public eCommerceRequestResource mock(){
      OpportunitiesProducts = new List<OpportunityProductResource>();
      OpportunitiesProducts.add(new OpportunityProductResource().mock('0068F000002qK9C'));
      OpportunitiesProducts.add(new OpportunityProductResource().mock('0068F000002qK9C'));
      OpportunitiesProducts[1].ProductLines[0].ProductId = '01t6T000006BZPwQAO';
      OpportunitiesProducts[1].ProductLines[0].Quantity = 3;
      OpportunitiesProducts[1].ProductLines[0].TotalAmount = 207;
      ShippingAddress = new AddressResource().mock('0038F000007RlXD');
      BillingAddress = new AddressResource().mock('0038F000007RlXD');
      CreditCard = new CreditCardResource().mock();
      return this;
    }
  }
  class OpportunityProductResource {
    String OpportunityId;
    String OrderId;
    Boolean Success;
    String ErrorMessage;
    List<ProductLineResource> ProductLines;

    public OpportunityProductResource mock(){
      return mock('0062C00000H0Ib8QAF');
    }
    public OpportunityProductResource mock(Id opportunityId){
      this.OpportunityId = opportunityId;
      ProductLines = new List<ProductLineResource>{new ProductLineResource().mock()};
      return this;
    }
  } 
  class ProductLineResource {
    String ProductId;
    Decimal Quantity;
    Decimal TotalAmount;

    public ProductLineResource mock(){
      return mock('01t6T000006BZPmQAO');
    }
    public ProductLineResource mock(Id productId){
      this.ProductId = productId;
      Quantity = 2;
      TotalAmount = 90;
      return this;
    }
  }

  public class AddressResource {
    Id ContactId;
    String FirstName;
    String LastName;
    String StreetAddress;
    String City;
    String State;
    String Zip;
    String Country;
    String CompanyName;
    String PhoneNumber;
    String Email;

    public AddressResource mock(Id contactId){
      this.ContactId = contactId;
      FirstName = 'FnameNewCustomer';
      LastName = 'LnameNewCustomer';
      StreetAddress = '123 any st addr2';
      City = 'Seattle';
      State = 'WA';
      Zip = '12345';
      CompanyName = 'ACME Global, Inc.';
      PhoneNumber = '8005551212';
      Email = 'victoriasample@fivestarprofessional.com';
      return this;
    }
  }

  public class CreditCardResource {
    String FirstName;
    String LastName;
    String CardType;
    String CardNumber;        
    Integer ExpirationMonth;        
    Integer ExpirationYear;        
    String CVC;

    public CreditCardResource mock(){
      FirstName = 'asdf';
      LastName = 'asdf';
      CardType = 'Visa';
      CardNumber = '4111111111111111';
      ExpirationMonth = 1;
      ExpirationYear = 22;
      CVC = '123';
      return this;
    }
  }

  public static String sampleRequest(){
 
    return null;
  }
}