force-app/main/default/objects/Contact/fields/MX_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Customer_Id__c</fullName>
    <label>MX Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/MX_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Customer_Id__c</fullName>
    <formula>Contact__r.MX_Customer_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MX Customer Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeleteBoomPaymentMethodControllerTest.cls
@isTest
public with sharing class DeleteBoomPaymentMethodControllerTest {
    @isTest
    private static void testDefaultController() {
        Test.setMock(HttpCalloutMock.class, new ZealynxHttpMockGenerator());

        Account testAcc = BoomTestHelpers.generateAccount();
        Contact testCtc = BoomTestHelpers.generateContact(testAcc.Id);
        
        testCtc.MX_Customer_Id__c = '12345';
        update testCtc;
        
        Payment_Method__c testPm1 = BoomTestHelpers.generateTestPmtMethod(testCtc.Id, true);
        Payment_Method__c testPm2 = BoomTestHelpers.generateTestPmtMethod(testCtc.Id, true);

        testPm1.ExternalId__c = '123456';
        update testPm1;
        


        List<Id> pmIds = new List<Id>{testPm1.Id, testPm2.Id};

        List<Payment_Method__c> pms = [SELECT Id, Contact__c, MX_Customer_Id__c, ExternalId__c FROM Payment_Method__c WHERE Id IN :pmIds];

        ApexPages.StandardController sc1 = new ApexPages.StandardController(pms[0]);
        ApexPages.StandardController sc2 = new ApexPages.StandardController(pms[1]);
        DeleteBoomPaymentMethodController controller1 = new DeleteBoomPaymentMethodController(sc1);
        DeleteBoomPaymentMethodController controller2 = new DeleteBoomPaymentMethodController(sc2);


        controller1.doDelete();
        controller2.doDelete();

        List<Payment_Method__c> pmList = [SELECT Id FROM Payment_Method__c WHERE Id IN :pmIds];

        System.assertEquals(0, pmList.size(), 'All payment methods should be deleted');

    }
}