force-app/main/default/objects/Contact/fields/MX_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Customer_Id__c</fullName>
    <label>MX Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Account.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total transaction amount (including tax, shipping and fees)</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Authorization_Id__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Id__c</fullName>
    <inlineHelpText>Authorization ID returned from payment processor.</inlineHelpText>
    <label>Authorization Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Billing_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Name__c</fullName>
    <label>Billing Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <inlineHelpText>Actual date of payment.</inlineHelpText>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/MX_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Payment_Id__c</fullName>
    <label>MX Payment Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <inlineHelpText>The payment processor or merchant account used to process this payment.  This field is set automatically when external payments are received and recorded, and when payments are processed using the Payment Terminal.</inlineHelpText>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorize.Net</fullName>
            </value>
            <value>
                <fullName>eWay</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>PayPal</fullName>
            </value>
            <value>
                <fullName>WorldPay</fullName>
            </value>
            <value>
                <fullName>MX Merchant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Token__c.field-meta.xml
<CustomField>
    <fullName>Payment_Token__c</fullName>
    <label>Payment Token</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check or Money Order</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>ECheck</fullName>
            </value>
            <value>
                <fullName>Electronic Funds Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Ship_To_City__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_City__c</fullName>
    <label>Ship To City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>For recording manual payments like a check or cash, please choose &quot;Completed&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Transaction Id returned from payment processor.</inlineHelpText>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Merchant_Token__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Token__c</fullName>
    <label>Merchant Token</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/MX_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Customer_Id__c</fullName>
    <formula>Contact__r.MX_Customer_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MX Customer Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MX Merchant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Account Name, which is required. 

To change the required Account name, please update the Additional Account Info field on this Order. If the field is not visible, please contact your Administrator. For Released or Paid Orders, please also update the Invoice and Payment records.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT (Status_Picklist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ECommercePaymentQueueable.cls
global class ECommercePaymentQueueable implements Queueable, Database.AllowsCallouts {
  global class ECommercePaymentResource {
    global Contact contact;
    global Payment_Method__c paymentMethod;
    global SalesOrder__c salesOrder;
    global String city;
    global Decimal amount;
  }

  private List<ECommercePaymentResource> request;
  global ECommercePaymentQueueable(String request) {
    this.request = (List<ECommercePaymentResource>) JSON.deserialize(request, List<ECommercePaymentResource>.class);
  }


  global void execute(QueueableContext qCntxt) {
    if (this.request.size() > 0) {
        Set<Id> salesOrderIds = new Set<Id>();
        for(ECommercePaymentResource payment : this.request) {
            salesOrderIds.add(payment.salesOrder.Id);
        }
        Map<Id,SalesOrder__c> soNameMap = new Map<Id,SalesOrder__c>([
            SELECT Id, Name FROM SalesOrder__c WHERE Id IN :salesOrderIds
        ]);
        List<Payment__c> payments = new List<Payment__c>();
        for(ECommercePaymentResource r: request) {
            Contact existingContact = r.contact;
            Payment_Method__c paymentMethod = r.paymentMethod;
            SalesOrder__c so = r.salesOrder;
            String shipToCity = r.city;
            Decimal totalAmount = r.amount;
            String soName = soNameMap.get(so.Id).Name;
            Zealynx.PaymentResource zealynxPayment = new Zealynx.PaymentResource();
            zealynxPayment.amount = totalAmount;
            zealynxPayment.paymentType = 'Sale';
            zealynxPayment.tenderType = 'Card';
            zealynxPayment.entryClass = 'WEB';
            zealynxPayment.cardPresent = false;
            zealynxPayment.authOnly = false;
            zealynxPayment.isSettleFunds = true;
            zealynxPayment.customerId = Long.valueOf(existingContact.MX_Customer_Id__c);
            zealynxPayment.cardAccountToken = paymentMethod.Merchant_Token__c;
            zealynxPayment.reference = soName;
            zealynxPayment.invoice = soName;
            zealynxPayment = zealynxPayment.save();
        
            Payment__c payment = new Payment__c();
            // payment.Account__c =
            payment.Contact__c = existingContact.Id;
            payment.Billing_Name__c = existingContact.FirstName + ' ' + existingContact.LastName;
        
            payment.Amount__c = totalAmount;
            if(zealynxPayment.status == 'Approved') {
              payment.Status__c = 'Completed';
            } else if(zealynxPayment.status == 'Declined') {
              payment.Status__c = 'Declined';
            } else {
              payment.Status__c = 'Error';
            }
            if(zealynxPayment.id != null) {
              payment.MX_Payment_Id__c = String.valueOf(zealynxPayment.id);
            }
            if(zealynxPayment.reference != null) {
              payment.Transaction_Id__c = String.valueOf(zealynxPayment.reference);
            }
            if(zealynxPayment.paymentToken != null) {
              payment.Payment_Token__c = zealynxPayment.paymentToken;
            }
            if(zealynxPayment.authCode != null) {
              payment.Authorization_Id__c = zealynxPayment.authCode;
            }
            payment.Date__c = system.today();
            payment.Payment_Processor__c = 'MX Merchant';
            payment.Account__c = so.Account__c;
            payment.Ship_To_City__c = shipToCity;
            payment.Payment_Type__c = 'Credit Card';
            payment.Payment_Method__c = paymentMethod.Id;
            payment.Sales_Order__c = so.Id;
      
            payments.add(payment);
        }
        if(payments.size() > 0) {
            insert payments;
        }
    }
  }
}