force-app/main/default/objects/Contact/fields/MX_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Customer_Id__c</fullName>
    <label>MX Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/MX_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Customer_Id__c</fullName>
    <formula>Contact__r.MX_Customer_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MX Customer Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeleteBoomPaymentMethodController.cls
public with sharing class DeleteBoomPaymentMethodController {
  public Payment_Method__c pm { get; set; }

  public DeleteBoomPaymentMethodController(ApexPages.StandardController sc) {
    pm = (Payment_Method__c) sc.getRecord();
  }

  public Pagereference doDelete() {
    if (pm != null) {
      Id ctId = pm.Contact__c;
      if (
        String.isNotEmpty(pm.ExternalId__c) &&
        String.isNotEmpty(pm.MX_Customer_Id__c)
      ) {
        handleApiDelete(pm.ExternalId__c, pm.MX_Customer_Id__c);
        delete pm;
      } else {
        delete pm;
      }

      return new ApexPages.standardController(new Contact(Id = ctId)).view();
    } else {
      return null;
    }
  }

  @future(callout=true)
  public static void handleApiDelete(String externalId, String mxCustomerId) {
    Zealynx.CreditCardResource creditCardResource = new Zealynx.CreditCardResource();
    creditCardResource.customerId = long.valueOf(mxCustomerId);
    creditCardResource.id = long.valueOf(externalId);
    try {
      creditCardResource.deleteCard();
    } catch (Exception e) {
      System.debug(e.getMessage());
      throw e;
    }
  }
}