force-app/main/default/objects/Contact/fields/MX_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Customer_Id__c</fullName>
    <label>MX Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Default payment method for the related contact</description>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/MX_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Customer_Id__c</fullName>
    <formula>Contact__r.MX_Customer_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MX Customer Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentMethodTriggerTest.cls
@isTest
public with sharing class PaymentMethodTriggerTest {
    @isTest
    private static void testMethod1() {
        Test.setMock(HttpCalloutMock.class, new ZealynxHttpMockGenerator());

        Account testAcc = BoomTestHelpers.generateAccount();
        Contact testCtc = BoomTestHelpers.generateContact(testAcc.Id);
        testCtc.MX_Customer_Id__c = '12345';
        update testCtc;
        Payment_Method__c testPm1 = BoomTestHelpers.generateTestPmtMethod(testCtc.Id, true);
        Payment_Method__c testPm2 = BoomTestHelpers.generateTestPmtMethod(testCtc.Id, true);
        Payment_Method__c newPm1 = [SELECT Id, Default__c FROM Payment_Method__c WHERE Id = :testPm1.Id LIMIT 1];
        System.assertEquals(false, newPm1.Default__c, 'Default__c should be false');

        newPm1.Default__c = true;
        update newPm1;

        Payment_Method__c newPm2 = [SELECT Id, Default__c FROM Payment_Method__c WHERE Id = :testPm2.Id LIMIT 1];
        System.assertEquals(false, newPm2.Default__c, 'Default__c should be false');
        newPm2.ExternalId__c = '123456';
        update newPm2;
    }
}