force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Account.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <inlineHelpText>The payment processor or merchant account used to process this payment.  This field is set automatically when external payments are received and recorded, and when payments are processed using the Payment Terminal.</inlineHelpText>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorize.Net</fullName>
            </value>
            <value>
                <fullName>eWay</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>PayPal</fullName>
            </value>
            <value>
                <fullName>WorldPay</fullName>
            </value>
            <value>
                <fullName>MX Merchant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>For recording manual payments like a check or cash, please choose &quot;Completed&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Default payment method for the related contact</description>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MX Merchant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Override_Default_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Override_Default_Payment_Method__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Default Payment Method</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payment_Method__c.Inactive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <valueField>Payment_Method__c.Contact__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentMethodTriggerHelper.cls
public without sharing class PaymentMethodTriggerHelper {
    private static final Map<Id,User> GUEST_USERS = new Map<Id,User>([
        SELECT Id FROM User WHERE Name LIKE '%Guest User%'
    ]);
    public static void beforeInsert(List<Payment_Method__c> newList) {
        for(Payment_Method__c pm : newList) {
            if(GUEST_USERS.keySet().contains(pm.CreatedById)) {
                pm.Default__c = true;
            }
            if(String.isEmpty(pm.Payment_Processor__c)) {
                pm.Payment_Processor__c = 'MX Merchant';
            }
        }
    }


    public static void afterInsert(List<Payment_Method__c> newList) {
        Set<Id> contactIds = new Set<Id>();
        Set<Id> triggerIds = new Set<Id>();

        for(Payment_Method__c pm : newList) {
            if(pm.Default__c == true) {
                contactIds.add(pm.Contact__c);
                triggerIds.add(pm.Id);
            }
        }
        unsetDefaults(contactIds, triggerIds);
    }

    public static void afterUpdate(Map<Id, Payment_Method__c> oldMap, Map<Id, Payment_Method__c> newMap) {
        Set<Id> contactIds = new Set<Id>();
        Set<Id> triggerIds = new Set<Id>();


        for(Id key: newMap.keySet()) {
            Payment_Method__c oldPm = oldMap.get(key);
            Payment_Method__c newPm = newMap.get(key);
            if(newPm.Default__c != oldPm.Default__c && newPm.Default__c == true) {
                contactIds.add(newPm.Contact__c);
                triggerIds.add(newPm.Id);
            }
        }

        unsetDefaults(contactIds, triggerIds);
    }

    public static void afterDelete(List<Payment_Method__c> oldList) {
       
    }

    static void unsetDefaults(Set<Id> contactIds, Set<Id> triggerIds) {
        List<Payment_Method__c> existingPms = [
            SELECT Id, Default__c 
            FROM Payment_Method__c 
            WHERE Id NOT IN :triggerIds
            AND Contact__c IN :contactIds 
            AND Default__c=true
        ];

        if(existingPms.size() > 0) {
            for(Payment_Method__c pm : existingPms) {
                pm.Default__c = false;
            }

            update existingPms;
            
            
        }
        updatePaymentMethods(contactIds);
    }

    @future
    public static void updatePaymentMethods(Set<Id> contactIds) {
        Map<Id,Contact> contactMap = new Map<Id,Contact>([
            SELECT Id, (SELECT Id FROM Payment_Methods__r WHERE Default__c = true ORDER BY CreatedDate DESC LIMIT 1)
            FROM Contact
            WHERE Id IN :contactIds
        ]);

        List<Subscription__c> subscriptions = [
            SELECT Id, Payment_Method__r.Contact__c
            FROM Subscription__c
            WHERE Payment_Method__r.Contact__c IN :contactIds
            AND Override_Default_Payment_Method__c = false
            AND Status__c != 'Cancelled'
            AND Payment_Method__r.Default__c = false
        ];

        List<Payment__c> payments = [
            SELECT Id, Payment_Method__c, Payment_Method__r.Contact__c
            FROM Payment__c
            WHERE Payment_Method__r.Contact__c IN :contactIds
            AND Status__c = 'Scheduled'
            AND Payment_Method__r.Default__c = false
        ];

        List<Payment__c> updatedPayments = new List<Payment__c>();
        List<Subscription__c> updatedSubscriptions = new List<Subscription__c>();

        for(Subscription__c sub : subscriptions) {
            Contact c = contactMap.get(sub.Payment_Method__r.Contact__c);
            if(c.Payment_Methods__r != null && c.Payment_Methods__r.size() > 0) {
                updatedSubscriptions.add(new Subscription__c(
                    Id = sub.Id,
                    Payment_Method__c =  c.Payment_Methods__r[0].Id
                ));
            }
        }

        for(Payment__c pay : payments) {
            Contact c = contactMap.get(pay.Payment_Method__r.Contact__c);
            if(c.Payment_Methods__r != null && c.Payment_Methods__r.size() > 0) {
                updatedPayments.add(new Payment__c(
                    Id = pay.Id,
                    Payment_Method__c =  c.Payment_Methods__r[0].Id
                ));
            }
        }

        if(updatedPayments.size() > 0) {
            update updatedPayments;
        }

        if(updatedSubscriptions.size() > 0) {
            update updatedSubscriptions;
        }

    }
    
}