force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Account.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>For recording manual payments like a check or cash, please choose &quot;Completed&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Alternate_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Contact_Email__c</fullName>
    <label>Alternate Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Send_Invoice_to_Alternate_Contact__c.field-meta.xml
<CustomField>
    <fullName>Send_Invoice_to_Alternate_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This will send invoice and payments to alternate contact</inlineHelpText>
    <label>Send Invoice to Alternate Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT (Status_Picklist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentBatchableHelper.cls
public without sharing class PaymentBatchableHelper {
  public static Map<String, Id> templateMap = new Map<String, Id>{
    'Declined' => queryTemplateId('New_Credit_Card_Declined'),
    'Approved' => queryTemplateId('Boom_Payment_VF_Template')
  };

  public static OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'billing@fivestarprofessional.com'];


  public static Boolean isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1]
  .IsSandbox;

  public static string processEmails(List<Payment__c> newPayments) {

    Messaging.SingleEmailMessage[] approvedMessages = new List<Messaging.SingleEmailMessage>();
    Messaging.SingleEmailMessage[] declinedMessages = new List<Messaging.SingleEmailMessage>();

    for (Payment__c s : newPayments) {
      String emailAddress = '';

      if (
        s.Sales_Order__r.Send_Invoice_to_Alternate_Contact__c == true &&
        String.isNotEmpty(s.Sales_Order__r.Alternate_Contact_Email__c)
      ) {
        emailAddress = s.Sales_Order__r.Alternate_Contact_Email__c;
      } else {
        emailAddress = s.Contact__r.Email;
      }

      if (String.isNotEmpty(emailAddress)) {

        if(s.Status__c == 'Completed') {
          approvedMessages.add(sendEmail(
          'Approved',
          s.Id,
          s.Contact__c,
          emailAddress,
          s.Sales_Order__c,
          true
        ));
        } else if (s.Status__c == 'Declined') {
          declinedMessages.add(sendEmail(
          'Declined',
          s.Id,
          s.Contact__c,
          emailAddress,
          s.Sales_Order__c,
          true
        ));
        }
        
      }

    }

    if (!isSandbox) {
      Messaging.SendEmailResult[] results = new List<Messaging.SendEmailResult>();
      if (approvedMessages.size() > 0) {
        results.addAll(Messaging.sendEmail(approvedMessages));
      }

      if(declinedMessages.size() > 0) {
        results.addAll(Messaging.sendEmail(declinedMessages));
      }

      if (results.size() > 0 && results[0].success) {
        return 'Success';
      } else {
        return 'Error';
      }
    } else {
      return 'Success';
    }
  }

  public static Messaging.SingleEmailMessage sendEmail(
    String status,
    Id paymentId,
    Id contactId,
    String contactEmail,
    Id salesOrderId,
    Boolean isActive
  ) {
    Id templateId = templateMap.get(status);
    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
    List<String> ccAddresses = new List<String>{'accounts.receivable@fivestarprofessional.com'};
    message.setTargetObjectId(contactId);

    if(owea.size() > 0) {
      message.setOrgWideEmailAddressId(owea[0].Id);
    }
    
    message.setUseSignature(false);
    message.setBccSender(false);
    message.setSaveAsActivity(false);
    message.setTemplateID(templateId);
    message.setWhatId(paymentId);
    message.toAddresses = new List<String>{ contactEmail };
    message.setccAddresses(ccAddresses);

    if(status == 'Approved') {
      // PageReference pdf = Page.Payment2VF;

      // pdf.getParameters().put('orderId', (String) salesOrderId);
      // pdf.getParameters().put('paymentId', (String) paymentId);
      // Blob b;
      // if (Test.isRunningTest()) {
      //   b = Blob.valueOf('testbody');
      // } else {
      //   b = pdf.getContent();
      // }
      // // Create the email attachment
      // Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
      // efa.setFileName('Payment_Invoice.pdf');
      // efa.setBody(b);

      // message.setFileAttachments(
      //   new List<Messaging.EmailFileAttachment>{ efa }
      // );

    }

    return message;
    
  }

  public static Id queryTemplateId(String tempName) {
    EmailTemplate temp = [
      SELECT Id, DeveloperName
      FROM EmailTemplate
      WHERE DeveloperName = :tempName
      LIMIT 1
    ];

    return temp.Id;
  }
}