force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Account.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total transaction amount (including tax, shipping and fees)</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Authorization_Id__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Id__c</fullName>
    <inlineHelpText>Authorization ID returned from payment processor.</inlineHelpText>
    <label>Authorization Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <inlineHelpText>Actual date of payment.</inlineHelpText>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/MX_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Payment_Id__c</fullName>
    <label>MX Payment Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Token__c.field-meta.xml
<CustomField>
    <fullName>Payment_Token__c</fullName>
    <label>Payment Token</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Scheduled_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment_Date__c</fullName>
    <inlineHelpText>Scheduled Payment Date is the date on which payment is expected to be paid, and may be used to trigger payment reminders using workflow rules.</inlineHelpText>
    <label>Scheduled Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>For recording manual payments like a check or cash, please choose &quot;Completed&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Transaction Id returned from payment processor.</inlineHelpText>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Authorization</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Merchant_Token__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Token__c</fullName>
    <label>Merchant Token</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Alternate_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Contact_Email__c</fullName>
    <label>Alternate Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Send_Invoice_to_Alternate_Contact__c.field-meta.xml
<CustomField>
    <fullName>Send_Invoice_to_Alternate_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This will send invoice and payments to alternate contact</inlineHelpText>
    <label>Send Invoice to Alternate Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT (Status_Picklist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentBatchable.cls
global class PaymentBatchable implements Database.Batchable<sObject>, Database.AllowsCallouts,Database.Stateful {
  global String queryString;
  global List<Payment__c> newPayments;

  global paymentBatchable() {
    if(newPayments == null) {
      newPayments = new List<Payment__c>();
    }
    if (String.isBlank(queryString)) {
      queryString = 'SELECT Id, Sales_Order__r.Name, Sales_Order__r.Alternate_Contact_Email__c, Sales_Order__r.Send_Invoice_to_Alternate_Contact__c, Sales_Order__c, Contact__c, Contact__r.Email, Payment_Method__r.Merchant_Token__c, Amount__c FROM Payment__c WHERE Id NOT IN :newPayments AND Status__c = \'Scheduled\' AND Scheduled_Payment_Date__c <= TODAY AND Payment_Method__c != null';
    }
    // if (Test.isRunningTest()) {
    //   queryString += ' LIMIT 1';
    // }
  }

  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(queryString);
  }

  global void execute(Database.BatchableContext info, List<Payment__c> scope) {
    System.debug('New payments count: ' + newPayments.size());
    List<Payment__c> paymentsLocal = new List<Payment__c>();
    for (Payment__c s : scope) {
      Zealynx.PaymentResource paymentRecord = new Zealynx.PaymentResource();
      paymentRecord.amount = s.Amount__c;
      paymentRecord.paymentType = 'Sale';
      paymentRecord.entryClass = 'WEB';
      paymentRecord.cardAccountToken = s.Payment_Method__r.Merchant_Token__c;

      paymentRecord.clientReference = s.Sales_Order__r.Name;
      paymentRecord.invoice = s.Sales_Order__r.Name;

      System.debug(paymentRecord);
      Map<String, Object> res = (Map<String, Object>) Zealynx.makePayment(
        paymentRecord
      );
      Zealynx.PaymentResource paymentObj = (Zealynx.PaymentResource) res.get(
        'payment'
      );
      if ((String) paymentObj.status == 'Approved') {
        s.Status__c = 'Completed';
        s.Date__c = (Date) system.today();

        if(!test.isRunningTest()) {
          s.Authorization_Id__c = '' + paymentObj.authCode;    
        }
        
      } else if (
        (String) paymentObj.status == 'Declined'
      ) {
        s.Status__c = 'Declined';
        s.Date__c = (Date) system.today();
      } else {
        s.Status__c = 'Error';
        System.debug('An error has occured in the payment batch process.');
      }
      s.MX_Payment_Id__c = '' + paymentObj.id;
      s.Transaction_Type__c = 'Payment';
      s.Payment_Token__c = (String) paymentObj.paymentToken;
      s.Transaction_Id__c = '' + paymentObj.reference;

      paymentsLocal.add(s);
    }

    newPayments.addAll(paymentsLocal);
  }

  global void finish(Database.BatchableContext info) {
    System.debug('New payments complete count: ' + newPayments.size());

    System.debug('Finished batch process.');
    System.debug(JSON.serializePretty(newPayments));

    if (newPayments.size() > 0) {
      update newPayments;

      PaymentBatchableHelper.processEmails(newPayments);
    }
  }
}