force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Account.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <formula>Amount__c - Transaction_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>For recording manual payments like a check or cash, please choose &quot;Completed&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Alternate_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Contact_Email__c</fullName>
    <label>Alternate Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactBilling__c.field-meta.xml
<CustomField>
    <fullName>ContactBilling__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactBuying__c.field-meta.xml
<CustomField>
    <fullName>ContactBuying__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Buying</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Email_To_Send__c.field-meta.xml
<CustomField>
    <fullName>Email_To_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created to use in invoice email criteria in place of Initial Invoice sent checkbox</description>
    <label>Email To Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Initial_Invoice_Sent__c.field-meta.xml
<CustomField>
    <fullName>Initial_Invoice_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Initial Invoice Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <formula>round(ProductAmount__c + AdditionalChargeCreditAmount__c - TotalDiscountAmount__c + TotalTaxAmount__c + TotalVATAmount__c,2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Send_Invoice_to_Alternate_Contact__c.field-meta.xml
<CustomField>
    <fullName>Send_Invoice_to_Alternate_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This will send invoice and payments to alternate contact</inlineHelpText>
    <label>Send Invoice to Alternate Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT (Status_Picklist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>Payment Update Needed</fullName>
            </value>
            <value>
                <fullName>Subscription Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BoomPdfRest.cls
@RestResource(urlMapping='/attachments/*')
global class BoomPdfRest {
  private static String TEMPLATE_NAME = 'Boom_Order_Invoice';
  public static Boolean isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;

  @HttpPost 
  global static void send(List<String> orderIds, String sessionId) {
    System.debug('hitting the send POST');
    // List<SalesOrder__c> lstOrders = querySalesOrders(orderIds);
    // List<Payment__c> payments = queryCompletedPayments(orderIds);

    // Map<String, SalesOrder__c> ordersToSend = getOrdersToSend(lstOrders);

    // Map<String, Blob> orderToAttachment = constructBlobMap(ordersToSend.values());

    // EmailTemplate template = queryEmailTemplate();
    // List<OrgWideEmailAddress> orgWide = queryOrgWideAddresses();

    // List<Messaging.SingleEmailMessage> allMsg = new List<Messaging.SingleEmailMessage>();

    // for ( SalesOrder__c order : ordersToSend.values() ) {
    //   List<string> toAddress = new List<string>();
    //   List<string> cCAddress = new List<string>();

    //   if (
    //     order.Send_Invoice_to_Alternate_Contact__c == true &&
    //     String.isNotEmpty(order.Alternate_Contact_Email__c)
    //   ) {
    //     toAddress.add(order.Alternate_Contact_Email__c);
    //   } else {
    //     toAddress.add(order.ContactBuying__r.Email);
    //   }

    //   cCAddress.add('billing@fivestarprofessional.com');

    //   Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    //   mail.setTemplateId(template.Id);
    //   if (orgWide != null && orgWide.size() > 0) {
    //     mail.setOrgWideEmailAddressId(orgWide.get(0).Id);
    //   }
    //   mail.setCCAddresses(cCAddress);
    //   mail.setToAddresses(toAddress);
    //   mail.setTreatTargetObjectAsRecipient(false);
    //   mail.setTargetObjectId(order.ContactBilling__c);
    //   mail.setWhatId(order.Id);

    //   if ( orderToAttachment.containsKey(order.Id) ) {
    //     Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
    //     attach.setFileName(order.Name + '.pdf');
    //     attach.setBody( 
    //       Test.isRunningTest() 
    //       ? Blob.valueOf('test') 
    //       : orderToAttachment.get(order.Id) 
    //     );
    //     mail.setFileAttachments(new List<Messaging.EmailFileAttachment>{ attach });
    //   }
    //   allMsg.add(mail);
    // }

    // try {
    //   if (isSandbox || test.isRunningTest()) {
    //     System.debug('inside sandbox, skipping email');
    //     System.debug(JSON.serializePretty(lstOrders));
    //     System.debug(JSON.serializePretty(allMsg));
    //     return;
    //   } 
    //   Messaging.SendEmailResult[] results = Messaging.sendEmail(allMsg);
    //   if (results.get(0).isSuccess()) {
    //     EmailSent(ordersToSend.values());
    //   }

    //   system.debug('results ===' + results);
    //   return;
    // } catch (Exception e) {
    //   System.debug(e.getMessage());
    // }
  }

  private static void emailSent(List<SalesOrder__c> sentOrders) {
    List<SalesOrder__c> ordersToUpdate = new List<SalesOrder__c>();
    for ( SalesOrder__c so : sentOrders ) {
      if ( so.Initial_Invoice_Sent__c == false ) {
        so.Initial_Invoice_Sent__c = true;
        ordersToUpdate.add(so);
      }
    }
    update ordersToUpdate;
  }

  private static EmailTemplate queryEmailTemplate() {
    return [
      SELECT Id
      FROM EmailTemplate
      WHERE DeveloperName = :TEMPLATE_NAME
    ];
  }

  private static List<OrgWideEmailAddress> queryOrgWideAddresses() {
    return [
      SELECT Id
      FROM OrgWideEmailAddress
      WHERE Address = 'accounts.receivable@fivestarprofessional.com'
    ];
  }

  private static Map<String, Blob> constructBlobMap(List<SalesOrder__c> orders) {
    Map<String, Blob> blobMap = new Map<String, Blob>();
    for ( SalesOrder__c order : orders ) {
      Attachment attach = new Attachment();
      attach.ParentId = order.Id;
      PageReference pref = Page.SalesOrderInvoicePDF;
      pref.getParameters().put('id', order.Id);
      pref.setRedirect(true);
      attach.Body = !Test.isRunningTest() ? pref.getContentAsPDF() : Blob.valueOf('running inside test');
      attach.Name = order.Name + '.pdf';
      blobMap.put(order.Id, attach.Body);
    }
    return blobMap;
  }

  private static Map<String, SalesOrder__c> getOrdersToSend(List<SalesOrder__c> orders) {
    Map<String, SalesOrder__c> orderMap = new Map<String, SalesOrder__c>();

    for ( SalesOrder__c so : orders ) {
      if ( (so.Email_To_Send__c == true &&
        so.NetAmount__c > 0 &&
        so.Initial_Invoice_Sent__c == false) || test.isrunningtest() 
      ) {
        orderMap.put(so.Id, so);
      }
    }
    return orderMap;
  }

  private static List<SalesOrder__c> querySalesOrders(List<String> orderIds) {
    return [
      SELECT
        Id,
        Name,
        ContactBilling__c,
        Status_Picklist__c,
        ContactBuying__r.Email,
        Initial_Invoice_Sent__c,
        Email_To_Send__c,
        NetAmount__c,
        Alternate_Contact_Email__c,
        Send_Invoice_to_Alternate_Contact__c
      FROM SalesOrder__c
      WHERE Id IN :orderIds
    ];
  }

  private static List<Payment__c> queryCompletedPayments(List<String> orderIds) {
    return [
      SELECT
        Id,
        Contact__c,
        Contact__r.Email,
        Sales_Order__c,
        Sales_Order__r.Name,
        Sales_Order__r.Send_Invoice_to_Alternate_Contact__c,
        Sales_Order__r.Alternate_Contact_Email__c
      FROM Payment__c
      WHERE Sales_Order__c IN :orderIds AND Status__c = 'Completed'
    ];
  }
}