force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Account.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Billing_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Name__c</fullName>
    <label>Billing Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Order_Name__c.field-meta.xml
<CustomField>
    <fullName>Order_Name__c</fullName>
    <formula>Sales_Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Order_Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Release_Date__c</fullName>
    <formula>Sales_Order__r.DateReleased__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Release Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <inlineHelpText>The payment processor or merchant account used to process this payment.  This field is set automatically when external payments are received and recorded, and when payments are processed using the Payment Terminal.</inlineHelpText>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Authorize.Net</fullName>
            </value>
            <value>
                <fullName>eWay</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>PayPal</fullName>
            </value>
            <value>
                <fullName>WorldPay</fullName>
            </value>
            <value>
                <fullName>MX Merchant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Token__c.field-meta.xml
<CustomField>
    <fullName>Payment_Token__c</fullName>
    <label>Payment Token</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>For recording manual payments like a check or cash, please choose &quot;Completed&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Billing_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_First_Name__c</fullName>
    <label>Billing First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Billing_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Last_Name__c</fullName>
    <label>Billing Last Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <label>Payment Processor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MX Merchant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Alternate_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Contact_Email__c</fullName>
    <label>Alternate Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Released__c.field-meta.xml
<CustomField>
    <fullName>Released__c</fullName>
    <label>Released</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Send_Invoice_to_Alternate_Contact__c.field-meta.xml
<CustomField>
    <fullName>Send_Invoice_to_Alternate_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This will send invoice and payments to alternate contact</inlineHelpText>
    <label>Send Invoice to Alternate Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT (Status_Picklist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>Payment Update Needed</fullName>
            </value>
            <value>
                <fullName>Subscription Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewPaymentTriggerHelper.cls
public without sharing class NewPaymentTriggerHelper {
  public static final String COMPLETED_STATUS = 'Completed';
  public static final String SCHEDULED_STATUS = 'Scheduled';

  public static final List<String> INVALID_STATUSES = new List<String>{
    'Declined',
    'Error',
    'Expired',
    'Reversed',
    'Voided'
  };
  public static final String EMAIL_TEMPLATE = 'Boom_Payment_VF_Template';
  public static Boolean isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1]
  .IsSandbox;

  public static final String MXMERCHANT_PROCESSOR = 'MX Merchant';

  public static void beforeInsert(List<Payment__c> newPayments) {
    Set<Id> pmtMethodIds = new Set<Id>();
    List<Payment__c> paymentsToUpdate = new List<Payment__c>();
    List<Id> SalesOrdersToUnlock = new List<Id>();

    for (Payment__c p : newPayments) {

      if (Approval.isLocked(p.Sales_Order__c)) {
        SalesOrdersToUnlock.add(p.Sales_Order__c);
      }

      if (String.isEmpty(p.Name)) {
        p.Name = 'Payment for Sales Order ' + p.Order_Name__c;
      }

      if (
        String.isEmpty(p.Payment_Processor__c) &&
        p.Payment_Method__c != null &&
        (p.Status__c == SCHEDULED_STATUS ||
        String.isNotEmpty(p.Payment_Token__c))
      ) {
        p.Payment_Processor__c = MXMERCHANT_PROCESSOR;
      }

      if (p.Payment_Method__c != null && String.isEmpty(p.Billing_Name__c)) {
        pmtMethodIds.add(p.Payment_Method__c);
        paymentsToUpdate.add(p);
      }
      
    }

    if(SalesOrdersToUnlock.size() > 0) {
      Approval.unlock(SalesOrdersToUnlock);
    }

    if (pmtMethodIds.size() > 0) {
      Map<Id, Payment_Method__c> pmtMethodMap = new Map<Id, Payment_Method__c>(
        [
          SELECT Id, Billing_First_Name__c, Billing_Last_Name__c
          FROM Payment_Method__c
          WHERE Id IN :pmtMethodIds
        ]
      );

      for (Payment__c p : paymentsToUpdate) {
        Payment_Method__c pm = pmtMethodMap.get(p.Payment_Method__c);
        if (
          String.isNotEmpty(pm.Billing_First_Name__c) &&
          String.isNotEmpty(pm.Billing_Last_Name__c)
        ) {
          p.Billing_Name__c =
            pm.Billing_First_Name__c +
            ' ' +
            pm.Billing_Last_Name__c;
        }
      }
    }
  }

  public static void afterInsert(List<Payment__c> newList) {
    List<Payment__c> completedPayments = new List<Payment__c>();
    List<Id> salesOrdersToLock = new List<Id>();
    for (Payment__c p : newList) {
      if (
        p.Status__c == COMPLETED_STATUS &&
        p.Payment_Method__c != null &&
        p.Order_Release_Date__c != null
      ) {
        completedPayments.add(p);
      }

      if (!Approval.isLocked(p.Sales_Order__c)) {
        salesOrdersToLock.add(p.Sales_Order__c);
      }
    }

    if(salesOrdersToLock.size() > 0) {
      List<SalesOrder__c> queriedOrdersToLock = [SELECT Id FROM SalesOrder__c WHERE Id IN :salesOrdersToLock AND Status_Picklist__c IN ('Released', 'Approved')];
      if(queriedOrdersToLock.size() > 0) {
        Approval.lock(queriedOrdersToLock);
      }
    }

    if (completedPayments.size() > 0) {
      sendEmail(JSON.serialize(completedPayments));
    }
  }

  public static void beforeUpdate(
    List<Payment__c> oldList,
    List<Payment__c> newList
  ) {
    Set<Id> pmtMethodIds = new Set<Id>();
    List<Payment__c> paymentsToUpdate = new List<Payment__c>();
    List<Id> salesOrdersToUnlock = new List<Id>();

    for (Integer i = 0; i < newList.size(); i++) {
        Payment__c p = newList[i];
        Payment__c oldP = oldList[i];

      if (Approval.isLocked(p.Sales_Order__c)) {
        salesOrdersToUnlock.add(p.Sales_Order__c);
      }

      if (
        String.isNotEmpty(p.Payment_Token__c) &&
        String.isEmpty(p.Payment_Processor__c) &&
        p.Payment_Method__c != null
      ) {
        p.Payment_Processor__c = MXMERCHANT_PROCESSOR;
      }

      if (
        (p.Payment_Method__c != oldP.Payment_Method__c ||
        String.isEmpty(p.Billing_Name__c)) && p.Payment_Method__c != null
      ) {
        pmtMethodIds.add(p.Payment_Method__c);
        paymentsToUpdate.add(p);
      }
      
    }
    if(salesOrdersToUnlock.size() > 0) {
      Approval.unlock(salesOrdersToUnlock);
    }

    if (pmtMethodIds.size() > 0) {
      Map<Id, Payment_Method__c> pmtMethodMap = new Map<Id, Payment_Method__c>(
        [
          SELECT Id, Billing_First_Name__c, Billing_Last_Name__c
          FROM Payment_Method__c
          WHERE Id IN :pmtMethodIds
        ]
      );

      for (Payment__c p : paymentsToUpdate) {
        Payment_Method__c pm = pmtMethodMap.get(p.Payment_Method__c);
        if (
          String.isNotEmpty(pm.Billing_First_Name__c) &&
          String.isNotEmpty(pm.Billing_Last_Name__c)
        ) {
          p.Billing_Name__c =
            pm.Billing_First_Name__c +
            ' ' +
            pm.Billing_Last_Name__c;
        }
      }
    }
  }

  public static void afterUpdate(
    List<Payment__c> oldList,
    List<Payment__c> newList
  ) {

    List<Id> unlockedOrders = new List<Id>();


    for (Integer i = 0; i < newList.size(); i++) {
      if (!Approval.isLocked(newList[i].Sales_Order__c)) {
        unlockedOrders.add(newList[i].Sales_Order__c);
      }
    }

    List<SalesOrder__c> ordersToLock = [SELECT Id FROM SalesOrder__c WHERE Id IN :unlockedOrders AND Status_Picklist__c IN ('Approved', 'Released')];
    
    if(ordersToLock.size() > 0) {
      Approval.lock(ordersToLock);
    }
  }

  public static void beforeDelete(List<Payment__c> oldList) {
  }

  @future(callout=true)
  public static void sendEmail(String paymentJson) {
    List<Payment__c> pts = (List<Payment__c>) JSON.deserialize(
      paymentJson,
      List<Payment__c>.class
    );

    DateTime dt = System.Now().addHours(-1);

    List<Payment__c> payments = [
      SELECT
        Id,
        Contact__c,
        Contact__r.Email,
        Sales_Order__c,
        Sales_Order__r.Send_Invoice_to_Alternate_Contact__c,
        Sales_Order__r.Alternate_Contact_Email__c,
        Sales_Order__r.Name
      FROM Payment__c
      WHERE Id IN :pts
      AND Sales_Order__r.Released__c <= :dt
    ];

    Id templateId = [
      SELECT Id, DeveloperName
      FROM EmailTemplate
      WHERE DeveloperName = :EMAIL_TEMPLATE
      LIMIT 1
    ]
    .Id;

    Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>();

    if(payments.size() > 0) {

      for (Payment__c pmt : payments) {
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
  
        String emailAddress = '';
  
        if (
          pmt.Sales_Order__r.Send_Invoice_to_Alternate_Contact__c == true &&
          String.isNotEmpty(pmt.Sales_Order__r.Alternate_Contact_Email__c)
        ) {
          emailAddress = pmt.Sales_Order__r.Alternate_Contact_Email__c;
        } else {
          emailAddress = pmt.Contact__r.Email;
        }
  
        message.setTargetObjectId(pmt.Contact__c);
        message.setSenderDisplayName('Five Star Billing');
        message.setReplyTo('billing@fivestarprofessional.com');
        message.setUseSignature(false);
        message.setBccSender(false);
        message.setSaveAsActivity(false);
        message.setTemplateID(templateId);
        message.setWhatId(pmt.Id);
        message.toAddresses = new List<String>{ emailAddress };
  
        
        // PageReference pdf = Page.Payment/2VF;
  
        // pdf.getParameters().put('orderId', (String) pmt.Sales_Order__c);
        // pdf.getParameters().put('paymentId', (String) pmt.Id);
  
        // pdf.setRedirect(true);
  
        // // Take the PDF content
        // Blob b;
        // if (Test.isRunningTest()) {
        //   System.debug('::PAGE REFERENCE');
        //   System.debug(pdf);
        //   b = Blob.valueOf('testbody');
        // } else {
        //   b = pdf.getContentAsPdf();
        // }
        // // Create the email attachment
        // Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        // efa.setFileName('Payment_For_' + pmt.Sales_Order__r.Name + '.pdf');
        // efa.setBody(b);
  
        // message.setFileAttachments(
        //   new List<Messaging.EmailFileAttachment>{ efa }
        // );
  
        messages.add(message);
      }
  
      if (!isSandbox && !Test.isRunningTest()) {
        try {
          Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        } catch (Exception e) {
          System.debug('Error sending email: ' + e.getMessage());
        }
      } else {
        System.debug('Skipping email send in sandbox mode');
        System.debug(JSON.serializePretty(messages));
      }
    }

    
  }
}