force-app/main/default/objects/FivestarSetting__mdt/FivestarSetting__mdt.object-meta.xml
<CustomObject>
    <label>Fivestar Setting</label>
    <pluralLabel>Fivestar Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FivestarSetting__mdt/fields/Allow_Subscription_Payments__c.field-meta.xml
<CustomField>
    <fullName>Allow_Subscription_Payments__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if you&apos;d like to allow subscription payments</inlineHelpText>
    <label>Allow Subscription Payments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FivestarSetting__mdt/fields/Allow_Subscriptions__c.field-meta.xml
<CustomField>
    <fullName>Allow_Subscriptions__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if you want to run subscription automation.</inlineHelpText>
    <label>Allow Subscriptions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SubscriptionBatchSchedule.cls
global class SubscriptionBatchSchedule implements Schedulable
{
    global void execute(SchedulableContext sc)
    {
        if((FivestarSetting__mdt.getInstance('Universal') != null 
        && FivestarSetting__mdt.getInstance('Universal').Allow_Subscription_Payments__c) 
        || test.isRunningTest()) {
            SubscriptionOrdersBatch batch = new SubscriptionOrdersBatch();
            database.executebatch(batch, 50);
        }

        if(test.isRunningTest() || (
            FivestarSetting__mdt.getInstance('Universal') != null
            && FivestarSetting__mdt.getInstance('Universal').Allow_Subscriptions__c
        )) {
            database.executeBatch(new SubscriptionStatusBatch(), 100);
        }
    }
   
}