force-app/main/default/objects/Kit_Bundle_Member__c/Kit_Bundle_Member__c.object-meta.xml
<CustomObject>
    <label>Kit/Bundle Member</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Kit/Bundle Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kit/Bundle Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/IsKitBundle__c.field-meta.xml
<CustomField>
    <fullName>IsKitBundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Unchecked disables Kit/Bundle function and deletes all Kit/Bundle members.</description>
    <inlineHelpText>Unchecked disables Kit/Bundle function and deletes all Kit/Bundle members.</inlineHelpText>
    <label>Kit/Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/KitBundleTest.cls
@isTest
public with sharing class KitBundleTest {
    @isTest
    private static void testMethod1() {
        Product2 sampleProd1 = BoomTestHelpers.generateProduct();
        Product2 sampleProd2 = BoomTestHelpers.generateProduct();
        Kit_Bundle_Member__c sampleMember = BoomTestHelpers.generateTestKitBundle(sampleProd1.Id, sampleProd2.Id);

        Test.startTest();
        Product2 retProd = [SELECT IsKitBundle__c FROM Product2 WHERE Id = :sampleProd1.Id];
        System.assertEquals(true, retProd.IsKitBundle__c, 'Product should be a kit bundle');
        Test.stopTest();
    }
}