force-app/main/default/objects/Kit_Bundle_Member__c/Kit_Bundle_Member__c.object-meta.xml
<CustomObject>
    <label>Kit/Bundle Member</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Kit/Bundle Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kit/Bundle Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Kit_Bundle_Member__c/fields/ReferenceKitBundle__c.field-meta.xml
<CustomField>
    <fullName>ReferenceKitBundle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit/Bundle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Kit/Bundle Members</relationshipLabel>
    <relationshipName>KitBundles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IsKitBundle__c.field-meta.xml
<CustomField>
    <fullName>IsKitBundle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Unchecked disables Kit/Bundle function and deletes all Kit/Bundle members.</description>
    <inlineHelpText>Unchecked disables Kit/Bundle function and deletes all Kit/Bundle members.</inlineHelpText>
    <label>Kit/Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/KitBundleHelper.cls
public without sharing class KitBundleHelper {
    public static void afterInsert(List<Kit_Bundle_Member__c> newList) {
        Set<Id> parentProductIds = new Set<Id>();
        for(Kit_Bundle_Member__c kbm : newList) {
            parentProductIds.add(kbm.ReferenceKitBundle__c);
        }

        updateParentProducts(parentProductIds);
    }

    public static void updateParentProducts(Set<Id> parentProductIds) {
        List<Product2> parentProducts = [SELECT Id, IsKitBundle__c FROM Product2 WHERE Id IN :parentProductIds];

        for(Product2 p : parentProducts) {
            p.IsKitBundle__c = true;
        }

        update parentProducts;
    }
}