force-app/main/default/objects/Sales_Tax__mdt/Sales_Tax__mdt.object-meta.xml
<CustomObject>
    <label>Sales Tax</label>
    <pluralLabel>Sales Taxes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sales_Tax__mdt/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/SalesOrderProductLine__c.object-meta.xml
<CustomObject>
    <description>Related object to Order for Order Product Lines. A Product is configured when the related Additional Product Info key field Service equals False.</description>
    <label>Sales Order Product Line</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Order Product Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrderProductLine__c/fields/ContactShipping__c.field-meta.xml
<CustomField>
    <fullName>ContactShipping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Shipping</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Sales_Order_Product_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrderProductLine__c/fields/State_Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>State_Tax_Rate__c</fullName>
    <label>State Tax Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ContactTriggerForTaxesHelper.cls
public without sharing class ContactTriggerForTaxesHelper {

    public static void afterUpdate(Map<Id, Contact> oldMap, Map<Id, Contact> newMap) {
        Map<Id, Contact> contactsWithNewStates = new Map<Id, Contact>();

        for(Contact c : newMap.values()) {
            if(oldMap.get(c.Id).MailingState != c.MailingState) {
                contactsWithNewStates.put(c.Id, c);
            }
        }
        
        if(contactsWithNewStates.size() > 0) {
            updateSoplStateTaxes(contactsWithNewStates);
        }
    }

    public static void updateSoplStateTaxes(Map<Id, Contact> ctMap) {
        List<SalesOrderProductLine__c> sopls = [
            SELECT Id,ContactShipping__c
            FROM SalesOrderProductLine__c
            WHERE ContactShipping__c IN :ctMap.keySet()
        ];

        for(SalesOrderProductLine__c sopl : sopls) {
            Contact c = ctMap.get(sopl.ContactShipping__c);
            if(c != null) {
                if(Sales_Tax__mdt.getInstance(c.MailingState) != null) {
                    sopl.State_Tax_Rate__c = Sales_Tax__mdt.getInstance(c.MailingState).Rate__c;
                } else {
                    sopl.State_Tax_Rate__c = 0;
                }
            }
        }

        update sopls;
    }
}