force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BoomPaymentController.cls
global class BoomPaymentController {
  global String PagePDFContent { get; set; }
  global String paymentId {
    get;
    set {
      UpdatePDFContent(value);
    }
  }

  public void UpdatePDFContent(String pmtId) {
    try {
      Payment__c pmt = [
        SELECT Id, Sales_Order__c
        FROM Payment__c
        WHERE Id = :pmtId
        LIMIT 1
      ];
      PageReference pageRef = Page.Payment2VF;
      pageRef.getParameters().put('orderId', (String) pmt.Sales_Order__c);
      pageRef.getParameters().put('paymentId', (String) pmt.Id);
      PagePDFContent = pageRef.getContent()
        .toString()
        .replace('<html style="display:none !important;">', '<html>');
    } catch (System.Exception ex) {
    }
  }
}