force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Main object that captures Payment details. A Payment may be assigned either to an Order or Invoice, not both.</description>
    <label>Payment 2</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments 2</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total transaction amount (including tax, shipping and fees)</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Authorization_Id__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Id__c</fullName>
    <inlineHelpText>Authorization ID returned from payment processor.</inlineHelpText>
    <label>Authorization Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <inlineHelpText>Actual date of payment.</inlineHelpText>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/MX_Payment_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Payment_Id__c</fullName>
    <label>MX Payment Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Token__c.field-meta.xml
<CustomField>
    <fullName>Payment_Token__c</fullName>
    <label>Payment Token</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check or Money Order</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>ECheck</fullName>
            </value>
            <value>
                <fullName>Electronic Funds Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>SalesOrder__c</referenceTo>
    <relationshipLabel>Payments 2</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>For recording manual payments like a check or cash, please choose &quot;Completed&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Transaction Id returned from payment processor.</inlineHelpText>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Authorization</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Boom Payment Method</label>
    <nameField>
        <displayFormat>PM-{00000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boom Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Merchant_Token__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Token__c</fullName>
    <label>Merchant Token</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/MX_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>MX_Customer_Id__c</fullName>
    <formula>Contact__r.MX_Customer_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MX Customer Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/SalesOrder__c.object-meta.xml
<CustomObject>
    <description>Main object for Order details. Contains key data points such as Account Name, Order Contacts, and Payment Information.</description>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO{YYMMDD}-{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOrder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the Account Name, which is required. 

To change the required Account name, please update the Additional Account Info field on this Order. If the field is not visible, please contact your Administrator. For Released or Paid Orders, please also update the Invoice and Payment records.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Approved_Complimentary_Order__c.field-meta.xml
<CustomField>
    <fullName>Approved_Complimentary_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to allow $0 orders to release</description>
    <label>Approved Complimentary Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/ContactBilling__c.field-meta.xml
<CustomField>
    <fullName>ContactBilling__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact Billing</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SalesOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Net_Due__c.field-meta.xml
<CustomField>
    <fullName>Net_Due__c</fullName>
    <formula>NetAmount__c - ( ExistingPayments__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Due After Scheduled and Completed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/OrderDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT (Status_Picklist__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Status_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_Picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>Pending Renewal</fullName>
            </value>
            <value>
                <fullName>Payment Update Needed</fullName>
            </value>
            <value>
                <fullName>Subscription Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOrder__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Subscription</description>
    <inlineHelpText>Related Subscription</inlineHelpText>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Boom Orders</relationshipLabel>
    <relationshipName>Boom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Payment_Method__c.Inactive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contact__c</field>
            <operation>equals</operation>
            <valueField>Payment_Method__c.Contact__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Method__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubscriptionOrdersBatch.cls
global class SubscriptionOrdersBatch implements Database.Batchable<sObject>, Database.AllowsCallouts,Database.Stateful {
    global String queryString;
    public static String declinedCardStatus = 'Payment Update Needed';

    global SubscriptionOrdersBatch() {
        if (String.isBlank(queryString)) {
            queryString = 'SELECT Id, Name, Subscription__c, Net_Due__c, Subscription__r.Payment_Method__c, ';
            queryString += 'Account__c, ContactBilling__c, ';
            queryString += 'Subscription__r.Payment_Method__r.Merchant_Token__c, Subscription__r.Payment_Method__r.MX_Customer_Id__c '; 
            queryString += 'FROM SalesOrder__c WHERE Subscription__r.Payment_Method__c != null AND Subscription__c != null AND Subscription__r.Status__c = \'Active\' AND OrderDate__c = LAST_N_DAYS:28 AND (Status_Picklist__c = \'Pending Renewal\' OR Status_Picklist__c = \'Payment Update Needed\')';
          }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(queryString);
    }
    
    global void execute(Database.BatchableContext info, List<SalesOrder__c> scope) {
        List<Payment__c> paymentsLocal = new List<Payment__c>();
        List<SalesOrder__c> updatedSalesOrders = new List<SalesOrder__c>();
        for(SalesOrder__c s : scope) {
            if(s.Net_Due__c == 0 || test.isRunningTest()) {
              s.Status_Picklist__c = 'Approved';
              s.Approved_Complimentary_Order__c = true;
              if(test.isRunningTest()) {
                s.Approved_Complimentary_Order__c = false;
                s.Status_Picklist__c = 'Pending Renewal';
              } else {
                updatedSalesOrders.add(s);
                continue;  
              }
            }
            Payment__c newPayment = new Payment__c(
                Payment_Method__c = s.Subscription__r.Payment_Method__c,
                Account__c = s.Account__c,
                Amount__c = s.Net_Due__c,
                Sales_Order__c = s.Id,
                Contact__c = s.ContactBilling__c,
                Date__c = System.today(),
                Payment_Type__c = 'Credit Card'
            );

            Zealynx.PaymentResource pR = new Zealynx.PaymentResource();
            pR.amount = s.Net_Due__c;
            pR.paymentType = 'Sale';
            pR.entryClass = 'WEB';
            pR.cardAccountToken = s.Subscription__r.Payment_Method__r.Merchant_Token__c;
            pR.clientReference = s.Name.length() > 16 ? s.Name.replaceFirst('-', '') : s.Name;
            pR.invoice = s.Name.length() > 16 ? s.Name.replaceFirst('-', '') : s.Name;

            try {
              Map<String, Object> res = (Map<String, Object>) Zealynx.makePayment(pR);
              Zealynx.PaymentResource paymentObj = (Zealynx.PaymentResource) res.get(
                  'payment'
              );
  
              if ((String) paymentObj.status == 'Approved') {
                  newPayment.Status__c = 'Completed';
                  newPayment.Date__c = (Date) system.today();
          
                  if(!test.isRunningTest()) {
                      newPayment.Authorization_Id__c = '' + paymentObj.authCode;    
                  }
                  
                } else if (
                  (String) paymentObj.status == 'Declined'
                ) {
                  newPayment.Status__c = 'Declined';
                  newPayment.Date__c = (Date) system.today();
                  s.Status_Picklist__c = declinedCardStatus;
                  updatedSalesOrders.add(s);
                } else {
                  newPayment.Status__c = 'Error';
                  System.debug('An error has occured in the payment batch process.');
                  s.Status_Picklist__c = declinedCardStatus;
                  updatedSalesOrders.add(s);
                  paymentsLocal.add(newPayment);
                  continue;
                }
                newPayment.MX_Payment_Id__c = '' + paymentObj.id;
                newPayment.Transaction_Type__c = 'Payment';
                newPayment.Payment_Token__c = (String) paymentObj.paymentToken;
                newPayment.Transaction_Id__c = '' + paymentObj.reference;
                paymentsLocal.add(newPayment);
            } catch (Exception err) {
              System.debug(err.getMessage());
              newPayment.Status__c = 'Error';
              s.Status_Picklist__c = declinedCardStatus;
              updatedSalesOrders.add(s);
              paymentsLocal.add(newPayment);
              continue;
            }
            
        }

        if(paymentsLocal.size() > 0) {
          upsert paymentsLocal;
        }

        if(updatedSalesOrders.size() > 0) {
          upsert updatedSalesOrders;
        }

        
        
      }
    
      global void finish(Database.BatchableContext info) {
        if(test.isRunningTest()) {
          Database.executeBatch(new MissedSubscriptionsBatch(), 50);
        } else {
          System.scheduleBatch(new MissedSubscriptionsBatch(), 'Create Pending Renewals for Missed Subscriptions', 30, 50);
        }
      }
}